### ISSUE TITLE
How to instrument java.net.Socket?

### ISSUE THREAD

**Issue by rahjesh-vunet** [open-telemetry/opentelemetry-java-instrumentation#10008]
### Discussed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/10007

<div type='discussions-op-text'>

<sup>Originally posted by **rahjesh-vunet** December  6, 2023</sup>
I have a requirement to create spans for the java.net.Socket calls to the backend from a Spring REST API. I tried to create an extension for this. I have creates the InstrumentationModule, Instrumentation and IgnoredTypesConfigurer.

```
// SocketInstrumentationModule.java
package instrumentation;

import static java.util.Collections.singletonList;

import java.util.List;
import java.util.logging.Logger;

import com.google.auto.service.AutoService;

import io.opentelemetry.javaagent.extension.instrumentation.InstrumentationModule;
import io.opentelemetry.javaagent.extension.instrumentation.TypeInstrumentation;

@AutoService(InstrumentationModule.class)
public final class SocketInstrumentationModule extends InstrumentationModule {
	
	private static Logger logger = Logger.getLogger(SocketInstrumentationModule.class.getName());

	public SocketInstrumentationModule() {
		super("SocketInstrumentation");
		logger.info("SocketInstrumentationModule activated....");
	}

	@Override
	public List<TypeInstrumentation> typeInstrumentations() {
		return singletonList(new SocketInstrumentation());
	}

	@Override
	public boolean isHelperClass(String className) {
		return className.matches("java.net.Socket");
	}
}
```

```
// SocketInstrumentation.java
package instrumentation;

import static net.bytebuddy.matcher.ElementMatchers.any;

import java.util.logging.Logger;

import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.StatusCode;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.context.Context;
import io.opentelemetry.context.Scope;
import io.opentelemetry.javaagent.extension.instrumentation.TypeInstrumentation;
import io.opentelemetry.javaagent.extension.instrumentation.TypeTransformer;
import net.bytebuddy.asm.Advice;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.matcher.ElementMatcher;
import net.bytebuddy.matcher.ElementMatchers;
public class SocketInstrumentation implements TypeInstrumentation {

private static Logger logger = Logger.getLogger(SocketInstrumentation.class.getName());

@Override
public ElementMatcher<TypeDescription> typeMatcher() {
	logger.info("Entering typeMatcher");
	return ElementMatchers.named("java.net.Socket");
}

@Override
public void transform(TypeTransformer typeTransformer) {
	logger.info("Entering transform...");
	typeTransformer.applyAdviceToMethod(any(), this.getClass().getName() + "$SocketPoolAdvice");
}

public static class SocketPoolAdvice {
	@Advice.OnMethodEnter(suppress = Throwable.class)
	public static Scope onEnter(@Advice.Local("otelSpan") Span span, @Advice.Local("otelContext") Context context) {

		logger.info("Entering method");

		Tracer tracer = GlobalOpenTelemetry.getTracer("java.net.socket.instrumentation", "1.0.0");

		span = tracer.spanBuilder("mySpan").startSpan();

		Scope scope = span.makeCurrent();

		return scope;

	}

	@Advice.OnMethodExit(onThrowable = Throwable.class, suppress = Throwable.class)
	public static void onExit(@Advice.Thrown Throwable throwable, @Advice.Local("otelSpan") Span span,
			@Advice.Enter Scope scope) {
		scope.close();

		if (throwable != null) {
			span.setStatus(StatusCode.ERROR, "Exception thrown in method");
		}

		span.end();
	}
}
}

```
```
//SocketIgnoredTypesConfigurer.java
package instrumentation;

import java.util.logging.Logger;

import com.google.auto.service.AutoService;
import io.opentelemetry.javaagent.extension.ignore.IgnoredTypesBuilder;
import io.opentelemetry.javaagent.extension.ignore.IgnoredTypesConfigurer;
import io.opentelemetry.sdk.autoconfigure.spi.ConfigProperties;

@autoservice(IgnoredTypesConfigurer.class)
public class SocketIgnoredTypesConfigurer implements IgnoredTypesConfigurer {

private static Logger logger = Logger.getLogger(SocketIgnoredTypesConfigurer.class.getName());

@Override
public void configure(IgnoredTypesBuilder builder, ConfigProperties config) {
	logger.info(" Allowing class java.net.Socket...");
	builder.allowClass("java.net.Socket");
}
}

```
I build this using maven abd create the jar. I am instrumenting my Spring REST API application using the javaagent and this extension.
```
-javaagent:../../assets/opentelemetry-javaagent-1.32.0.jar -Dotel.javaagent.extensions=../../extension/SocketInstrumentation/target/socket-instrumentation-1.0.jar
```

I could see the logs that prints the log messages in the extension I created.
```
[otel.javaagent 2023-12-06 00:59:03:887 +0530] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.32.0
[otel.javaagent 2023-12-06 00:59:04:534 +0530] [main] INFO instrumentation.SocketIgnoredTypesConfigurer - Allowing class java.net.Socket...
[otel.javaagent 2023-12-06 00:59:04:646 +0530] [main] INFO instrumentation.SocketInstrumentationModule - SocketInstrumentationModule activated....
[otel.javaagent 2023-12-06 00:59:05:097 +0530] [main] INFO instrumentation.SocketInstrumentation - Entering typeMatcher
[otel.javaagent 2023-12-06 00:59:05:097 +0530] [main] INFO instrumentation.SocketInstrumentation - Entering transform...
```

But the OnMethodEnter and OnMethodExit advices are not called. I don't see the logs which were inside these methods. 

My expectation was that calls to any method in java.net.Socket classes should result in creating the span.

Am I missing anything?</div>

**Comment by laurit** [comment]
`any()` also matches constructors use a matcher that matches only the methods you want.

**Comment by rahjesh-vunet** [comment]
Yes @laurit. Exactly. Modified the matcher

```
typeTransformer.applyAdviceToMethod(named("connect"), this.getClass().getName() + "$SocketPoolAdvice");
```

Looking at this error now.

```
[otel.javaagent 2023-12-06 16:34:36:178 +0530] [http-nio-8080-exec-1] DEBUG io.opentelemetry.javaagent.bootstrap.ExceptionLogger - Failed to handle exception in instrumentation for java.net.Socket
java.lang.NoClassDefFoundError: instrumentation/SocketInstrumentation
	at java.base/java.net.Socket.connect(Socket.java:583)
	at java.base/java.net.Socket.<init>(Socket.java:507)
	at java.base/java.net.Socket.<init>(Socket.java:287)
	at otel.vstock.SocketService.sendOrderAndGetAck(SocketService.java:23)
	at otel.vstock.OrderController.placeOrder(OrderController.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:254)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:182)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.servlet.v6_0.OpenTelemetryHandlerMappingFilter.doFilter(OpenTelemetryHandlerMappingFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by laurit** [comment]
In your advice class do not use fields like `logger` from the outer class

**Comment by rahjesh-vunet** [comment]
Thanks @laurit 

The suggestion given by you solve the issue.

**Comment by rahjesh-vunet** [comment]
I am able to instrument the java.net.Socket class
