### ISSUE TITLE
Setting OTEL_EXPORTER_OTLP_HEADERS when using SpringBoot starter fails with ConverterNotFoundException

### ISSUE THREAD

**Issue by c-north-8** [open-telemetry/opentelemetry-java-instrumentation#10268]
### Describe the bug

Using spring boot starter v2.0.0, which introduced an [improvement](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9950) for using the OTEL_EXPORTER_OTLP_HEADERS property, I get the following error message.

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'otel.exporter.otlp.headers' to java.util.Map<java.lang.String, java.lang.String>:

    Property: otel.exporter.otlp.headers
    Value: "api-key=12345"
    Origin: System Environment Property "OTEL_EXPORTER_OTLP_HEADERS"
    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.util.Map<java.lang.String, java.lang.String>]

Action:

Update your application's configuration

### Steps to reproduce

1. Add `opentelemetry-spring-boot-starter` to Maven dependency (v2.0.0) in app
2. Set the following environment variables
     - OTEL_EXPORTER_OTLP_HEADERS=api-key=123
3. Run the app and see error message

### Expected behavior

Setting the environment variable as described by the documentation would result in an `api-key` property being added to the `headers` Map for the OTLP exporter.

### Actual behavior

Application fails to start with a ConverterNotFoundException 

### Javaagent or library instrumentation version

2.0.0_alpha

### Environment

Spring Boot 3.2.1, Java 17

### Additional context

When setting the headers via application.properties (e.g. `otel.exporter.otlp.headers.api-key=12345`), the application works as intended. It is only when trying to set via environment variables that the header is not respected or read.

**Comment by zeitlinger** [comment]
I can't reproduce the issue using the [spring demo](https://github.com/open-telemetry/opentelemetry-java-examples/tree/main/spring-native). 

Please compare this to your setup and point out the difference - or create a draft PR against the demo for illustration.

**Comment by zeitlinger** [comment]
I'm pretty sure it's a duplicate.

**Comment by void-spark** [comment]
Running into a similar/same issue with todays versions.
No time to got to a minimal sample, but did look into it a lot.
@zeitlinger  could it be OtelResourceProperties needs:
    @Bean
    @ConfigurationPropertiesBinding
    public OtelMapConverter otelMapConverter() {
      // needed for otlp exporter headers and OtelResourceProperties
      return new OtelMapConverter();
    }

Instead if/in addition to OpenTelemetryAutoConfiguration?

**Comment by zeitlinger** [comment]
> Running into a similar/same issue with todays versions. No time to got to a minimal sample, but did look into it a lot. [@zeitlinger](https://github.com/zeitlinger) could it be OtelResourceProperties needs: [@bean](https://github.com/bean) @ConfigurationPropertiesBinding public OtelMapConverter otelMapConverter() { // needed for otlp exporter headers and OtelResourceProperties return new OtelMapConverter(); }
> 
> Instead if/in addition to OpenTelemetryAutoConfiguration?

That was a great hint - I managed to find a combination that fails - please check if that precondition is also present in your setup: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/13971

**Comment by void-spark** [comment]
Nice, I was useful :) Not sure if it solves my issue though :D

@zeitlinger It's a pretty complex application, I'm the one who added the OTEL spring boot starter to it though, so I'm pretty sure we don't provider our own OpenTelemetry bean.
The configuration really is pretty very basic :)

So far the stack trace makes me think that via a very long path of bean dependencies one of the auto configured parts (jdbc/jpa or so) tries to pull in a OpenTelemetry bean, before any other OTLP related parts are touched (because jdbc is used in some beans that are very top level).
If that makes no sense, that's ok :)

To give you an idea, this is redacted and minimized/cleaned stack trace I observe:
Note that it fails in creation of the otel bean, so I'm guessing that shows we don't add one ourselves? :)
```
Application stopped with RuntimeException
org.springframework.context.ApplicationContextException: Unable to start web server
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:170)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:621)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:753)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1362)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1351)
..
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:147)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:107)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:517)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:219)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:193)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:167)
	... 8 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webAppConfig': Unsatisfied dependency expressed through field 'currencyConverter':....
....
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dbBlablaDao': Injection of persistence dependencies failed
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: 
    Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: 
        Unsatisfied dependency expressed through method 'dataSourceScriptDatabaseInitializer' parameter 0: Error creating bean with name 'datasource' defined in class path resource [.../PersistenceConfiguration.class]: 
           Error creating bean with name 'openTelemetry' defined in class path resource [io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration$OpenTelemetrySdkConfig.class]: Unsatisfied dependency expressed through method 'openTelemetry' parameter 0: 
               Error creating bean with name 'autoConfiguredOpenTelemetrySdk' defined in class path resource [io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration$OpenTelemetrySdkConfig.class]: Unsatisfied dependency expressed through method 'autoConfiguredOpenTelemetrySdk' parameter 2: 
                   Error creating bean with name 'otel.resource-io.opentelemetry.instrumentation.spring.autoconfigure.internal.properties.OtelResourceProperties': Could not bind properties to 'OtelResourceProperties' : prefix=otel.resource, ignoreInvalidFields=false, ignoreUnknownFields=true
Caused by: org.springframework.beans.factory.BeanCreationException: 
    Error creating bean with name 'datasource' defined in class path resource [.../PersistenceConfiguration.class]: 
        Error creating bean with name 'openTelemetry' defined in class path resource [io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration$OpenTelemetrySdkConfig.class]: 
           Unsatisfied dependency expressed through method 'openTelemetry' parameter 0: 
              Error creating bean with name 'autoConfiguredOpenTelemetrySdk' defined in class path resource [io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration$OpenTelemetrySdkConfig.class]: 
                  Unsatisfied dependency expressed through method 'autoConfiguredOpenTelemetrySdk' parameter 2: 
                      Error creating bean with name 'otel.resource-io.opentelemetry.instrumentation.spring.autoconfigure.internal.properties.OtelResourceProperties': 
                          Could not bind properties to 'OtelResourceProperties' : prefix=otel.resource, ignoreInvalidFields=false, ignoreUnknownFields=true
.......
Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'otel.resource.attributes' to java.util.Map<java.lang.String, java.lang.String>
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.util.Map<java.lang.String, java.lang.String>]

```

**Comment by zeitlinger** [comment]
> Nice, I was useful :) Not sure if it solves my issue though :D

this doesn't give enough information - maybe if you start with debug enabled: https://docs.spring.io/spring-boot/docs/1.5.22.RELEASE/reference/html/boot-features-logging.html#boot-features-logging-console-output

**Comment by void-spark** [comment]
@zeitlinger I will try that, Any specific part you're looking for? :)
I sadly can't provide logs just unredacted :)

**Comment by zeitlinger** [comment]
> [@zeitlinger](https://github.com/zeitlinger) I will try that, Any specific part you're looking for? :) I sadly can't provide logs just unredacted :)

the beans that are loaded - particularly the ones related to observability

**Comment by void-spark** [comment]
@zeitlinger I don't think that's trivial to get, as we have a exception while Spring is loading/creating all it's beans, and some may be lazy loaded and such :)
Mind, it depends how you define loaded, if you mean only the bean definitions, not bean instances, it's a lot easier :D

I can get an impression of some of it by running in a debugger, breaking on the exception, and logging:
((DefaultListableBeanFactory) this.getBeanFactory()).singletonObjects against the application context :)

```
"appConfig" -> {AppConfig$$SpringCGLIB$$0@13197} 
"applicationEventMulticaster" -> {SimpleApplicationEventMulticaster@12960} 
"applicationStartup" -> {DefaultApplicationStartup@12914} 
"autoConfigurationReport" -> {ConditionEvaluationReport@13114} 
"contextAttributes" -> {Collections$UnmodifiableMap@13099}  size = 10
"contextParameters" -> {Collections$UnmodifiableMap@13224}  size = 0
"conversionService" -> {DefaultFormattingConversionService@13155} "ConversionService converters =\n\t@org.springframework.format.annotation.DateTimeFormat java.lang.Long -> java.lang.String: org.springframework.format.datetime.DateTimeFormatAnnotationFormatterFactory@5006a697,@org.springframework.format.annotation.NumberFormat java.lang.Long -> java.lang.String: org.springframework.format.number.NumberFormatAnnotationFormatterFactory@62f3ad90\n\t@org.springframework.format.annotation.DateTimeFormat java.time.Instant -> java.lang.String: org.springframework.format.datetime.standard.Jsr310DateTimeFormatAnnotationFormatterFactory@1c000c2f,java.time.Instant -> java.lang.String : org.springframework.format.datetime.standard.InstantFormatter@5d3a238\n\t@org.springframework.format.annotation.DateTimeFormat java.time.LocalDate -> java.lang.String: org.springframework.format.datetime.standard.Jsr310DateTimeFormatAnnotationFormatterFactory@1c000c2f,java.time.LocalDate -> java.lang.String : org.springframework.format.datetime.standard.TemporalAccessorPrinter@5ee76cf2\n"
"conversionServicePostProcessor" -> {RsaKeyConversionServicePostProcessor@13153} 
"dataSourcePostProcessor" -> {DataSourcePostProcessor@13095} 
"emBeanDefinitionRegistrarPostProcessor" -> {EntityManagerBeanDefinitionRegistrarPostProcessor@13207} 
"environment" -> {ApplicationServletEnvironment@12953} "ApplicationServletEnvironment {activeProfiles=[local], defaultProfiles=[default], propertySources=[ConfigurationPropertySourcesPropertySource {name='configurationProperties'}, StubPropertySource {name='servletConfigInitParams'}, StubPropertySource {name='servletContextInitParams'}, PropertiesPropertySource {name='systemProperties'}, OriginAwareSystemEnvironmentPropertySource {name='systemEnvironment'}, RandomValuePropertySource {name='random'}, OriginTrackedMapPropertySource {name='Config resource 'file [application-local.properties]' via location 'optional:file:./''}, OriginTrackedMapPropertySource {name='Config resource 'class path resource [application.properties]' via location 'optional:classpath:/''}, ApplicationInfoPropertySource {name='applicationInfo'}, ResourcePropertySource {name='class path resource [messages.properties]'}, ResourcePropertySource {name='class path resource [app-info.properties]'}]}"
"errorPageRegistrar" -> {SpringBootServletConfiguration$lambda@13149} 
"errorPageRegistrarBeanPostProcessor" -> {ErrorPageRegistrarBeanPostProcessor@13232} 
"fileWatcher" -> {FileWatcher@13183} 
"globalCompanySelectionImplicitFromPathFilter" -> {FilterRegistrationBean@13161} "globalCompanySelectionImplicitFromPathFilter urls=[/*] order=200"
"healthEndpointGroupsBeanPostProcessor" -> {HealthEndpointConfiguration$HealthEndpointGroupsBeanPostProcessor@13249} 
"io.opentelemetry.instrumentation.spring.autoconfigure.OpenTelemetryAutoConfiguration$OpenTelemetrySdkConfig" -> {OpenTelemetryAutoConfiguration$OpenTelemetrySdkConfig$$SpringCGLIB$$0@13134} 
"jerseyServlet" -> {ServletRegistrationBean@13239} "jerseyServlet urls=[/healthCheck]"
"localeCharsetMappingsCustomizer" -> {HttpEncodingAutoConfiguration$LocaleCharsetMappingsCustomizer@13147} 
"messageSource" -> {ResourceBundleMessageSource@12959} "org.springframework.context.support.ResourceBundleMessageSource: basenames=[messages]"
"meterRegistryPostProcessor" -> {MeterRegistryPostProcessor@13118} 
"methodValidationPostProcessor" -> {MethodValidationPostProcessor@13102} "proxyTargetClass=false; optimize=false; opaque=false; exposeProxy=false; frozen=false"
"metricsRepositoryMethodInvocationListenerBeanPostProcessor" -> {MetricsRepositoryMethodInvocationListenerBeanPostProcessor@13170} 
"observationRegistryPostProcessor" -> {ObservationRegistryPostProcessor@13090} 
"org.springframework.aop.config.internalAutoProxyCreator" -> {AnnotationAwareAspectJAutoProxyCreator@13157} "proxyTargetClass=true; optimize=false; opaque=false; exposeProxy=false; frozen=false"
"org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory" -> {SharedMetadataReaderFactoryContextInitializer$SharedMetadataReaderFactoryBean@13180} 
"org.springframework.boot.autoconfigure.sql.init.DataSourceInitializationConfiguration" -> {DataSourceInitializationConfiguration@13185} 
"org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration" -> {SslAutoConfiguration@13178} 
"org.springframework.boot.autoconfigure.web.embedded.EmbeddedWebServerFactoryCustomizerAutoConfiguration$TomcatWebServerFactoryCustomizerConfiguration" -> {EmbeddedWebServerFactoryCustomizerAutoConfiguration$TomcatWebServerFactoryCustomizerConfiguration@13106} 
"org.springframework.boot.autoconfigure.web.servlet.HttpEncodingAutoConfiguration" -> {HttpEncodingAutoConfiguration@13159} 
"org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryAutoConfiguration" -> {ServletWebServerFactoryAutoConfiguration@13140} 
"org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryConfiguration$EmbeddedTomcat" -> {ServletWebServerFactoryConfiguration$EmbeddedTomcat@13195} 
"org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration$TomcatWebSocketConfiguration" -> {WebSocketServletAutoConfiguration$TomcatWebSocketConfiguration@13211} 
"org.springframework.boot.context.ContextIdApplicationContextInitializer$ContextId" -> {ContextIdApplicationContextInitializer$ContextId@13174} 
"org.springframework.boot.context.internalConfigurationPropertiesBinder" -> {ConfigurationPropertiesBinder$ConfigurationPropertiesBinderFactory@13128} 
"org.springframework.boot.context.properties.BoundConfigurationProperties" -> {BoundConfigurationProperties@13241} 
"org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor" -> {ConfigurationPropertiesBindingPostProcessor@13222} 
"org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor" -> {DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor@13216} 
"org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry" -> {ConfigurationClassParser$ImportStack@13168}  size = 0
"org.springframework.context.annotation.internalAsyncAnnotationProcessor" -> {AsyncAnnotationBeanPostProcessor@13142} "proxyTargetClass=false; optimize=false; opaque=false; exposeProxy=false; frozen=false"
"org.springframework.context.annotation.internalAutowiredAnnotationProcessor" -> {AutowiredAnnotationBeanPostProcessor@13164} 
"org.springframework.context.annotation.internalCommonAnnotationProcessor" -> {CommonAnnotationBeanPostProcessor@13193} 
"org.springframework.context.annotation.internalConfigurationAnnotationProcessor" -> {ConfigurationClassPostProcessor@13091} 
"org.springframework.context.annotation.internalPersistenceAnnotationProcessor" -> {PersistenceAnnotationBeanPostProcessor@13235} 
"org.springframework.context.annotation.internalScheduledAnnotationProcessor" -> {ScheduledAnnotationBeanPostProcessor@13220} 
"org.springframework.context.event.internalEventListenerFactory" -> {DefaultEventListenerFactory@13116} 
"org.springframework.context.event.internalEventListenerProcessor" -> {EventListenerMethodProcessor@13145} 
"org.springframework.jms.annotation.JmsBootstrapConfiguration" -> {JmsBootstrapConfiguration@13176} 
"org.springframework.jms.config.internalJmsListenerAnnotationProcessor" -> {JmsListenerAnnotationBeanPostProcessor@13136} 
"org.springframework.kafka.config.internalKafkaListenerAnnotationProcessor" -> {KafkaListenerAnnotationBeanPostProcessor@13251} 
"org.springframework.retry.annotation.RetryConfiguration" -> {RetryConfiguration@13163} 
"org.springframework.scheduling.annotation.ProxyAsyncConfiguration" -> {ProxyAsyncConfiguration@13126} 
"org.springframework.scheduling.annotation.SchedulingConfiguration" -> {SchedulingConfiguration@13209} 
"org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration" -> {ProxyTransactionManagementConfiguration@13132} 
"org.springframework.transaction.config.internalTransactionAdvisor" -> {BeanFactoryTransactionAttributeSourceAdvisor@13199} "org.springframework.transaction.interceptor.BeanFactoryTransactionAttributeSourceAdvisor: advice org.springframework.transaction.interceptor.TransactionInterceptor@4888d1ea"
"org.springframework.transaction.config.internalTransactionalEventListenerFactory" -> {RestrictedTransactionalEventListenerFactory@13203} 
"otel.exporter.otlp-io.opentelemetry.instrumentation.spring.autoconfigure.internal.properties.OtlpExporterProperties" -> {OtlpExporterProperties@13247} 
"otelKafkaListenerContainerFactoryBeanPostProcessor" -> {ConcurrentKafkaListenerContainerFactoryPostProcessor@13151} 
"otelRestClientBeanPostProcessor" -> {RestClientBeanPostProcessor@13097} 
"otelRestTemplateBeanPostProcessor" -> {RestTemplateBeanPostProcessor@13190} 
"persistenceConfiguration" -> {PersistenceConfiguration$$SpringCGLIB$$0@13187} 
"persistenceExceptionTranslationPostProcessor" -> {PersistenceExceptionTranslationPostProcessor@13088} "proxyTargetClass=true; optimize=false; opaque=false; exposeProxy=false; frozen=false"
"projectingArgumentResolverBeanPostProcessor" -> {ProjectingArgumentResolverRegistrar$ProjectingArgumentResolverBeanPostProcessor@13104} 
"properties" -> {PropertySourcesPlaceholderConfigurer@13258} 
"requestDataValueReplacer" -> {WebSecurityConfig$lambda@13218} 
"server-org.springframework.boot.autoconfigure.web.ServerProperties" -> {ServerProperties@13110} 
"servletContext" -> {ApplicationContextFacade@12948} 
"servletWebServerFactoryCustomizer" -> {ServletWebServerFactoryCustomizer@13124} 
"sessionTrackingModesSetter" -> {AppConfig$lambda@13237} 
"spring.ssl-org.springframework.boot.autoconfigure.ssl.SslProperties" -> {SslProperties@13122} 
"springApplicationArguments" -> {DefaultApplicationArguments@13093} 
"springBootBanner" -> {SpringApplicationBannerPrinter$PrintedBanner@13245} 
"springBootLoggerGroups" -> {LoggerGroups@13260} 
"springBootLoggingLifecycle" -> {LoggingApplicationListener$Lifecycle@13230} 
"springBootLoggingSystem" -> {LogbackLoggingSystem@13201} 
"springBootServletConfiguration" -> {SpringBootServletConfiguration$$SpringCGLIB$$0@13166} 
"springSecurityHandlerMappingIntrospectorBeanDefinitionRegistryPostProcessor" -> {WebMvcSecurityConfiguration$1@13234} 
"sslBundleRegistry" -> {DefaultSslBundleRegistry@13172} 
"sslPropertiesSslBundleRegistrar" -> {SslPropertiesBundleRegistrar@13192} 
"systemEnvironment" -> {Collections$UnmodifiableMap@13144}  size = 56
"systemProperties" -> {Properties@13228}  size = 76
"tomcatServletWebServerFactory" -> {TomcatServletWebServerFactory@13253} 
"tomcatServletWebServerFactoryCustomizer" -> {TomcatServletWebServerFactoryCustomizer@13108} 
"tomcatWebServerFactoryCustomizer" -> {TomcatWebServerFactoryCustomizer@13243} 
"transactionAttributeSource" -> {AnnotationTransactionAttributeSource@13226} 
"transactionInterceptor" -> {TransactionInterceptor@13138} 
"urlSanitizerFilter" -> {FilterRegistrationBean@13255} "urlSanitizerFilter urls=[/*] order=-200"
"validationConfig" -> {ValidationConfig$$SpringCGLIB$$0@13213} 
"validatorFactory" -> {LocalValidatorFactoryBean@13205} 
"webServerFactoryCustomizer" -> {SpringBootServletConfiguration$lambda@13120} 
"webServerFactoryCustomizerBeanPostProcessor" -> {WebServerFactoryCustomizerBeanPostProcessor@13130} 
"websocketServletWebServerCustomizer" -> {TomcatWebSocketServletWebServerCustomizer@13112}
```

**Comment by zeitlinger** [comment]
nothing that looks suspicious there

**Comment by void-spark** [comment]
Hmm, somewhat smaller samples tend to work :)

I think it's an ordering thing.

This registers the map converter (also?) as bean:

![Image](https://github.com/user-attachments/assets/0fc4b1a1-e06d-4b74-b78a-ed712a365134)

If that happens before an OtelResourceProperties is created, the converter is known to Spring, it will use it, all is well.

But Spring doesn't know / isn't told that OtelResourceProperties depends on that converter (that's actually why @ConfigurationPropertiesBinding is needed on that class/bean).
So if somehow something very early on requires OtelResourceProperties, it might get created before the otelMapConverter bean is created, and it fails :)

Just creating a smaller sample that requires OtelResourceProperties (or something that depends on OtelResourceProperties) very early on, I haven't been able to do that. From the huge stack trace in my earlier message, something in the web application context set up requires it early on, through a chain of dependencies :)

**Comment by void-spark** [comment]
Talking about all those converters.. I'm going to double check we don't mess with those somehow, this line from the loaded objects needs some checking:

```
"conversionService" -> {DefaultFormattingConversionService@13155} "ConversionService converters =\n\t@org.springframework.format.annotation.DateTimeFormat java.lang.Long -> java.lang.String: org.springframework.format.datetime.DateTimeFormatAnnotationFormatterFactory@5006a697,@org.springframework.format.annotation.NumberFormat java.lang.Long -> java.lang.String: org.springframework.format.number.NumberFormatAnnotationFormatterFactory@62f3ad90\n\t@org.springframework.format.annotation.DateTimeFormat java.time.Instant -> java.lang.String: org.springframework.format.datetime.standard.Jsr310DateTimeFormatAnnotationFormatterFactory@1c000c2f,java.time.Instant -> java.lang.String : org.springframework.format.datetime.standard.InstantFormatter@5d3a238\n\t@org.springframework.format.annotation.DateTimeFormat java.time.LocalDate -> java.lang.String: org.springframework.format.datetime.standard.Jsr310DateTimeFormatAnnotationFormatterFactory@1c000c2f,java.time.LocalDate -> java.lang.String : org.springframework.format.datetime.standard.TemporalAccessorPrinter@5ee76cf2\n"
```

:)

**Comment by zeitlinger** [comment]
good idea - I've added a dependency to https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/13972/files#diff-cd6117f59740aa02f17c8a886ccc69ef1754f341d208537f148e26f2b0c21375R77

**Comment by void-spark** [comment]
It's always a small thing isn't it? :)

We have this on an @Configuration class:
```
    @Bean
    public ConversionService conversionService() {
        return new DefaultFormattingConversionService();
    }
```

That seems to be what triggers the issue :)

Adding that to smaller samples (not small/minimal, but smaller) seems to trigger the issue too :)

**Comment by zeitlinger** [comment]
great - is there anything that the starter could improve?

**Comment by void-spark** [comment]
Yes, that gives me an actual minimal sample too :)

```
@SpringBootConfiguration
@EnableAutoConfiguration(
        exclude = {
                HibernateJpaAutoConfiguration.class,
                ActiveMQAutoConfiguration.class,
                JmsAutoConfiguration.class,
                NettyAutoConfiguration.class,
                JmxAutoConfiguration.class,
                JmxEndpointAutoConfiguration.class,
                DataSourceAutoConfiguration.class
        }
)
public class SoSmall {
    @Autowired
    OpenTelemetry ringRing;

    @Configuration
    static class MyConf {
        @Bean
        public ConversionService conversionService() {
            return new DefaultFormattingConversionService();
        }
    }

    public static void main(final String[] args) {
        final ConfigurableApplicationContext context = new SpringApplicationBuilder(SoSmall.class).web(WebApplicationType.NONE)
                .run(args);
        final SoSmall smol = context.getBean(SoSmall.class);

        smol.run(context);

        context.close();
    }

    private void run(ConfigurableApplicationContext context) {
        System.out.println("Hello!");
    }
}
```

@zeitlinger it depends, if you expect this to fail, then the Starter is ok :)
Else, it would be nice if it would support this corner case :)

I think there is a reason to have the DefaultFormattingConversionService there, but it's been a while :)
Either it exposes it as a bean (where else it's internal?), or it makes those default formatters available in a place where it was needed :)

**Comment by zeitlinger** [comment]
> Yes, that gives me an actual minimal sample too :)

That was a great help - I created https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/13985 - let's continue the discussion there
