### ISSUE TITLE
DEADLINE_EXCEEDED when using agent + collector + (xray or file) from localhost

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1053]
I'm not sure if this is related to the SDK, agent, or collector. For now posting here.

In my playground app, ever since upgrading to 0.7.0, I believe, I get `DEADLINE_EXCEEDED` on pretty much all OTLP exports. The spans still show up in X-Ray. Perhaps the collector isn't returning a response. One thing that makes me a bit suspicious of the Java side is the deadline triggers at very random times - I've never seen a timeout trigger at values like 935ms, 716ms, etc before (unless it was an explicit adaptive timeout which I don't think this is).

```
[opentelemetry.auto.trace 2020-08-19 07:22:57:651 +0000] [BatchSpanProcessor_ExporterThread_1] WARN io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter - Failed to export spans
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 935274000ns. [remote_addr=otel/172.17.0.10:9100]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:244)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:225)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)
	at io.opentelemetry.proto.collector.trace.v1.TraceServiceGrpc$TraceServiceBlockingStub.export(TraceServiceGrpc.java:201)
	at io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter.export(OtlpGrpcSpanExporter.java:114)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker$1.run(BatchSpanProcessor.java:288)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
[opentelemetry.auto.trace 2020-08-19 07:22:51:634 +0000] [BatchSpanProcessor_ExporterThread_1] WARN io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter - Failed to export spans
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 716645000ns. [buffered_nanos=734111100, waiting_for_connection]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:244)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:225)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)
	at io.opentelemetry.proto.collector.trace.v1.TraceServiceGrpc$TraceServiceBlockingStub.export(TraceServiceGrpc.java:201)
	at io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter.export(OtlpGrpcSpanExporter.java:114)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker$1.run(BatchSpanProcessor.java:288)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by anuraaga** [comment]
At first I thought it might "just be me" but got a report from a totally different app with similar log messages. They're also using python and the python app does not show this.

**Comment by anuraaga** [comment]
My playground app is at https://github.com/aws-samples/aws-xray-sdk-with-opentelemetry-sample/tree/both-otel-and-xray just docker-compose up

**Comment by anuraaga** [comment]
Nevermind, `docker pull otel/opentelemetry-collector-contrib-dev` seems to have fixed it. Living on the edge...

**Comment by iNikem** [comment]
Hm. I have very similar error after upgrading to latest otel-java snapshot:
```
[opentelemetry.auto.trace 2020-08-19 17:18:39:329 +0000] [grpc-default-executor-0] WARN io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter - Failed to export spans
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: ClientCall started after deadline exceeded: -4.614417900s from now
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by anuraaga** [comment]
Are you using dev collector? That might fix it, or maybe it was a fluke that it worked ok for me after docker pull...

**Comment by iNikem** [comment]
There is an actual problem in the current snapshot of otel-java. Don't why newer collector solved it for you, it should not.

**Comment by anuraaga** [comment]
Well I'm not using the current snapshot of otel-java, I believe :) So maybe it's a similar but different error
