### ISSUE TITLE
Getting "java.lang.VerifyError: Illegal type at constant pool entry 208" when using a combination of dropwizard and swagger

### ISSUE THREAD

**Issue by doppleware** [open-telemetry/opentelemetry-java-instrumentation#10609]
### Describe the bug

I am working on instrumenting a project with the following libraries:
com.smoketurner:dropwizard-swagger:1.0.6-1
io.dropwizard:dropwizard-core:1.0.2

When instrumenting with the OTEL agent receive the below error:
```
Exception in thread "main" java.lang.VerifyError: Illegal type at constant pool entry 208 in class io.swagger.jaxrs.listing.ApiListingResource
Exception Details:
  Location:
    io/swagger/jaxrs/listing/ApiListingResource.getListing(Ljavax/ws/rs/core/Application;Ljavax/servlet/ServletConfig;Ljavax/ws/rs/core/HttpHeaders;Ljavax/ws/rs/core/UriInfo;Ljava/lang/String;)Ljavax/ws/rs/core/Response; @308: invokestatic
  Reason:
    Constant pool index 208 is invalid
  Bytecode:
    0000000: 013a 0601 3a07 013a 0801 3a09 013a 0a12
    0000010: 5eb8 0062 3a07 1907 b600 669e 0006 a700
    0000020: f101 3a0b 08bd 0068 5903 2b53 5904 2c53
    0000030: 5905 2d53 5906 1904 5359 0719 0553 3a0c
    0000040: 190c be36 0d03 360e 150e 150d a200 3519
    0000050: 0c15 0e32 3a0f 190f c100 5499 0020 190f
    0000060: c000 543a 0612 5412 6eb8 0074 3a0b 190b
    0000070: 1906 b600 78c6 000c a700 9784 0e01 a7ff
    0000080: cab8 007e 3a0c bb00 5a59 2ab6 0082 1209
    0000090: 1283 08bd 0085 5903 124c 5359 0412 4e53
    00000a0: 5905 1250 5359 0612 5253 5907 1235 53b6
    00000b0: 0089 b700 8c3a 0919 0cb2 0092 b200 9819
    00000c0: 09b8 009e b800 a419 0c19 09b6 00aa 9a00
    00000d0: 06a7 003e b800 a419 0c19 09b6 00ae 3a08
    00000e0: 1908 b900 b201 003a 0a19 0bc6 0016 1906
    00000f0: c600 1119 0b19 0619 0819 09b8 00b6 b600
    0000100: baa7 000e 12bc 5fb8 00c2 a700 0457 002a
    0000110: 3a0b 2b3a 0c2c 3a0d 2d3a 0e19 043a 0f19
    0000120: 053a 1000 190b b600 823a 11b8 00c8 3a12
    0000130: 1912 12ca b800 d019 11b6 00d3 b900 d903
    0000140: 0057 1912 12db b800 d012 0912 8308 bd00
    0000150: 8559 0312 4c53 5904 124e 5359 0512 5053
    0000160: 5906 1252 5359 0712 3553 b600 89b6 00de
    0000170: b900 d903 0057 a700 0e12 bc5f b800 c2a7
    0000180: 0004 5700 0019 10b8 0002 9900 2519 10b6
    0000190: 0003 1204 b600 0599 0018 190b 190c 190b
    00001a0: b400 0619 0d19 0e19 0fb6 0007 a700 1819
    00001b0: 0b19 0c19 0bb4 0006 190d 190e 190f b600
    00001c0: 08a7 0003 3a0b 013a 0ca7 0008 3a0c 013a
    00001d0: 0b19 07b6 00e3 9e00 06a7 007a 190a c700
    00001e0: 06a7 0072 190a b900 e601 0019 0cc6 0013
    00001f0: b800 a419 0819 0901 190c b600 eaa7 0056
    0000200: 190b c100 ec99 000b 190b c000 eca7 0004
    0000210: 013a 0d19 0dc6 001a 190d bb00 ee59 b800
    0000220: a419 0819 09b7 00f1 b900 f502 003a 0d19
    0000230: 06c7 0014 190d c700 0fb8 00a4 1908 1909
    0000240: 0101 b600 eaa7 000e 12bc 5fb8 00c2 a700
    0000250: 0457 0019 0cc6 0006 190c bf19 0bb0     
  Exception Handler Table:
    bci [292, 377] => handler: 377
    bci [15, 260] => handler: 260
    bci [292, 452] => handler: 460
    bci [465, 584] => handler: 584
    bci [260, 266] => handler: 269
    bci [377, 383] => handler: 386
    bci [584, 590] => handler: 593
  Stackmap Table:
    full_frame(@15,{Object[#9],Object[#76],Object[#78],Object[#80],Object[#82],Object[#53],Object[#84],Object[#86],Object[#88],Object[#90],Object[#92]},{})
    same_frame(@33)
    full_frame(@72,{Object[#9],Object[#76],Object[#78],Object[#80],Object[#82],Object[#53],Object[#84],Object[#86],Object[#88],Object[#90],Object[#92],Object[#106],Object[#108],Integer,Integer},{})
    same_frame(@123)
    chop_frame(@129,3)
    append_frame(@212,Object[#88])
    same_frame(@257)
    full_frame(@260,{Object[#9],Object[#76],Object[#78],Object[#80],Object[#82],Object[#53],Object[#84],Object[#86],Object[#88],Object[#90],Object[#92]},{Object[#74]})
    same_locals_1_stack_item_frame(@269,Object[#74])
    same_frame(@270)
    same_frame(@271)
    full_frame(@291,{Object[#9],Object[#76],Object[#78],Object[#80],Object[#82],Object[#53],Object[#84],Object[#86],Object[#88],Object[#90],Object[#92],Object[#9],Object[#76],Object[#78],Object[#80],Object[#82],Object[#53]},{})
    same_locals_1_stack_item_extended(@377,Object[#74])
    same_locals_1_stack_item_frame(@386,Object[#74])
    same_frame(@387)
    same_frame(@388)
    same_frame(@431)
    full_frame(@452,{Object[#9],Object[#76],Object[#78],Object[#80],Object[#82],Object[#53],Object[#84],Object[#86],Object[#88],Object[#90],Object[#92]},{Object[#224]})
    same_locals_1_stack_item_frame(@460,Object[#74])
    append_frame(@465,Object[#224],Object[#74])
    same_frame(@476)
    same_frame(@484)
    same_frame(@512)
    same_frame(@528)
    same_locals_1_stack_item_frame(@529,Object[#236])
    append_frame(@559,Object[#236])
    same_frame(@581)
    full_frame(@584,{Object[#9],Object[#76],Object[#78],Object[#80],Object[#82],Object[#53],Object[#84],Object[#86],Object[#88],Object[#90],Object[#92],Object[#224],Object[#74]},{Object[#74]})
    same_locals_1_stack_item_frame(@593,Object[#74])
    same_frame(@594)
    same_frame(@595)
    same_frame(@603)

	at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:66)
	at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:33)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:79)
	at dropwizard.java.example.ExampleApp.main(ExampleApp.java:16)
```

### Steps to reproduce

I created a sample repo reproducing the issue:
https://github.com/doppleware/drop-wizard-issue

### Expected behavior

Not throw an exception when using the agent

### Actual behavior

Java.lang.VerifyError is thrown

### Javaagent or library instrumentation version

2.1.0, 1.3.2

### Environment

**JDK**:
**OS**:

**Comment by laurit** [comment]
@doppleware I cloned your repository, built it with `mvn clean package -Dmaven.test.skip=true` and ran `java -javaagent:opentelemetry-javaagent-2.1.0-SNAPSHOT.jar -Dotel.traces.exporter=none  -Dotel.logs.exporter=none -Dotel.metrics.exporter=none  -jar target/dropwizard-java-example.jar server` it did not fail.

**Comment by doppleware** [comment]
@laurit you are right!  I tested some more and apparently, our agent extension causes it rather than the agent itself ... Closing the issue, thanks!
