### ISSUE TITLE
java.lang.NoSuchMethodError: 'void io.opentelemetry.contrib.awsxray.propagator.AwsXrayPropagator.inject(...)'

### ISSUE THREAD

**Issue by gdw2** [open-telemetry/opentelemetry-java-instrumentation#10659]
### Describe the bug

I'm getting an exception when trying to send an SNS or SQS message.  Simple repro linked below.

### Steps to reproduce

1. Checkout https://github.com/gdw2/otel-sns.
2. Download the agent jar and put it somewhere.
3. Run 'mvn package'
4. Run it: `java -javaagent:/Users/gwarner/Downloads/opentelemetry-javaagent-1.32.1.jar -Dotel.service.name="greg-test" -Dotel.instrumentation.aws-sdk.experimental-use-propagator-for-messaging=true -cp target/demo-1.0-SNAPSHOT.jar acme.Main`

### Expected behavior

No exception.  SNS/SQS message sent.  

### Actual behavior

```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2024-02-23 16:31:16:741 -0700] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.32.1
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoSuchMethodError: 'void io.opentelemetry.contrib.awsxray.propagator.AwsXrayPropagator.inject(io.opentelemetry.context.Context, java.lang.Object, io.opentelemetry.context.propagation.TextMapSetter)'
	at io.opentelemetry.instrumentation.awssdk.v2_2.TracingExecutionInterceptor.modifyHttpRequest(TracingExecutionInterceptor.java:288)
	at io.opentelemetry.instrumentation.awssdk.v2_2.autoconfigure.TracingExecutionInterceptor.modifyHttpRequest(TracingExecutionInterceptor.java:58)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyHttpRequestAndHttpContent(ExecutionInterceptorChain.java:90)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.runModifyHttpRequestAndHttpContentInterceptors(BaseClientHandler.java:157)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:83)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:151)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:80)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)
	at software.amazon.awssdk.services.sns.DefaultSnsClient.publish(DefaultSnsClient.java:2169)
	at acme.Main.pubTopic(Main.java:42)
	at acme.Main.main(Main.java:22)
```

### Javaagent or library instrumentation version

1.32.1 (also tried the lastest 2.x)

### Environment

**JDK**: 17.0.1
**OS**: Mac OSX Intel

### Additional context

pom.xml has the dependencies I'm using.

**Comment by laurit** [comment]
While this is a bug what you are doing doesn't really make sense. Use either the agent or the manual instrumentation library, you don't need to use both at the same time as they do the same thing.
