### ISSUE TITLE
Scala build cache issue?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1072]
Not exactly sure but it seemed like my local build cache got corrupt when building groovy + scala. The akka-http test failed multiple times when running, until I did clean, then `:test --no-build-cache` and it was fine. I've seen this once before too.

```
groovy.lang.MissingPropertyException: No such property: AkkaHttpTestAsyncWebServer for class: AkkaHttpServerInstrumentationTestAsync
	at AkkaHttpServerInstrumentationTestAsync.startServer(AkkaHttpServerInstrumentationTest.groovy:58)
	at io.opentelemetry.auto.test.base.HttpServerTest.setupSpecUnderRetry(HttpServerTest.groovy:78)
	at io.opentelemetry.auto.test.base.HttpServerTest.setupSpec_closure1(HttpServerTest.groovy:71)
	at io.opentelemetry.auto.test.base.HttpServerTest.setupSpec_closure1(HttpServerTest.groovy)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at io.opentelemetry.auto.test.AgentTestRunner.withRetryOnAddressAlreadyInUse(AgentTestRunner.java:195)
	at io.opentelemetry.auto.test.AgentTestRunner.withRetryOnAddressAlreadyInUse(AgentTestRunner.java:190)
	at io.opentelemetry.auto.test.base.HttpServerTest.setupSpec(HttpServerTest.groovy:70)
```

**Comment by iNikem** [comment]
Cannot reproduce
