### ISSUE TITLE
unclear compatibility with the collector

### ISSUE THREAD

**Issue by hatharom** [open-telemetry/opentelemetry-java-instrumentation#10729]
### Describe the bug

When the collector and javaagent are the latest I get this error when trying to export spans:

```
[otel.javaagent 2024-03-01 12:33:42:554 +0000] [OkHttp http://otelcol:4317/...] ERROR io.opentelemetry.exporter.internal.http.HttpExporter - Failed to export spans. The request could not be executed. Full error message: java.net.SocketException: Connection reset by peer
....
    Suppressed: java.io.IOException: unexpected end of stream on http://otelcol-address:4317/...
                at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:210)
                at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
                at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
                ... 14 more
        Caused by: java.io.EOFException: \n not found: limit=15 content=000006040000000000000500004000…
                at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:339)
                at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
                at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
                ... 16 more
```

when playing with versions by hand it sometimes work
for example collector v0.84.0 works with javaagent 1.30.0

Is there any version matrix?
Or just continue the guessing game?

### Steps to reproduce

launch any random versions

### Expected behavior

to work

### Actual behavior

doesnt work

### Javaagent or library instrumentation version

any

### Environment

**JDK**:
**OS**:

**Comment by hatharom** [comment]
thank you very much, it solved

**Comment by qixiaobo** [comment]
The same problem
