### ISSUE TITLE
Servlet 3.0 instrumentation does not fully cover 3.1 and 4.0

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#1083]
Servlet 3.1 introduced a new method in `ServletOutputStream`: `setWriteListener(WriteListener)`. This method is not implemented in our current servlet 3.0 instrumentation, so when it's called an `AbstractMethodError` is thrown instead:

```
 org.jboss.resteasy.spi.UnhandledException: java.lang.AbstractMethodError: Receiver class io.opentelemetry.instrumentation.auto.servlet.v3_0.CountingHttpServletResponse$CountingServletOutputStream does not define or inherit an implementation of the resolved method 'abstract void setWriteListener(javax.servlet.WriteListener)' of abstract class javax.servlet.ServletOutputStream.
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
	at org.jboss.resteasy.core.SynchronousDispatcher.asynchronousExceptionDelivery(SynchronousDispatcher.java:571)
...
Caused by: java.lang.AbstractMethodError: Receiver class io.opentelemetry.instrumentation.auto.servlet.v3_0.CountingHttpServletResponse$CountingServletOutputStream does not define or inherit an implementation of the resolved method 'abstract void setWriteListener(javax.servlet.WriteListener)' of abstract class javax.servlet.ServletOutputStream.
	at org.jboss.resteasy.plugins.server.servlet.HttpServletResponseWrapper$DeferredOutputStream.queue(HttpServletResponseWrapper.java:204)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletResponseWrapper$DeferredOutputStream.asyncWrite(HttpServletResponseWrapper.java:179)
	at org.jboss.resteasy.util.CommitHeaderAsyncOutputStream.asyncWrite(CommitHeaderAsyncOutputStream.java:94)
	at org.jboss.resteasy.spi.AsyncOutputStream.asyncWrite(AsyncOutputStream.java:23)
...
```

I ran into this issue when I was unit testing RESTEasy 4.5.6: it looks like they actually use this new method when dealing with an `AsyncResponse`: https://github.com/resteasy/Resteasy/blob/master/resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletResponseWrapper.java#L204
This issue is easy to reproduce by using code from [this PR](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1082/files) and running

```sh
./gradlew :instrumentation:jaxrs:jaxrs-2.0:jaxrs-2.0-resteasy-3.1:test -PtestLatestDeps=true
```

The worst thing about this is that it affects the instrumented application (because we overwrite request & response with our wrappers) - in my case, I got a 500 HTTP response instead of 1 200 one:

```
Response{protocol=http/1.1, code=500, message=Internal Server Error, url=http://localhost:56412/async?action=succeed}
```

**Comment by mateuszrzeszutek** [comment]
I've started working on this issue, PR will be ready this week for sure

**Comment by iNikem** [comment]
I see this task, #1096, the complexity of PRs trying to solve this task and I am wondering if we should rollback `CountingHttpServletResponse` and come up with some other way to set those 2 semantic convention attributes...

@trask @anuraaga

**Comment by mateuszrzeszutek** [comment]
I agree -- I've tried to fix https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1149 by creating a proxy `ServletOutputStream` class in runtime (so that we don't have to hard-code the usage of `WriteListener`) but this solution is also starting to look pretty crazy.

**Comment by mateuszrzeszutek** [comment]
I've submitted a PR that removes `CountingOutputStream`: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1167

I'll close the other two, since they both seem to inane solutions.
