### ISSUE TITLE
Metro library in currently 2.2, My application is using 2.3

### ISSUE THREAD

**Issue by srinivas-bode** [open-telemetry/opentelemetry-java-instrumentation#10986]
### Is your feature request related to a problem? Please describe.

We are using Oracle Service Bus. We are trying to explore opentelemetry java agent for collecting traces from the application. We we do so we are getting the below error.
<soapenv:Envelope xmlns:soapenv="[http://schemas.xmlsoap.org/soap/envelope/">](http://schemas.xmlsoap.org/soap/envelope/%22%3E)
soapenv:Body
soapenv:Fault
soapenv:Server
OSB-382000: Not yet supported!

<con:stack-trace xmlns:con="[http://www.bea.com/wli/sb/context">com.bea.wli.sb.service.handlerchain.HandlerException](http://www.bea.com/wli/sb/context%22%3Ecom.bea.wli.sb.service.handlerchain.HandlerException): Not yet supported!
at com.bea.wli.sb.service.disi.handlerchain.handlers.InboundDISIHandler.dispatch(InboundDISIHandler.java:144)
at com.bea.wli.sb.service.handlerchain.handlers.AbstractHandler.dispatch(AbstractHandler.java:129)
at com.bea.wli.sb.service.disi.handlerchain.handlers.InboundWssPhase1DISIHandler.dispatch(InboundWssPhase1DISIHandler.java:100)
at com.bea.wli.sb.service.handlerchain.handlers.AbstractHandler.dispatch(AbstractHandler.java:129)
at com.bea.wli.sb.service.handlerchain.handlers.InboundMessageContentHandler.dispatch(InboundMessageContentHandler.java:170)
at com.bea.wli.sb.service.handlerchain.handlers.AbstractHandler.dispatch(AbstractHandler.java:129)
at com.bea.wli.sb.service.handlerchain.handlers.CheckAccessControl.dispatch(CheckAccessControl.java:73)
at com.bea.wli.sb.service.handlerchain.handlers.AbstractHandler.dispatch(AbstractHandler.java:129)
at com.bea.wli.sb.service.handlerchain.handlers.UpdateInboundTransportStatistics.dispatch(UpdateInboundTransportStatistics.java:64)
at com.bea.wli.sb.service.handlerchain.handlers.AbstractHandler.dispatch(AbstractHandler.java:129)
at com.bea.wli.sb.service.handlerchain.handlers.AbstractHandler.dispatch(AbstractHandler.java:129)
at com.bea.wli.sb.service.handlerchain.handlers.DefaultInboundErrorHandler.dispatch(DefaultInboundErrorHandler.java:44)
at com.bea.wli.sb.service.handlerchain.DefaultInboundHandlerChain.dispatch(DefaultInboundHandlerChain.java:135)
at com.bea.wli.sb.transports.TransportDispatcherClient.dispatch(TransportDispatcherClient.java:96)
at com.bea.wli.sb.transports.TransportManagerImpl.receiveMessage(TransportManagerImpl.java:330)
at com.bea.wli.sb.transports.http.generic.RequestHelperBase.invokePipeline(RequestHelperBase.java:253)
at com.bea.wli.sb.transports.http.wls.HttpTransportServlet$RequestHelperWLS.invokePipeline(HttpTransportServlet.java:257)
at com.bea.wli.sb.transports.http.generic.RequestHelperBase$1.run(RequestHelperBase.java:220)
at com.bea.wli.sb.transports.http.generic.RequestHelperBase$1.run(RequestHelperBase.java:216)
at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:386)
at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:163)
at com.bea.wli.sb.util.security.SecurityUtils.executeAs(SecurityUtils.java:102)
at com.bea.wli.sb.transports.http.generic.RequestHelperBase.securedInvoke(RequestHelperBase.java:214)
at com.bea.wli.sb.transports.http.generic.RequestHelperBase.service(RequestHelperBase.java:142)
at com.bea.wli.sb.transports.http.wls.HttpTransportServlet.service(HttpTransportServlet.java:150)
at weblogic.servlet.FutureResponseServlet.service(FutureResponseServlet.java:24)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:295)
at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:353)
at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
at oracle.dms.servlet.DMSServletFilter.doFilter(DMSServletFilter.java:248)
at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3800)
at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3766)
at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2454)
at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2302)
at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2280)
at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1739)
at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1699)
at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)
Caused by: java.lang.UnsupportedOperationException: Not yet supported!
at com.bea.wli.sb.security.wss.wsm.CommonWsmHandler$OSBWSMHttpRequest.getServletPath(CommonWsmHandler.java:728)
at io.opentelemetry.javaagent.instrumentation.metro.MetroServerSpanNaming.updateServerSpanName(MetroServerSpanNaming.java:32)
at io.opentelemetry.javaagent.instrumentation.metro.MetroHelper.start(MetroHelper.java:27)
at io.opentelemetry.javaagent.instrumentation.metro.TracingTube.processRequest(TracingTube.java:37)
at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1136)
at com.sun.xml.ws.api.pipe.Fiber.access$100(Fiber.java:127)
at com.sun.xml.ws.api.pipe.Fiber$InterceptorHandler.execute(Fiber.java:965)
at com.sun.xml.ws.api.pipe.Fiber$InterceptorHandler.execute(Fiber.java:939)
at com.oracle.webservices.impl.disi.service.ServiceRequestTransportProcessor$Receiver$2.execute(ServiceRequestTransportProcessor.java:106)
at com.sun.xml.ws.api.pipe.Fiber$InterceptorHandler.execute(Fiber.java:969)
at com.sun.xml.ws.api.pipe.Fiber$InterceptorHandler.invoke(Fiber.java:958)
at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1054)
at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:1019)
at com.sun.xml.ws.api.pipe.Fiber.run(Fiber.java:813)
at com.sun.xml.ws.api.server.ThreadLocalContainerResolver$2$1.run(ThreadLocalContainerResolver.java:112)
at com.oracle.webservices.impl.disi.service.DISIEndpointImpl$1.execute(DISIEndpointImpl.java:141)
at com.sun.xml.ws.api.server.ThreadLocalContainerResolver$2.execute(ThreadLocalContainerResolver.java:107)
at com.sun.xml.ws.api.pipe.Engine.addRunnable(Engine.java:96)
at com.sun.xml.ws.api.pipe.Fiber.start(Fiber.java:424)
at com.sun.xml.ws.server.WSEndpointImpl.processAsync(WSEndpointImpl.java:368)
at com.sun.xml.ws.server.WSEndpointImpl.schedule(WSEndpointImpl.java:322)
at com.sun.xml.ws.metro.api.config.management.ManagedEndpoint.schedule(ManagedEndpoint.java:230)
at com.oracle.webservices.impl.disi.service.ServiceRequestTransportProcessor$Receiver.run(ServiceRequestTransportProcessor.java:92)
at com.oracle.webservices.impl.disi.service.ServiceRequestTransportProcessor.request(ServiceRequestTransportProcessor.java:53)
at com.oracle.webservices.impl.disi.service.DISIAdapter$DISIToolkit.invoke(DISIAdapter.java:315)
at com.oracle.webservices.impl.disi.service.DISIAdapter$2.request(DISIAdapter.java:142)
at com.oracle.webservices.impl.disi.service.DISIAdapter$2.request(DISIAdapter.java:105)
at com.bea.wli.sb.service.disi.handlerchain.handlers.InboundDISIHandler$1.run(InboundDISIHandler.java:113)
at java.security.AccessController.doPrivileged(Native Method)
at oracle.security.jps.util.JpsSubject.doAs(JpsSubject.java:207)
at com.bea.wli.sb.service.disi.handlerchain.handlers.InboundDISIHandler.dispatch(InboundDISIHandler.java:110)
... 53 more</con:stack-trace>

</soapenv:Fault>
</soapenv:Body>
</soapenv:Envelope>

I suppresed the usage of the library by using 
otel.instrumentation.metro.enabled=false.

Upon checking i found that OSB is using metro version 2.3 and open telemetry is using 2.2 for instrumenting resulting in the above error.

### Describe the solution you'd like

Can you please try and add support for metro library 2.3
Current version our application is using - 2.3.

### Describe alternatives you've considered

I tried to reach oracle team for support as they are the vendors for the application but they are unable to help up with this and we cannot make changes to any of the source code.

**Comment by srinivas-bode** [comment]
When i suppressed the usage of metro library, the trace propagation is not happening. Multiple traces are getting created for single transaction with out any parent id.

**Comment by laurit** [comment]
I don't think this has anything to do with metro 2.3. Version numbers in the instrumentation names indicate the minimum version of the library where the instrumentation works, the same instrumentation may work with newer versions too. Looking at the stack trace it looks like you are using an old version of the agent, though the issue should still be present in the latest version. Seems like metro is passed a wrapped `HttpServletRequest` where the wrapper does not implement all the methods but throws `UnsupportedOperationException`. I have create a PR to catch these exceptions. I'd say that this is unlikely to help if you get multiple traces, that would indicate that you somehow have multiple threads involved in servicing the same request and context isn't propagated between these threads. You will need to provide additional information.

**Comment by srinivas-bode** [comment]
Hi @laurit ,
When i suppressed the metro library instrumentation, the error stops and i am getting the traces. Thing is the trace propagation is not happening for one webservice. 

Webservice(Logic): This webservice is used to fetch some pricing data from the backend microservices. We have 2 backend microservices. The first call will go to the microservice1 and we wait for response for the response from the service, then we make a call to the second microservice2. I am getting the spans for both but the propagation is not happening. Both the spans are under individual traces.

What i am suspecting is suppressing the instrumentation of the metro library is causing the issue. Is there any work around?

Previously we were using datadog for monitoring then it worked but now we are moving to opensource grafana.

**Comment by laurit** [comment]
@srinivas-bode you have to provide more information if you expect us to help you. Ideally we'd prefer a minimal application that reproduces the issue. If context does not propagate from service1 to service2 then the first place I'd look at is where service2 is called. Firstly I'd check what the context is before service2 is called with printing out the result of `Span.current()`. If the returned span has trace and span id with all zeros then the context is already lost by this point, otherwise I'd look how exactly service2 is called. Perhaps it uses a http client that we don't have instrumentation for?
