### ISSUE TITLE
java.lang.StackOverflowError during Reactor instrumentation

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1103]
I have tried to run a moderate load test on https://github.com/spring-petclinic/spring-petclinic-microservices with Otel 0.7.0 attached. It runs nicely on light load, but with a little bit more load it gave me this error:

```
java.lang.StackOverflowError: null
	at java.base/java.util.HashMap.hash(Unknown Source)
	at java.base/java.util.HashMap.get(Unknown Source)
	at java.base/java.util.Collections$SynchronizedMap.get(Unknown Source)
	at ch.qos.logback.classic.util.LogbackMDCAdapter.get(LogbackMDCAdapter.java:151)
	at org.slf4j.MDC.get(MDC.java:203)
	at brave.context.slf4j.MDCScopeDecorator$MDCContext.getValue(MDCScopeDecorator.java:92)
	at brave.baggage.CorrelationScopeDecorator$Multiple.decorateScope(CorrelationScopeDecorator.java:194)
	at org.springframework.cloud.sleuth.log.Slf4jScopeDecorator.decorateScope(Slf4jScopeDecorator.java:95)
	at brave.propagation.CurrentTraceContext.decorateScope(CurrentTraceContext.java:108)
	at brave.propagation.CurrentTraceContext.maybeScope(CurrentTraceContext.java:141)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:75)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at io.opentelemetry.auto.instrumentation.reactor.shaded.TracingSubscriber.request(TracingSubscriber.java:98)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
```

**Comment by anuraaga** [comment]
This reminds me a bit of BSP amazingly :P Where even in async mode we can't 100% eagerly export batches because if the exporter is synchronous it can make `StackOverflowError`. Didn't dig into this issue at all but maybe some context that can help.

**Comment by devinsba** [comment]
I've done some digging into this. It looks like some odd interaction with `FluxPeekFuseable$PeekFuseableSubscriber` and the `TracingSubscriber`
