### ISSUE TITLE
opentelemetry-javaagent exporter=zipkin does not work on version 2.5.0

### ISSUE THREAD

**Issue by donniexyz** [open-telemetry/opentelemetry-java-instrumentation#11783]
### Describe the bug

When using opentelemetry-javaagent.jar version 2.5.0 with `-Dotel.traces.exporter=zipkin` the exporter seems ignored and still attempt to connect to port 4318. Setting via `OTEL_TRACES_EXPORTER` environment property also has same behavior.
opentelemetry-javaagent.jar version 1.33.4 works as expected.

### Steps to reproduce

Launch java application with javaagent: opentelemetry-javaagent v2.5.0
```
D:\apps\jdk\jdk-21\bin\java.exe -javaagent:D:/java/exec/opentelemetry-javaagent-v2.5.0.jar ^
   -Dotel.service.name=dongo ^
   -Dotel.traces.exporter=zipkin ^
   -Dotel.metrics.exporter=none ^
   -Dotel.exporter.zipkin.endpoint=http://localhost:9411/api/v2/spans ^
   -jar target\med-spring-boot-demo-0.0.1-SNAPSHOT.jar 
```

### Expected behavior

Using version 1.x WORKS: opentelemetry-javaagent v1.33.4
```
D:\apps\jdk\jdk-21\bin\java.exe -javaagent:D:/java/exec/opentelemetry-javaagent-v1.33.4.jar ^
   -Dotel.service.name=dongo ^
   -Dotel.traces.exporter=zipkin ^
   -Dotel.metrics.exporter=none ^
   -Dotel.exporter.zipkin.endpoint=http://localhost:9411/api/v2/spans ^
   -jar target\med-spring-boot-demo-0.0.1-SNAPSHOT.jar 
```

### Actual behavior

Error log:

```
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2024-07-10 13:46:37:500 +0800] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 2.5.0

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.2.6)

2024-07-10T13:46:40.256+08:00  INFO 10408 --- [med-spring-boot-demo] [           main] c.g.d.d.m.MedSpringBootDemoApplication   : Starting MedSpringBootDemoApplication using Java 21.0.1 with PID 10408 (D:\work\medium\donnie-med-spring-boot-demo\repo\med-spring-boot-demo\target\classes started by userX in D:\work\medium\donnie-med-spring-boot-demo\repo\med-spring-boot-demo)
2024-07-10T13:46:40.269+08:00  INFO 10408 --- [med-spring-boot-demo] [           main] c.g.d.d.m.MedSpringBootDemoApplication   : No active profile set, falling back to 1 default profile: "default"
2024-07-10T13:46:41.102+08:00  INFO 10408 --- [med-spring-boot-demo] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
[otel.javaagent 2024-07-10 13:46:41:157 +0800] [OkHttp http://localhost:4318/...] ERROR io.opentelemetry.exporter.internal.http.HttpExporter - Failed to export logs. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4318
java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4318
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	Suppressed: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:4318
		... 19 more
	Caused by: java.net.ConnectException: Connection refused: no further information
		at java.base/sun.nio.ch.Net.pollConnect(Native Method)
		at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
		at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:751)
		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
		... 18 more
Caused by: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	... 18 more
2024-07-10T13:46:41.195+08:00  INFO 10408 --- [med-spring-boot-demo] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 81 ms. Found 7 JPA repository interfaces.
...
```

### Javaagent or library instrumentation version

v2.5.0

### Environment

**JDK**: 21
**OS**: Windows 10

**Comment by breedx-splk** [comment]
Looks like this got figured out. 🥳  Please feel free to reopen if this is not the case.

**Comment by amitthk-avl** [comment]
Did not resolve even after adding -Dotel.logs.exporter=none .  Please advise

Below is the command I'm using:

`java -jar -javaagent:"C:\Projects\repository\WineryEquipmentScheduler\lib\opentelemetry-javaagent.jar" -Dotel.traces.exporter=zipkin -Dotel.exporter=zipkin -Dotel.logs.exporter=none -Dotel.exporter.zipkin.endpoint=http://localhost:9411/api/v2/spans -Dserver.port=9300 ./build/libs/myapp.war`

**Comment by laurit** [comment]
@amitthk-avl The exception reads `Failed to export metrics` Similarly to how the logs exporter was disabled you can add `-Dotel.metrics.exporter=none` to jvm arguments to disable the metrics exporter.

**Comment by wego-xc** [comment]
OPENJDK 17

2025-07-10 18:05:09 [otel.javaagent 2025-07-10 18:05:09:250 +0800] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 2.17.1
2025-07-10 18:05:16 OpenTelemetry Javaagent failed to start
2025-07-10 18:05:16 java.lang.ExceptionInInitializerError
2025-07-10 18:05:16     at io.opentelemetry.javaagent.shaded.instrumentation.runtimemetrics.java8.Cpu.registerObservers(Cpu.java:51)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.shaded.instrumentation.runtimemetrics.java8.internal.JmxRuntimeMetricsFactory.buildObservables(JmxRuntimeMetricsFactory.java:28)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.shaded.instrumentation.runtimemetrics.java17.RuntimeMetricsBuilder.build(RuntimeMetricsBuilder.java:97)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.shaded.instrumentation.runtimemetrics.java17.internal.RuntimeMetricsConfigUtil.configure(RuntimeMetricsConfigUtil.java:50)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.shaded.instrumentation.javaagent.runtimemetrics.java17.Java17RuntimeMetricsInstaller.afterAgent(Java17RuntimeMetricsInstaller.java:23)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.tooling.AgentInstaller.runAfterAgentListeners(AgentInstaller.java:362)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:224)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:111)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:101)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.bootstrap.AgentInitializer$2.run(AgentInitializer.java:66)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.bootstrap.AgentInitializer$2.run(AgentInitializer.java:60)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.bootstrap.AgentInitializer.execute(AgentInitializer.java:82)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:59)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:59)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:46)
2025-07-10 18:05:16     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2025-07-10 18:05:16     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2025-07-10 18:05:16     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2025-07-10 18:05:16     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2025-07-10 18:05:16     at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
2025-07-10 18:05:16     at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
2025-07-10 18:05:16 Caused by: java.lang.NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "anyController" is null
2025-07-10 18:05:16     at java.base/jdk.internal.platform.cgroupv2.CgroupV2Subsystem.getInstance(CgroupV2Subsystem.java:81)
2025-07-10 18:05:16     at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:113)
2025-07-10 18:05:16     at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:167)
2025-07-10 18:05:16     at java.base/jdk.internal.platform.SystemMetrics.instance(SystemMetrics.java:29)
2025-07-10 18:05:16     at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:58)
2025-07-10 18:05:16     at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
2025-07-10 18:05:16     at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:182)
2025-07-10 18:05:16     at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:280)
2025-07-10 18:05:16     at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:199)
2025-07-10 18:05:16     at java.management/sun.management.spi.PlatformMBeanProvider$PlatformComponent.getMBeans(PlatformMBeanProvider.java:195)
2025-07-10 18:05:16     at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:687)
2025-07-10 18:05:16     at java.management/java.lang.management.ManagementFactory.getOperatingSystemMXBean(ManagementFactory.java:389)
2025-07-10 18:05:16     at io.opentelemetry.javaagent.shaded.instrumentation.runtimemetrics.java8.internal.CpuMethods.<clinit>(CpuMethods.java:33)
2025-07-10 18:05:16     ... 21 more

**Comment by kannanjgithub** [comment]
Does not work: 
```
OTEL_EXPORTER_OTLP_PROTOCOL=grpc OTEL_LOGS_EXPORTER=none OTEL_METRICS_EXPORTER=none OTEL_EXPORTER_OTLP_TRACES_EN
DPOINT=http://localhost:7080 OTEL_SERVICE_NAME=otel-trace-service JAVA_TOOL_OPTIONS=-javaagent:/home/kannanj/workgithub/grpc-java/examples/example-opentelemetry/libs/opentelemetry-javaa
gent-1.33.0.jar build/install/example-opentelemetry/bin/opentelemetry-server

Picked up JAVA_TOOL_OPTIONS: -javaagent:/home/kannanj/workgithub/grpc-java/examples/example-opentelemetry/libs/opentelemetry-javaagent-1.33.0.jar
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2026-02-06 05:22:16:522 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.33.0
OpenTelemetry Javaagent failed to start
java.lang.IllegalStateException: Error building RuntimeMetrics
        at io.opentelemetry.javaagent.shaded.instrumentation.runtimemetrics.java17.RuntimeMetricsBuilder.buildObservables(RuntimeMetricsBuilder.java:122)
        at io.opentelemetry.javaagent.shaded.instrumentation.runtimemetrics.java17.RuntimeMetricsBuilder.build(RuntimeMetricsBuilder.java:96)
        at io.opentelemetry.javaagent.shaded.instrumentation.javaagent.runtimemetrics.java17.Java17RuntimeMetricsInstaller.afterAgent(Java17RuntimeMetricsInstaller.java:49)
        at io.opentelemetry.javaagent.tooling.AgentInstaller.runAfterAgentListeners(AgentInstaller.java:308)
        at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:200)
        at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:103)
        at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:98)
        at io.opentelemetry.javaagent.bootstrap.AgentInitializer$1.run(AgentInitializer.java:53)
        at io.opentelemetry.javaagent.bootstrap.AgentInitializer$1.run(AgentInitializer.java:47)
        at io.opentelemetry.javaagent.bootstrap.AgentInitializer.execute(AgentInitializer.java:64)
        at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:46)
        at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:57)
        at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:45)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.lang.NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "anyController" is null
        at java.base/jdk.internal.platform.cgroupv2.CgroupV2Subsystem.getInstance(CgroupV2Subsystem.java:80)
        at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:114)
        at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:177)
        at java.base/jdk.internal.platform.SystemMetrics.instance(SystemMetrics.java:29)
        at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:58)
        at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
        at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:182)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:280)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:199)
        at java.management/sun.management.spi.PlatformMBeanProvider$PlatformComponent.getMBeans(PlatformMBeanProvider.java:195)
        at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:689)
        at java.management/java.lang.management.ManagementFactory.getOperatingSystemMXBean(ManagementFactory.java:389)
        at io.opentelemetry.javaagent.shaded.instrumentation.runtimemetrics.java8.Cpu.registerObservers(Cpu.java:63)
        at io.opentelemetry.javaagent.shaded.instrumentation.runtimemetrics.java17.RuntimeMetricsBuilder.buildObservables(RuntimeMetricsBuilder.java:111)
        ... 16 more
```

**Comment by jaydeluca** [comment]
@kannanjgithub it would be better for you to open a new issue if you are having a problem. 

From your logs it looks like you are using an agent version that is several years old (1.33.0), could you try using the latest (2.24.0) and if you are still having a problem,  open a new issue and we can help get you sorted out
