### ISSUE TITLE
Spring active profiles incorrectly picked up as manifest

### ISSUE THREAD

**Issue by gabrielxfreire** [open-telemetry/opentelemetry-java-instrumentation#11795]
### Describe the bug

When running an application with spring profiles active, a `java.nio.file.NoSuchFileException` is thrown saying `Error reading manifest` and mentioning the spring profiles argument.

### Steps to reproduce

java -jar -Dspring.profiles.active=local target/app.jar

### Expected behavior

No WARN message.

### Actual behavior

```
➜  java -jar -Dspring.profiles.active=local target/app.jar    
Picked up JAVA_TOOL_OPTIONS: -Xms512m -Xmx1536m -XX:MaxRAM=1536m -XX:ReservedCodeCacheSize=64m -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=70 -XX:CompressedClassSpaceSize=64m -XX:ReservedCodeCacheSize=64m -XX:MaxMetaspaceSize=256m -XX:+UnlockExperimentalVMOptions -javaagent:opentelemetry-javaagent-2.5.0.jar
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2024-07-10 20:00:41:383 +0200] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 2.5.0
[otel.javaagent 2024-07-10 20:00:41:711 +0200] [main] WARN io.opentelemetry.instrumentation.resources.ManifestResourceProvider - Error reading manifest
java.nio.file.NoSuchFileException: -Dspring.profiles.active=local
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1853)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1445)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:724)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:345)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:316)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:296)
        at io.opentelemetry.instrumentation.resources.ManifestResourceProvider.readManifest(ManifestResourceProvider.java:73)
        at java.base/java.util.Optional.flatMap(Optional.java:289)
        at io.opentelemetry.instrumentation.resources.ManifestResourceProvider$1.readData(ManifestResourceProvider.java:42)
        at io.opentelemetry.instrumentation.resources.AttributeResourceProvider.createResource(AttributeResourceProvider.java:70)
        at io.opentelemetry.sdk.autoconfigure.ResourceConfiguration.configureResource(ResourceConfiguration.java:106)
        at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:439)
        at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installOpenTelemetrySdk(OpenTelemetryInstaller.java:29)
        at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:122)
        at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:102)
        at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:99)
        at io.opentelemetry.javaagent.bootstrap.AgentInitializer$1.run(AgentInitializer.java:53)
        at io.opentelemetry.javaagent.bootstrap.AgentInitializer$1.run(AgentInitializer.java:47)
        at io.opentelemetry.javaagent.bootstrap.AgentInitializer.execute(AgentInitializer.java:68)
        at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:46)
        at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:57)
        at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:45)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)

```

### Javaagent or library instrumentation version

v2.5.0

### Environment

**JDK**: openjdk 21.0.1 2023-10-17 (Mac) and openjdk 21.0.3 2024-04-16 LTS (ubuntu)
**OS**: Sonoma 14.5 (Mac) and Ubuntu 22.04.4 LTS

**Comment by xiangtianyu** [comment]
Maybe you should put your property before -jar like this `java -Dspring.profiles.active=local -jar target/app.jar`

**Comment by gabrielxfreire** [comment]
> Maybe you should put your property before -jar like this `java -Dspring.profiles.active=local -jar target/app.jar`

This works.

**Comment by serkan-ozal** [comment]
Right way of passing system properties is placing them before the `-jar` option. So, it seems that this is not a bug, but misuse of the JVM arguments.

**Comment by gabrielxfreire** [comment]
I'm closing this issue since using passing the arguments in the recommended order works and resolves it.
