### ISSUE TITLE
OpenTelemetryHandlerMappingFilter throws exceptions for invalid request path 

### ISSUE THREAD

**Issue by XuyuFu** [open-telemetry/opentelemetry-java-instrumentation#12214]
### Describe the bug

Our application is auto-instrumented by otel java agent. 
When a request comes in with a invalid request path, we notice exceptions in our code as

`java.lang.IllegalStateException: java.lang.IllegalArgumentException: Invalid contextPath '/api/v1': must match to full path segments for requestPath: '/api/v1;v1%2fusers%2flogin/events/subscriptions/validation/condition/T(java.lang.Runtime).getRuntime().exec(new%20java.lang.String(T(java.util.Base64).getDecoder().decode(%22bnNsb29rdXAge3tpbnRlcmFjdHNoLXVybH19%22)))' at org.springframework.web.servlet.v3_1.OpenTelemetryHandlerMappingFilter.parseAndCache(OpenTelemetryHandlerMappingFilter.java:186) at org.springframework.web.servlet.v3_1.OpenTelemetryHandlerMappingFilter.lambda$new$0(OpenTelemetryHandlerMappingFilter.java:46) at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.http.HttpServerRoute$OneArgAdapter.get(HttpServerRoute.java:164) at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.http.HttpServerRoute$OneArgAdapter.get(HttpServerRoute.java:151) at
`
which is from otel java instrument [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/release/v1.33.x/instrumentation/spring/spring-webmvc/spring-webmvc-3.1/javaagent/src/main/java/org/springframework/web/servlet/v3_1/OpenTelemetryHandlerMappingFilter.java#L185)

This exception is not captured by our application and lead to 500 response returned to the request.

I don't expect an Instrumentation library to cause exceptions to be thrown to abort normal app behavior.

### Steps to reproduce

1. Auto instrument a jetty based http server
2. Send request with invalid request path to the server

### Expected behavior

Path validation related exception such as IllegalArgumentException should be captured by [parseAndCache()](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/release/v1.33.x/instrumentation/spring/spring-webmvc/spring-webmvc-3.1/javaagent/src/main/java/org/springframework/web/servlet/v3_1/OpenTelemetryHandlerMappingFilter.java#L179C23-L179C36)

In a nutshell, Instrumentation library handles such exceptions silently. 

### Actual behavior

When request with invalid path received, [OpenTelemetryHandlerMappingFilter](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/release/v1.33.x/instrumentation/spring/spring-webmvc/spring-webmvc-3.1/javaagent/src/main/java/org/springframework/web/servlet/v3_1/OpenTelemetryHandlerMappingFilter.java#L179C23-L179C36) use Java Reflection to look up and call a method named `parseAndCache` from the class `ServletRequestPathUtils` in Spring Framework and didn't capture the exceptions could be thrown by the method which exerts impact on app behavior which is auto instrumented by otel java agent

### Javaagent or library instrumentation version

v1.33.1

### Environment

**JDK**:
**OS**:

**Comment by XuyuFu** [comment]
@laurit perfect, your PR seems promising.
