### ISSUE TITLE
JDBCConnectionUrlParser parse sqlserver IPv6 addresses error

### ISSUE THREAD

**Issue by dengliming** [open-telemetry/opentelemetry-java-instrumentation#1223]
20:18:29.120 [Test worker] DEBUG io.opentelemetry.instrumentation.auto.api.jdbc.JDBCConnectionUrlParser - Error parsing URL
```
java.lang.NumberFormatException: For input string: "8311:eeee:f70f:0:5eae:10.203.31.9\instance1"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at io.opentelemetry.instrumentation.auto.api.jdbc.JDBCConnectionUrlParser$3.doParse(JDBCConnectionUrlParser.java:175)
	at io.opentelemetry.instrumentation.auto.api.jdbc.JDBCConnectionUrlParser$9.doParse(JDBCConnectionUrlParser.java:382)
	at io.opentelemetry.instrumentation.auto.api.jdbc.JDBCConnectionUrlParser.parse(JDBCConnectionUrlParser.java:802)
	at io.opentelemetry.instrumentation.auto.api.jdbc.JDBCConnectionUrlParser$parse.callStatic(Unknown Source)
	at JDBCConnectionUrlParserTest.$spock_feature_0_1(JDBCConnectionUrlParserTest.groovy:56)
	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:200)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:113)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
	at org.spockframework.runtime.BaseSpecRunner.runFeatureMethod(BaseSpecRunner.java:408)
	at org.spockframework.runtime.BaseSpecRunner.doRunIteration(BaseSpecRunner.java:322)
	at org.spockframework.runtime.BaseSpecRunner$6.invoke(BaseSpecRunner.java:306)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
	at org.spockframework.runtime.BaseSpecRunner.runIteration(BaseSpecRunner.java:285)
	at org.spockframework.runtime.BaseSpecRunner.initializeAndRunIteration(BaseSpecRunner.java:275)
	at org.spockframework.runtime.ParameterizedSpecRunner.runIterations(ParameterizedSpecRunner.java:139)
	at org.spockframework.runtime.ParameterizedSpecRunner.runParameterizedFeature(ParameterizedSpecRunner.java:41)
```

reproduce url:
`jdbc:sqlserver://;serverName=3ffe:8311:eeee:f70f:0:5eae:10.203.31.9\instance1;integratedSecurity=true;`
more detail [https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15)

**Comment by imavroukakis** [comment]
I can take a look at this.

**Comment by iNikem** [comment]
@imavroukakis thank you for your help :) Assigned this issue to you.
