### ISSUE TITLE
Opentelemetry javaagent with rabbit mq + stomp gets error when disconnect

### ISSUE THREAD

**Issue by ingyeoking13** [open-telemetry/opentelemetry-java-instrumentation#12498]
### Describe the bug

Opentelemetry Javaagent + rabbit mq stomps get error with following message

```
java.lang.IllegalStateException: No header accessor (not using the SimpMessagingTemplate?):
```

It's error from `StompBrokerRelayMessageHandler`class `handleMessageInternal` method.
![image](https://github.com/user-attachments/assets/d85269d7-8fde-4be4-b664-2c812440e17b)

When Client Application disconnect from websocket that is connected, server got extra message with Headers (none `MutableMessageHeaders`). message should type of MutableMessageHeaders and accessor should be `StompHeaderAccessor`.

```
//message-instance-value maybe

GenericMessage [payload=byte[0], headers={simpMessageType=DISCONNECT, stompCommand=DISCONNECT, simpSessionAttributes={}, traceparent=00-a6f9f07152865fa16ea6076a9dd077c8-8605dc783c10878e-01, id=cef0afc3-9b43-4ae4-0d6e-e09ba0f564e4, simpUser=UsernamePasswordAuthenticationToken [Principal=0076bff3a7bf4082acfb3e524ee15923, Credentials=[PROTECTED], Authenticated=false, Details=null, Granted Authorities=[]], simpSessionId=gb4o2q3f, timestamp=1729606705285}]
```

### Steps to reproduce

When Client Application disconnect from websocket that is connected.

### Expected behavior

disconnect websocket gracefully.

### Actual behavior

```
g.springframework.messaging.MessageDeliveryException: Failed to handle GenericMessage [payload=byte[0], headers={simpMessageType=DISCONNECT, stompCommand=DISCONNECT, simpSessionAttributes={org.springframework.messaging.simp.SimpAttributes.COMPLETED=true}, traceparent=00-9b8d341269731c0a8c68a9f1f1e1ff7a-0cf3999f0c7f635a-01, id=74640079-6032-4eb9-cf12-f91d1b511b8d, simpUser=UsernamePasswordAuthenticationToken [Principal=0076bff3a7bf4082acfb3e524ee15923, Credentials=[PROTECTED], Authenticated=false, Details=null, Granted Authorities=[]], simpSessionId=0m4tk0fn, timestamp=1729610042917}] to org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask@28733565 in StompBrokerRelay[ReactorNettyTcpClient[reactor.netty.tcp.TcpClientConnect@6c9a31c1]]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:161)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.opentelemetry.exporter.sender.okhttp.internal.RetryInterceptor.intercept(RetryInterceptor.java:91)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: No header accessor (not using the SimpMessagingTemplate?): GenericMessage [payload=byte[0], headers={simpMessageType=DISCONNECT, stompCommand=DISCONNECT, simpSessionAttributes={org.springframework.messaging.simp.SimpAttributes.COMPLETED=true}, traceparent=00-9b8d341269731c0a8c68a9f1f1e1ff7a-0cf3999f0c7f635a-01, id=74640079-6032-4eb9-cf12-f91d1b511b8d, simpUser=UsernamePasswordAuthenticationToken [Principal=0076bff3a7bf4082acfb3e524ee15923, Credentials=[PROTECTED], Authenticated=false, Details=null, Granted Authorities=[]], simpSessionId=0m4tk0fn, timestamp=1729610042917}]
	at org.springframework.messaging.simp.stomp.StompBrokerRelayMessageHandler.handleMessageInternal(StompBrokerRelayMessageHandler.java:542)
Caused by: java.lang.IllegalStateException: No header accessor (not using the SimpMessagingTemplate?): GenericMessage [payload=byte[0], headers={simpMessageType=DISCONNECT, stompCommand=DISCONNECT, simpSessionAttributes={org.springframework.messaging.simp.SimpAttributes.COMPLETED=true}, traceparent=00-9b8d341269731c0a8c68a9f1f1e1ff7a-0cf3999f0c7f635a-01, id=74640079-6032-4eb9-cf12-f91d1b511b8d, simpUser=UsernamePasswordAuthenticationToken [Principal=0076bff3a7bf4082acfb3e524ee15923, Credentials=[PROTECTED], Authenticated=false, Details=null, Granted Authorities=[]], simpSessionId=0m4tk0fn, timestamp=1729610042917}]

	at org.springframework.messaging.simp.broker.AbstractBrokerMessageHandler.handleMessage(AbstractBrokerMessageHandler.java:297)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:152)
	... 7 common frames omitted
```

### Javaagent or library instrumentation version

2.9.0

### Environment

**JDK**: 17
**OS**: mac os(intel), linux ubuntu

**Comment by ingyeoking13** [comment]
I modify my code WebSocketConfigure. 
but I don't know why none StompHeaderMessage message comes in.

```
public class WebSocketConfig implements WebSocketMessageBrokerConfigurer {
...
  @Override
  public void configureClientInboundChannel(ChannelRegistration registration) {
        registration.interceptors(new ChannelInterceptor() {
            @Override
            public Message<?> preSend(Message<?> message, MessageChannel channel) {
                StompHeaderAccessor accessor =
                        MessageHeaderAccessor.getAccessor(message, StompHeaderAccessor.class);
                if (accessor == null) {  // to fix
                     StompHeaderAccessor newAccessor = StompHeaderAccessor.wrap(message);
                    newAccessor.setLeaveMutable(true);
                    return MessageBuilder.createMessage(message.getPayload(), newAccessor.getMessageHeaders());
              }

```

**Comment by laurit** [comment]
Based on the provided information it is not possible to tell why this happens. Please provide a minimal application that reproduces the issue along with any necessary instructions if you wish someone to take a look at this.

**Comment by ingyeoking13** [comment]
I'm trying to reproduce error with new project but I found that this is not only problem with stomp + rabbitmq + socket disconnect. 
I'm still adding adhoc to mimic my origin product to new project to reproduce error

**Comment by olabodeIdowu** [comment]
@ingyeoking13 when using the OpenTelemetry Java agent with RabbitMQ and STOMP, encountering errors during disconnection could stem from a few common issues. Here are some potential solutions and approaches to troubleshoot:

1. *Update Dependencies*: Ensure that you are using the latest version of the OpenTelemetry Java agent and RabbitMQ client libraries. Sometimes, bugs are fixed in newer versions.

2. *Graceful Shutdown*: Ensure that your application is properly handling the disconnection process. Implementing a graceful shutdown procedure can help in avoiding abrupt terminations that might lead to errors.

3. *Error Handling*: Enhance your error handling to capture and log detailed information about the error. This might provide insights into what specifically is going wrong during the disconnect process.

4. *Connection Settings*: Review your RabbitMQ connection settings and STOMP configuration to ensure they are correct. Misconfigurations can lead to unexpected behaviors.

5. *Telemetry Context Management*: Ensure that you are correctly managing the telemetry context across the lifecycle of your application, especially during connection and disconnection events.

6. *Inspect OpenTelemetry Configuration*: Review your OpenTelemetry configuration settings. Incorrect settings may lead to issues when sending traces or metrics during disconnection.

7. *Network Issues*: Check if there are any network-related issues that could be causing the disconnection errors. Ensure that the RabbitMQ server is reachable and that there are no firewall rules blocking the connection.

8. *Debugging and Logs*: Enable detailed logging for both OpenTelemetry and RabbitMQ. This will help you trace the flow of execution and identify where the error occurs.

9. *Consult Documentation*: Review the official documentation for OpenTelemetry and RabbitMQ for any specific notes on integration and known issues.

If these solutions don't resolve your issue, consider providing the specific error message you're encountering, as that might help in diagnosing the problem further.
