### ISSUE TITLE
Muzzle not working for opentelemetry-api-beta

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1274]
I got the following exception when the app code created a tracer. The agent is using OTel API 0.9.0-SNAPSHOT and the app   0.8.0.

The app didn't crash only the exception was logged. Did the Muzzle prevent the crash? There is no Muzzle mentioned in the logs. So either muzzle was not configured correctly or it could print more understandable output. 

```java
    Tracer foo = OpenTelemetry.getTracer("foo");
    foo.spanBuilder("foo").startSpan().end();
```

```bash
[opentelemetry.auto.trace 2020-09-28 12:04:29:526 +0200] [http-nio-8080-exec-1] ERROR io.opentelemetry.javaagent.tooling.HelperInjector - Error preparing helpers while processing class io.grpc.Context for GrpcContextInstrumentation. Failed to inject helper classes into instance org.springframework.boot.loader.LaunchedURLClassLoader@f446158
java.lang.IllegalStateException: Error invoking (accessor)::defineClass
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$UsingUnsafeInjection.defineClass(ClassInjector.java:922)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:234)
	at io.opentelemetry.javaagent.tooling.HelperInjector.injectClassLoader(HelperInjector.java:208)
	at io.opentelemetry.javaagent.tooling.HelperInjector.transform(HelperInjector.java:143)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10325)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10263)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10029)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10722)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10660)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10219)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.opentelemetry.trace.TracingContextUtils.<clinit>(TracingContextUtils.java:33)
	at io.opentelemetry.trace.DefaultTracer$NoopSpanBuilder.startSpan(DefaultTracer.java:75)
	at com.example.demo.HelloController.index(HelloController.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.opentelemetry.instrumentation.auto.springwebmvc.HandlerMappingResourceNameFilter.doFilterInternal(HandlerMappingResourceNameFilter.java:57)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: io/opentelemetry/common/AttributeConsumer
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.lang.ClassLoader$ByteBuddyAccessor$55EmPuCL.defineClass(Unknown Source)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$UsingUnsafeInjection.defineClass(ClassInjector.java:918)
	... 81 more
Caused by: java.lang.ClassNotFoundException: io.opentelemetry.common.AttributeConsumer
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 88 more
```

**Comment by trask** [comment]
The problem here is that all the OTel API instrumentation share a super class with a single definition of `helperClassNames`, but they each get their own muzzle matcher generated.

Ideally they would all share a muzzle matcher, because we want all or none of the OTel API instrumentation to be muzzled.

If they all shared a (unioned) muzzle matcher, then `GrpcContextInstrumentation` would have been muzzled (since the other OTel API instrumentation would have been muzzled since no `AttributeConsumer`).

**Comment by pavolloffay** [comment]
@trask any hints how to solve this?

**Comment by mateuszrzeszutek** [comment]
I've thought about it for a while and I have an idea how this can be solved properly:

We could split the `Instrumenter.Default` class in two:

```java
interface TypeInstrumentation {
  ElementMatcher<? super TypeDescription> typeMatcher();
  Map<? extends ElementMatcher<? super MethodDescription>, String> transformers();
}

class Default {
  AgentBuilder instrument(AgentBuilder parentAgentBuilder) {
    if (!enabled) {
        return parentAgentBuilder;
    }
    AgentBuilder.Identified.Extendable agentBuilder;
    MuzzleMatcher muzzleMatcher = ...
    HelperInjector helperInjector = ...
    for (TypeInstrumentation instrumentation : instrumentations()) {
      agentBuilder = parentAgentBuilder
          .type(instrumentation.typeMatcher(), classLoaderMatcher())
          .and(NOT_DECORATOR_MATCHER)
          .and(muzzleMatcher)
          .transform(AgentTransformers.defaultTransformers())
          .transform(helperInjector);
      agentBuilder = contextProvider.instrumentationTransformer(agentBuilder);
      agentBuilder = applyInstrumentationTransformers(instrumentation, agentBuilder);
      agentBuilder = contextProvider.additionalInstrumentation(agentBuilder);
    }
    return agentBuilder;
  }

  List<TypeInstrumentation> instrumentations();
  String[] helperClassNames();
  String[] helperResourceNames();
  ElementMatcher<ClassLoader> classLoaderMatcher();
  Map<String, String> contextStore();
  boolean defaultEnabled();
}
```

The new `TypeInstrumentation` interface would contain methods that differ per instrumented type (I think only those two), the `Instrumenter` has everything that is shared for the whole library instrumentation: like instrumentation name, muzzle reference matcher, helper classes to inject, context store (which is pretty much only used to communicate between advices) and the `classLoaderMatcher()`.
Because `ReferenceMatcher` will always get the same input for every `TypeInstrumentation` (same references, same classloader) after the first check the result will get cached and either all type instrumentations get applied or none. Same for `HelperInjector`: it already checks that same types won't be injected twice.

In the case of OTel API instrumentation `AbstractInstrumentation` would become a non-abstract `Instrumenter`, while `BaggageUtilsInstrumentation`, `DefaultSpanInstrumentation` and so on would be `TypeInstrumentation`s.

**Comment by trask** [comment]
I like this 👍

We may need to allow `TypeInstrumentation` to "override" `defaultEnabled()` and `instrumentationName` somehow in order to handle a few cases, e.g. `DataSourceInstrumentation`.

Might be nice for `instrumentations()` to return `List<Class<? extends TypeInstrumentation>>` instead of `List<TypeInstrumentation>`, but not sure about that.

Hm, maybe `JdbcInstrumenter.instrumentations()` implementation could check config and not return `DataSourceInstrumentation` if it's not enabled to deal with corder case like above(?)

One last thought, for naming, maybe `Instrumenter` --> `InstrumentationModule`.

I think this will unlock some nice optimizations in the future by sharing these matchers (e.g. caching and re-using matcher results).

**Comment by mateuszrzeszutek** [comment]
> One last thought, for naming, maybe Instrumenter --> InstrumentationModule.

👍 

> We may need to allow TypeInstrumentation to "override" defaultEnabled() and instrumentationName somehow in order to handle a few cases, e.g. DataSourceInstrumentation.
> Hm, maybe JdbcInstrumenter.instrumentations() implementation could check config and not return DataSourceInstrumentation if it's not enabled to deal with corder case like above(?)

I think that in that case we might just have two separate modules: `jdbc` and `jdbc-datasource`.

> I think this will unlock some nice optimizations in the future by sharing these matchers (e.g. caching and re-using matcher results).

We can do some of them right away - e.g. `ClassLoaderHasClassesNamedMatcher` already caches results per CL, as long as it's the same instance for all `TypeInstrumentation`s it'll only be evaluated once (per classloader).

**Comment by trask** [comment]
> I think that in that case we might just have two separate modules: `jdbc` and `jdbc-datasource`.

I'm torn on this. It feels more like an optional feature of a given instrumentation, as opposed to a separate instrumentation. At the same time, I'm interested to keep the number of optional features down, and forcing this kind of split could help prevent these optional features from sneaking in too easily 😄.

So, yeah, 👍 on two separate modules: `jdbc` and `jdbc-datasource`.
