### ISSUE TITLE
RabbitMqTest failed to start testcontainer

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1330]
Getting this on my Mac when running tests locally, haven't been able to debug it yet.

```
> Task :instrumentation:rabbitmq-2.7:test

RabbitMQTest > initializationError FAILED
    java.lang.IllegalStateException: Can not connect to Ryuk
        at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:150)
        at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:131)
        at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:175)
        at RabbitMQTest.setupSpec(RabbitMQTest.groovy:63)
16:23:25.534 [opentelemetry-exec-shutdown-hook] WARN io.opentelemetry.javaagent.tooling.CommonTaskExecutor - Periodic task scheduler is shutdown. Will not run: cleaner for com.blogspot.mydailyjava.weaklockfree.WeakConcurrentMap@2782da4e
16:23:25.535 [opentelemetry-exec-shutdown-hook] DEBUG io.opentelemetry.instrumentation.auto.javaconcurrent.FutureInstrumentation - Skipping future instrumentation for io.opentelemetry.javaagent.tooling.CommonTaskExecutor$UnscheduledFuture
16:23:25.538 [opentelemetry-exec-shutdown-hook] DEBUG io.opentelemetry.javaagent.tooling.AgentInstaller$TransformLoggingListener - Transformed io.opentelemetry.javaagent.tooling.CommonTaskExecutor$UnscheduledFuture -- jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc

1 test completed, 1 failed
```

**Comment by iNikem** [comment]
This is due to https://github.com/testcontainers/testcontainers-java/issues/3166. Will submit PR shortly
