### ISSUE TITLE
Netty Exceptions / Broken traces while instrumenting Kotlin/Ktor application with agent

### ISSUE THREAD

**Issue by csilcock** [open-telemetry/opentelemetry-java-instrumentation#1456]
I've been evaluating opentracing/opentelemetry options for Kotlin/Ktor applications. My end goal is to instrument services to publish OpenTelemetry traces to Lightstep.

I noticed that there is support for [Kotlin Coroutines](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/kotlin-coroutines/src/main/java/io/opentelemetry/javaagent/instrumentation/kotlincoroutines/KotlinProbeInstrumentation.java) and was hopeful that the Java agent would work in this case.

Using https://github.com/lightstep/otel-launcher-java as a configuration layer, I'm able to run the agent and publish spans successfully to Lighstep, but observe the following error in my application on each inbound request to Ktor. The Context of the spans appears to be lost (no parent spans), and so traces are completely broken up. I've tested with versions 0.8.X and 0.9.0.

```
ERROR io.opentelemetry.javaagent.shaded.io.grpc.ThreadLocalContextStorage - Context was not attached when detaching
java.lang.Throwable
        at io.opentelemetry.javaagent.shaded.io.grpc.ThreadLocalContextStorage.detach(ThreadLocalContextStorage.java:48)
        at io.opentelemetry.javaagent.shaded.io.grpc.Context.detach(Context.java:463)
        at io.opentelemetry.javaagent.shaded.io.opentelemetry.context.ContextUtils$ContextInScope.close(ContextUtils.java:45)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:66)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

Also noted a similar stack trace from some time ago affecting Grizzly Instrumentation https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/845, but unsure if there's any relation at all.

**Comment by trask** [comment]
hey @csilcock! any chance you can provide a repro that we can use to troubleshoot this behavior?

**Comment by brunojcm** [comment]
Was this ever fixed?

**Comment by trask** [comment]
hey @brunojcm, there have been several fixes related to netty and context propagation since then, but without a repro or more details I'm not sure if this particular issue was fixed. if you are running into something similar, can you open a new issue?

**Comment by brunojcm** [comment]
I'm not, I was just asking because I'm using ktor now and I was trying to decide between Jetty and Netty as my engine.

I ended up testing both (superficially) and they worked ok, so I'd say it's working fine now. Good work, guys!
