### ISSUE TITLE
Java Agent Behaviour

### ISSUE THREAD

**Issue by rodolfo-picoreti** [open-telemetry/opentelemetry-java-instrumentation#1485]
Hi everyone, thanks for this awesome project :)

I am trying to instrument my java application with the provided java agent.
I passed the following parameters to the application:

```
-javaagent:/agents/opentelemetry-javaagent-all.jar
-Dotel.exporter=jaeger
-Dotel.exporter.jaeger.endpoint=jaeger-collector.monitoring:14250
-Dotel.exporter.jaeger.service.name=ppw-api-server
```

Sometimes the application crashes with the following error:
```
[opentelemetry.auto.trace 2020-10-26 12:57:21:666 -0300] [grpc-default-executor-1] WARN io.opentelemetry.exporters.jaeger.JaegerGrpcSpanExporter - Failed to export spans
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 809414503ns. [buffered_nanos=811149828, waiting_for_connection]
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

That said, I have two question:
- How can I increase the deadline to export spans? I've tried ```      -Dotel.bsp.export.timeout=120000``` but i did not work.
- Is the application crashing the right behaviour here? I would not like all my instrumented applications to crash if someday my Jaeger deployment fails. IMHO the agent should have emitted a log message saying it was unable to export the spans and eventually drop them (to avoid unbounded memory growth).

Thanks in advance

**Comment by trask** [comment]
hi @rodolfo-picoreti! does the discussion in #1381 help?

**Comment by anuraaga** [comment]
@trask I tend to notice first few exports throw that error, presumably because of some JVM warmup or similar? But the spans still usually (not always) show up in the backend. I think this might be different than #1381 which is about mismatched collector IIUC.

**Comment by rodolfo-picoreti** [comment]
Hey @trask not sure if it is similar. I am using jaeger in my case, so the suggestion would be to set ```OTEL_EXPORTER=jaeger_span``` ? 

As @anuraaga pointed out, it usually happen during jvm initialization. And it concerns me a lot that if Jaeger is down my application won't come up.

**Comment by trask** [comment]
@rodolfo-picoreti sorry I think my suggestion was not relevant to your issue.

I'm surprised that this error is causing your application to fail to start (and not just causing the monitoring to fail to start). Can you confirm that's the behavior you are seeing?

Thanks!

**Comment by rodolfo-picoreti** [comment]
Hey @trask sorry for that, I was mistakenly thinking that the application was crashing due to the agent. The startup time of the application became higher due to the agent and the liveness probe was killing it. My bad.

**Comment by trask** [comment]
I noticed that we are defaulting the grpc deadline to 1 second, when I think we should be defaulting it to 10 seconds, which could explain this issue, see https://github.com/open-telemetry/opentelemetry-java/issues/2064

**Comment by pvyaka01** [comment]
Thanks, I see the same behavior
[opentelemetry.auto.trace 2020-11-23 01:55:02:922 +0000] [grpc-default-executor-0] WARN io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporter - Failed to export spans
**io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 0.999452088s. [remote_addr=xxxxx]**

**Comment by trask** [comment]
Hi @pvyaka01, the issue linked above hasn't been fixed yet, which is why you are still timing out at 1 second

**Comment by trask** [comment]
Closed by https://github.com/open-telemetry/opentelemetry-java/issues/2064
