### ISSUE TITLE
JDBC instrumentation does not work

### ISSUE THREAD

**Issue by hasanfd** [open-telemetry/opentelemetry-java-instrumentation#1584]
**Describe the bug**
When I tried an JDBC hello world example in a Spring boot application, I could not find the span that contains query information. After opening the debug logs of the agent I saw this error message:

```
java.lang.NoClassDefFoundError: io/opentelemetry/javaagent/instrumentation/jdbc/JDBCConnectionUrlParser
	at io.opentelemetry.javaagent.instrumentation.jdbc.JdbcTracer.extractDbInfo(JdbcTracer.java:106)
	at io.opentelemetry.javaagent.instrumentation.jdbc.JdbcTracer.startSpan(JdbcTracer.java:77)
	at io.opentelemetry.javaagent.instrumentation.jdbc.JdbcTracer.startSpan(JdbcTracer.java:68)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at com.example.demo.MyRest.jdbc(MyRest.java:31)
```

**Steps to reproduce**
I saw the error in a JDBC select example written in a Spring boot hello world application. The database is Postgres.

**What did you expect to see?**
A span that contains query information.

**What did you see instead?**
Span does not exist. NoClassDefFoundError thrown instead.

**What version are you using?**
Latest snapshot **opentelemetry-javaagent-0.10.0-20201106.042347-58-all**
v0.9.0 works as expected.

**Environment**
OS: Windows 10 
Runtime: "Oracle JDK 11.0.9"

**Comment by trask** [comment]
@hasanfd thanks for reporting this! it should be fixed now

**Comment by hasanfd** [comment]
works as excepted, thanks @trask!
