### ISSUE TITLE
Vendor specific distribution do not initialise SystemMetrics 

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-java-instrumentation#1637]
I added oshi.jar to vendor specific distribution.
1. SystemMetrics is not initialised because oshi.jar is not loaded to system classloader

2. I tried to call `oshi.SystemInfo.getCurrentPlatformEnum()` in system classloader:
```
public static void premain(final String agentArgs, final Instrumentation inst) {
    OpenTelemetryAgent.premain(agentArgs, inst);

    try {
      Class<?> oshiSystemInfoClass = ClassLoader.getSystemClassLoader().loadClass("oshi.SystemInfo");
      Method getCurrentPlatformEnumMethod = oshiSystemInfoClass.getMethod("getCurrentPlatformEnum");
      getCurrentPlatformEnumMethod.invoke(null);
    } catch (Throwable ex) {
      ex.printStackTrace();
    }
  }
```
Nothing happend.

3. I changed order:
```
public static void premain(final String agentArgs, final Instrumentation inst) {
    try {
      Class<?> oshiSystemInfoClass = ClassLoader.getSystemClassLoader().loadClass("oshi.SystemInfo");
      Method getCurrentPlatformEnumMethod = oshiSystemInfoClass.getMethod("getCurrentPlatformEnum");
      getCurrentPlatformEnumMethod.invoke(null);
    } catch (Throwable ex) {
      ex.printStackTrace();
    }

    OpenTelemetryAgent.premain(agentArgs, inst);
  }
```
But got error:
```
java.lang.IllegalAccessError: tried to access class oshi.SystemInfo$1 from class oshi.SystemInfo
        at oshi.SystemInfo.createHardware(SystemInfo.java:134)
        at oshi.util.Memoizer$1.get(Memoizer.java:87)
        at oshi.SystemInfo.getHardware(SystemInfo.java:130)
        at io.opentelemetry.javaagent.shaded.instrumentation.oshi.SystemMetrics.registerObserversInt(SystemMetrics.java:40)
        at io.opentelemetry.javaagent.shaded.instrumentation.oshi.SystemMetrics.registerObservers(SystemMetrics.java:28)
        at oshi.SystemInfo.getCurrentPlatformEnum(SystemInfo.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:77)
        at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
```

Which order is expected to work 2 or 3? Is there other way?
It's important to have oshi.jar in the vendor distribution and don't ask user to put oshi.jar in classpath.

**Comment by malafeev** [comment]
closing the issue because oshi-library jar (opentelemetry-oshi artifact) can be used to init system metrics.
