### ISSUE TITLE
Span.current() not working in custom servlet advice

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1661]
**Describe the bug**

`Span.current()` throws the following ByteBuddy error in custom servlet advice. This advice runs after the core one and it attaches additional data to span:

```java
java.lang.VerifyError: (class: javax/servlet/http/HttpServlet, method: service signature: (Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V) Illegal type in constant pool
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:610)
	at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:760)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:435)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:336)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:524)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:936)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce**
Use here `Span.current()` https://github.com/hypertrace/javaagent/pull/120/files#diff-d3f9bb095b87c95e993061da5887be040204b20d1fde34344b976046dcdb7e07R66

and run unit test in that module.

**What did you expect to see?**

`Span.current()` return current span.

**What did you see instead?**
Error see above ^^^.

**What version are you using?**
v0.10.0

**Environment**
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
macos

**Comment by trask** [comment]
Yeah this is a recent problem because Span.current() is a default interface method, which can't be called from pre-Java 8 bytecode (and advice is inlined into the instrumented class which may be pre-Java 8).

Check out https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/javaagent-api/src/main/java/io/opentelemetry/javaagent/instrumentation/api/Java8BytecodeBridge.java#L14-L21

**Comment by pavolloffay** [comment]
Is the only workaround to keep the advice methods minimal and rather use a helper class?

**Comment by trask** [comment]
you can use `Java8BytecodeBridge` from your instrumentation, it's part of the `javaagent-api`

**Comment by pavolloffay** [comment]
The `Java8BytecodeBridge` worked well is there anything we can do in this issue? Perhaps add some docs?
