### ISSUE TITLE
Can't run `byteBuddyJava` task twice without stopping Gradle daemon

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1674]
```
 ./gradlew :instrumentation:jetty-8.0:bytebuddyjava --no-build-cache --stacktrace --rerun-tasks
 ./gradlew :instrumentation:jetty-8.0:bytebuddyjava --no-build-cache --stacktrace --rerun-tasks
```

fails with

```
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Error reading class io.opentelemetry.javaagent.instrumentation.servlet.v3_0.TagSettingAsyncListener
        at io.opentelemetry.javaagent.tooling.muzzle.collector.MuzzleCodeGenerator$GenerateMuzzleReferenceMatcherMethodAndField.visitEnd(MuzzleCodeGenerator.java:458)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor.onVisitEnd(TypeWriter.java:5140)
        at net.bytebuddy.utility.visitor.MetadataAwareClassVisitor.visitEnd(MetadataAwareClassVisitor.java:370)
        at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:715)
        at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:394)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3892)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
        at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:252)
        at net.bytebuddy.build.Plugin$Engine$Default$Preprocessor$Resolved.call(Plugin.java:4498)
        at net.bytebuddy.build.Plugin$Engine$Default$Preprocessor$Resolved.call(Plugin.java:4455)
        at net.bytebuddy.build.Plugin$Engine$Dispatcher$ForSerialTransformation.accept(Plugin.java:3538)
        at net.bytebuddy.build.Plugin$Engine$Default.apply(Plugin.java:4302)
        at net.bytebuddy.build.gradle.AbstractByteBuddyTask.doApply(AbstractByteBuddyTask.java:331)
        ... 99 more
Caused by: java.lang.IllegalStateException: Error reading class io.opentelemetry.javaagent.instrumentation.servlet.v3_0.TagSettingAsyncListener
        at io.opentelemetry.javaagent.tooling.muzzle.collector.ReferenceCollector.collectReferencesFrom(ReferenceCollector.java:101)
        at io.opentelemetry.javaagent.tooling.muzzle.collector.MuzzleCodeGenerator$GenerateMuzzleReferenceMatcherMethodAndField.generateReferences(MuzzleCodeGenerator.java:144)
        at io.opentelemetry.javaagent.tooling.muzzle.collector.MuzzleCodeGenerator$GenerateMuzzleReferenceMatcherMethodAndField.visitEnd(MuzzleCodeGenerator.java:207)
        ... 111 more
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
        at net.bytebuddy.jar.asm.ClassReader.readStream(ClassReader.java:309)
        at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:277)
        at io.opentelemetry.javaagent.tooling.muzzle.collector.ReferenceCollector.collectReferencesFrom(ReferenceCollector.java:83)
        ... 113 more
```

If I do `./gradlew --stop` and run the task, it succeeds, then run again and fails - `./gradlew --stop` always brings it back to a working state for one attempt until the next time the daemon is stopped.

**Comment by trask** [comment]
I started running into this recently also 😢

**Comment by iNikem** [comment]
@agoallikmaa Can you take a look at this?

**Comment by agoallikmaa** [comment]
I am currently investigating this issue.
