### ISSUE TITLE
jaxrs-client instrumentation causes failure in JerseyInvocation due to CompletableFuture cast

### ISSUE THREAD

**Issue by ben-childs-docusign** [open-telemetry/opentelemetry-java-instrumentation#2031]
**Describe the bug**
After adding the opentelemetry java agent to our existing application we saw this error during startup:
```
java.lang.ClassCastException: class io.opentelemetry.javaagent.instrumentation.jaxrsclient.v2_0.WrappedFuture cannot be cast to class java.util.concurrent.CompletableFuture 
        at org.glassfish.jersey.client.JerseyInvocation$AsyncInvoker.method(JerseyInvocation.java:556)
	at org.glassfish.jersey.client.JerseyInvocation$AsyncInvoker.method(JerseyInvocation.java:535)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2710)
	at com.spotify.docker.client.DefaultDockerClient.version(DefaultDockerClient.java:600)
	at com.spotify.docker.client.DefaultDockerClient.assertApiVersionIsAbove(DefaultDockerClient.java:2910)
	at com.spotify.docker.client.DefaultDockerClient.listNodes(DefaultDockerClient.java:2239)
```

**Steps to reproduce**
Install the open telemetry agent in a service that uses the docker client or any other library that uses JerseyInvocation$AsyncInvoker.method

**What did you expect to see?**
Tracing should not break JerseyInvocation$AsyncInvoker

**What version are you using?**
v0.12.0

**Environment**
Compiler: AdoptOpenJDK 11.0.9
OS: MacOS X 10.15 

**Additional context**
After reviewing the jersey code it looks like it expects to receive a `CompletableFuture<T>` from JerseyInvocation.submit:
https://github.com/eclipse-ee4j/jersey/blob/95c08d35331478ce47c4ae339c7f8542bf69fa22/core-client/src/main/java/org/glassfish/jersey/client/JerseyInvocation.java
```java
        @Override
        public <T> CompletableFuture<T> method(final String name, final GenericType<T> responseType) {
            if (responseType == null) {
                throw new IllegalArgumentException(LocalizationMessages.RESPONSE_TYPE_IS_NULL());
            }
            builder.requestContext.setMethod(name);
            return (CompletableFuture<T>) new JerseyInvocation(builder).submit(responseType);
        }
```

However the jersey instrumentation code wraps the future using `WrappedFuture<T>` which inherits from `Future<T>`
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/jaxrs-client/jaxrs-client-2.0/jaxrs-client-2.0-jersey-2.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jaxrsclient/v2_0/WrappedFuture.java

One possible fix would be to check if the response type is Completablefuture<T> and then use something like .whenComplete to add in the tracing that we need for the error cases.

**Comment by ben-childs-docusign** [comment]
Something like this might work (not tested)

```java
      if (future instanceof CompletableFuture) {
        // Jersey Client assumes that the future returned is a CompletableFuture,
        // so if we see a CompletableFuture we should keep it
        future = ((CompletableFuture<?>)future).whenComplete((r, e) -> {
          if (e != null) {
            Object prop = context.getProperty(ClientTracingFilter.CONTEXT_PROPERTY_NAME);
            if (prop instanceof Context) {
              tracer().endExceptionally((Context) prop, e);
            }
          }
        });
      } else if (!(future instanceof WrappedFuture)) {
        future = new WrappedFuture<>(future, context);
      }
```
