### ISSUE TITLE
UNIMPLEMENTED: unknown service jaeger.api_v2.CollectorService

### ISSUE THREAD

**Issue by Michi01** [open-telemetry/opentelemetry-java-instrumentation#2096]
I'm trying to add the opentelemetry-java-instrumentation to my SpringBoot+RabbitMQ application, unfortunately I always get a message that the export to Jaeger doesn't work because something is missing. If I set export from jaeger to logging it works. Have I overlooked/forgotten something or is there a bug in the implementation? 

**Used JDK** jdk-12.0.2
**Start Arguments**:  -javaagent:E:/temp/opentelemetry-javaagent-all.jar -Xshare:off -Dotel.exporter=jaeger -Dotel.exporter.jaeger.endpoint=localhost:16686 -Dotel.exporter.jaeger.service.name=RabbitMQLIstener

**Trace**
```
[opentelemetry.auto.trace 2021-01-22 06:39:01:604 +0100] [grpc-default-executor-0] WARN io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporter - Failed to export spans
io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service jaeger.api_v2.CollectorService
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:464)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:428)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:461)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```
**POM.xml**
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.4.2</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.rabbitmq.test</groupId>
    <artifactId>rabbitmqdemo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>rabbitmqdemo</name>
    <description>Demo project for Spring Boot</description>
    <properties>
        <java.version>11</java.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.opentelemetry</groupId>
                <artifactId>opentelemetry-bom</artifactId>
                <version>0.14.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.amqp</groupId>
            <artifactId>spring-rabbit-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-extension-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-extension-annotations</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by anuraaga** [comment]
Hi @Michi01 - everything looks to be in order, and we can even see the agent trying to export to the jaeger service so on the app side it looks fine, and I don't see anything wrong with your command line. 

`UNIMPLEMENTED: unknown service jaeger.api_v2.CollectorService` would mean you are connecting to a gRPC server that is not a jaeger server. Can you confirm the jaeger server is set up to receive spans with gRPC on port 16686?

**Comment by Michi01** [comment]
Thanks, i checked jaeger and notice, that the gRPC Port was changed.
I would never have thought of that because of the error message..

**Comment by anuraaga** [comment]
@Michi01 Yeah we feel you - we've had this long-standing issue which I'm going to bump https://github.com/open-telemetry/opentelemetry-java/issues/2571

**Comment by karan-wahie03** [comment]
@anuraaga  I am facing a similar issue and as per your comment i checked if jaegar server is running or not. I checked the logs and i can see it is up and have attached the logs below. For context, I have deployed jaegar-all in one docker image on my kubernetes cluster and exposed it using a clusterIP type service on 16686. Is there an endpoint where I can check if the jaegar server is up or not? 

```
{"level":"info","ts":1645496566.8321354,"caller":"app/agent.go:69","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1645496566.8324885,"caller":"app/server.go:109","msg":"Query server started","port":16686}
{"level":"info","ts":1645496566.8325214,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1645496566.8325343,"caller":"app/server.go:146","msg":"Starting CMUX server","port":16686}
{"level":"info","ts":1645496566.8325465,"caller":"app/server.go:123","msg":"Starting HTTP server","port":16686}
{"level":"info","ts":1645496566.832557,"caller":"app/server.go:136","msg":"Starting GRPC server","port":16686}
```
