### ISSUE TITLE
Flaky test: :instrumentation:okhttp:okhttp-3.0:javaagent:test

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2153]
I haven't seen a flaky test failure without any containers involved in a loong time I think. Recording for posterity, but I stupidly forgot to copy in the build scan and am just guessing it is an extremely rare case of going over our retry count.

```
2021-02-01T08:29:19.5321908Z > Task :instrumentation:okhttp:okhttp-3.0:javaagent:test
2021-02-01T08:29:19.5322899Z 
2021-02-01T08:29:19.5324158Z OkHttp3AsyncTest > connection error dropped request[0] FAILED
2021-02-01T08:29:19.5325510Z     Condition not satisfied:
2021-02-01T08:29:19.5326180Z 
2021-02-01T08:29:19.5327867Z     jdk.internal.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
2021-02-01T08:29:19.5329296Z 
2021-02-01T08:29:19.5330264Z     assert val == value
2021-02-01T08:29:19.5331287Z            |   |  |
2021-02-01T08:29:19.5332835Z            |   |  'java.lang.NullPointerException'
2021-02-01T08:29:19.5334221Z            |   false
2021-02-01T08:29:19.5335574Z            'java.net.ConnectException'
2021-02-01T08:29:19.5338710Z         at io.opentelemetry.instrumentation.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:59)
2021-02-01T08:29:19.5344593Z         at io.opentelemetry.instrumentation.test.AgentTestRunner.assertTraces(AgentTestRunner.java:121)
2021-02-01T08:29:19.5348210Z         at io.opentelemetry.instrumentation.test.base.HttpClientTest.connection error dropped request(HttpClientTest.groovy:341)
2021-02-01T08:29:19.5350545Z 
2021-02-01T08:29:19.5351398Z         Caused by:
2021-02-01T08:29:19.5352297Z         Assertion failed: 
2021-02-01T08:29:19.5352842Z 
2021-02-01T08:29:19.5353688Z         assert val == value
2021-02-01T08:29:19.5354661Z                |   |  |
2021-02-01T08:29:19.5355992Z                |   |  'java.lang.NullPointerException'
2021-02-01T08:29:19.5357157Z                |   false
2021-02-01T08:29:19.5358314Z                'java.net.ConnectException'
2021-02-01T08:29:19.5360839Z             at io.opentelemetry.instrumentation.test.asserts.AttributesAssert.attribute(AttributesAssert.groovy:44)
2021-02-01T08:29:19.5364798Z             at io.opentelemetry.instrumentation.test.asserts.AttributesAssert.methodMissing(AttributesAssert.groovy:56)
2021-02-01T08:29:19.5368633Z             at io.opentelemetry.instrumentation.test.asserts.SpanAssert.errorEvent_closure1$_closure3(SpanAssert.groovy:151)
2021-02-01T08:29:19.5372688Z             at io.opentelemetry.instrumentation.test.asserts.AttributesAssert.assertAttributes(AttributesAssert.groovy:27)
2021-02-01T08:29:19.5376507Z             at io.opentelemetry.instrumentation.test.asserts.EventAssert.attributes(EventAssert.groovy:46)
2021-02-01T08:29:19.5379950Z             at io.opentelemetry.instrumentation.test.asserts.SpanAssert.errorEvent_closure1(SpanAssert.groovy:150)
2021-02-01T08:29:19.5383414Z             at io.opentelemetry.instrumentation.test.asserts.EventAssert.assertEvent(EventAssert.groovy:36)
2021-02-01T08:29:19.5386907Z             at io.opentelemetry.instrumentation.test.asserts.EventAssert.assertEvent(EventAssert.groovy:27)
2021-02-01T08:29:19.5390190Z             at io.opentelemetry.instrumentation.test.asserts.SpanAssert.event(SpanAssert.groovy:55)
2021-02-01T08:29:19.5393393Z             at io.opentelemetry.instrumentation.test.asserts.SpanAssert.errorEvent(SpanAssert.groovy:148)
2021-02-01T08:29:19.5396776Z             at io.opentelemetry.instrumentation.test.asserts.SpanAssert.errorEvent(SpanAssert.groovy:144)
2021-02-01T08:29:19.5400282Z             at io.opentelemetry.instrumentation.test.base.HttpClientTest.clientSpan_closure1(HttpClientTest.groovy:411)
2021-02-01T08:29:19.5403825Z             at io.opentelemetry.instrumentation.test.asserts.SpanAssert.assertSpan(SpanAssert.groovy:46)
2021-02-01T08:29:19.5407224Z             at io.opentelemetry.instrumentation.test.asserts.SpanAssert.assertSpan(SpanAssert.groovy:36)
2021-02-01T08:29:19.5410557Z             at io.opentelemetry.instrumentation.test.asserts.TraceAssert.span(TraceAssert.groovy:61)
2021-02-01T08:29:19.5415191Z             at io.opentelemetry.instrumentation.test.base.HttpClientTest.clientSpan(HttpClientTest.groovy:401)
2021-02-01T08:29:19.5418194Z             at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:44)
2021-02-01T08:29:19.5421084Z             at io.opentelemetry.instrumentation.test.base.HttpClientTest.$spock_feature_1_10_closure20$_closure54(HttpClientTest.groovy:344)
2021-02-01T08:29:19.5424513Z             at io.opentelemetry.instrumentation.test.asserts.TraceAssert.assertTrace(TraceAssert.groovy:40)
2021-02-01T08:29:19.5428326Z             at io.opentelemetry.instrumentation.test.asserts.InMemoryExporterAssert.trace(InMemoryExporterAssert.groovy:74)
2021-02-01T08:29:19.5432339Z             at io.opentelemetry.instrumentation.test.base.HttpClientTest.connection error dropped request_closure20(HttpClientTest.groovy:342)
2021-02-01T08:29:19.5436554Z             at io.opentelemetry.instrumentation.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:41)
2021-02-01T08:29:19.5439233Z             ... 2 more
2021-02-01T08:29:20.3306498Z 
```

**Comment by laurit** [comment]
Scans for the failure https://scans.gradle.com/s/ttqe4xti3iiuy/tests https://scans.gradle.com/s/gpunyt3dpndzs/tests

**Comment by trask** [comment]
Closing, I don't think this has been seen in a good while.
