### ISSUE TITLE
prometheus exporter does not start on 0.16.0

### ISSUE THREAD

**Issue by ecourreges-orange** [open-telemetry/opentelemetry-java-instrumentation#2255]
**Describe the bug**
I am trying for the first time `-Dotel.metrics.exporter=prometheus`   with default interface and port, and am getting this error:
`java.lang.ClassNotFoundException: io.prometheus.client.exporter.HTTPServer`

Before that I was using `-Dotel.metrics.exporter=none`

Full stack trace:
```
otel-provider2_1     | [opentelemetry.auto.trace 2021-02-11 14:37:27:671 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 0.16.0
otel-provider2_1     | [opentelemetry.auto.trace 2021-02-11 14:37:27:908 +0000] [main] ERROR io.opentelemetry.javaagent.bootstrap.AgentInitializer - Throwable thrown while installing the agent
otel-provider2_1     | java.lang.reflect.InvocationTargetException
otel-provider2_1     | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
otel-provider2_1     | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
otel-provider2_1     | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
otel-provider2_1     | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
otel-provider2_1     | 	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.startAgent(AgentInitializer.java:65)
otel-provider2_1     | 	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:51)
otel-provider2_1     | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
otel-provider2_1     | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
otel-provider2_1     | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
otel-provider2_1     | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
otel-provider2_1     | 	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
otel-provider2_1     | 	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
otel-provider2_1     | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
otel-provider2_1     | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
otel-provider2_1     | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
otel-provider2_1     | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
otel-provider2_1     | 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
otel-provider2_1     | 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
otel-provider2_1     | Caused by: java.lang.NoClassDefFoundError: io/prometheus/client/exporter/HTTPServer
otel-provider2_1     | 	at io.opentelemetry.sdk.autoconfigure.MetricExporterConfiguration.configurePrometheusMetrics(MetricExporterConfiguration.java:110)
otel-provider2_1     | 	at io.opentelemetry.sdk.autoconfigure.MetricExporterConfiguration.configureExporter(MetricExporterConfiguration.java:31)
otel-provider2_1     | 	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.configureMeterProvider(OpenTelemetrySdkAutoConfiguration.java:48)
otel-provider2_1     | 	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:31)
otel-provider2_1     | 	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installAgentTracer(OpenTelemetryInstaller.java:36)
otel-provider2_1     | 	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.beforeByteBuddyAgent(OpenTelemetryInstaller.java:27)
otel-provider2_1     | 	at io.opentelemetry.javaagent.tooling.AgentInstaller.installComponentsBeforeByteBuddy(AgentInstaller.java:164)
otel-provider2_1     | 	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:98)
otel-provider2_1     | 	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:82)
otel-provider2_1     | 	... 18 more
otel-provider2_1     | Caused by: java.lang.ClassNotFoundException: io.prometheus.client.exporter.HTTPServer
otel-provider2_1     | 	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
otel-provider2_1     | 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
otel-provider2_1     | 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
otel-provider2_1     | 	... 27 more
```

**Comment by anuraaga** [comment]
Thanks @ecourreges-orange! Looks like we have an issue in 0.16.0 we'll get the fix in.

**Comment by ecourreges-orange** [comment]
Sorry @anuraaga, still no luck for me with 0.16.1, am I doing something wrong?

```
 java -jar -javaagent:./opentelemetry-javaagent-all.jar 
-Dapplication.name=chucknorris-client -Dapplication.home=. 
-Dotel.resource.attributes=service.name=chucknorris-client 
-Dotel.bsp.schedule.delay=1000 
-Dotel.trace.exporter=zipkin 
-Dotel.exporter.zipkin.endpoint=http://xxx/api/v2/spans -Dotel.propagators=tracecontext,b3 -Dotel.trace.sampler=parentbased_traceidratio 
-Dotel.trace.sampler.arg=1.0 
-Dotel.metrics.exporter=prometheus 
myProgram.jar
```

```
[opentelemetry.auto.trace 2021-02-12 15:47:37:546 +0100] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 0.16.1
[opentelemetry.auto.trace 2021-02-12 15:47:37:672 +0100] [main] ERROR io.opentelemetry.javaagent.bootstrap.AgentInitializer - Throwable thrown while installing the agent
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.startAgent(AgentInitializer.java:65)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.NoClassDefFoundError: io/prometheus/client/exporter/HTTPServer
	at io.opentelemetry.sdk.autoconfigure.MetricExporterConfiguration.configurePrometheusMetrics(MetricExporterConfiguration.java:110)
	at io.opentelemetry.sdk.autoconfigure.MetricExporterConfiguration.configureExporter(MetricExporterConfiguration.java:31)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.configureMeterProvider(OpenTelemetrySdkAutoConfiguration.java:48)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:31)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installAgentTracer(OpenTelemetryInstaller.java:36)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.beforeByteBuddyAgent(OpenTelemetryInstaller.java:27)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installComponentsBeforeByteBuddy(AgentInstaller.java:164)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:98)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:82)
	... 18 more
Caused by: java.lang.ClassNotFoundException: io.prometheus.client.exporter.HTTPServer
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 27 more

```

**Comment by anuraaga** [comment]
Sorry @ecourreges-orange we didn't quite get this into the patch. And since metrics is currently alpha, we don't generally make this a priority for hotfixing. Just wondering, are you using metrics in production?

**Comment by ecourreges-orange** [comment]
> 
> 
> Sorry @ecourreges-orange we didn't quite get this into the patch. And since metrics is currently alpha, we don't generally make this a priority for hotfixing. Just wondering, are you using metrics in production?

Thanks for your quick answer.
I just wanted to test the functionality, but I can wait, or I guess I can build it myself to try it out.
My priority is tracing as well, most projects already have their own metrics.

**Comment by trask** [comment]
hey @ecourreges-orange, you can pull latest SNAPSHOT from https://oss.sonatype.org/content/repositories/snapshots/io/opentelemetry/javaagent/opentelemetry-javaagent/0.17.0-SNAPSHOT/
