### ISSUE TITLE
Agent - Prometheus Metrics Exporter - ClassNotFoundException for Prometheus HTTPServer

### ISSUE THREAD

**Issue by fjunior87** [open-telemetry/opentelemetry-java-instrumentation#2284]
**Describe the bug**
Tried to use the prometheus metrics exporter for the java agent and received an error of ClassNotFoundException:

```
[opentelemetry.auto.trace 2021-02-14 20:49:10:635 -0300] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 0.16.1
[opentelemetry.auto.trace 2021-02-14 20:49:10:848 -0300] [main] ERROR io.opentelemetry.javaagent.bootstrap.AgentInitializer - Throwable thrown while installing the agent
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.startAgent(AgentInitializer.java:65)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: io/prometheus/client/exporter/HTTPServer
	at io.opentelemetry.sdk.autoconfigure.MetricExporterConfiguration.configurePrometheusMetrics(MetricExporterConfiguration.java:110)
	at io.opentelemetry.sdk.autoconfigure.MetricExporterConfiguration.configureExporter(MetricExporterConfiguration.java:31)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.configureMeterProvider(OpenTelemetrySdkAutoConfiguration.java:48)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:31)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installAgentTracer(OpenTelemetryInstaller.java:36)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.beforeByteBuddyAgent(OpenTelemetryInstaller.java:27)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installComponentsBeforeByteBuddy(AgentInstaller.java:164)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:98)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:82)
	... 18 more
Caused by: java.lang.ClassNotFoundException: io.prometheus.client.exporter.HTTPServer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 27 more
```

**Steps to reproduce**
Started a WSO2 Micro Integrator adding the following parameters:

```
-Dotel.metrics.exporter=prometheus
-Dotel.propagators=jaeger
-Dotel.resource.attributes=service.name=myservice
-javaagent:/Users/user/Documents/opentelemetry-javaagent-all.jar

```
**What did you expect to see?**
I was expecting to see an Endpoint for pulling metrics to be used in Prometheus.

**What did you see instead?**
Got the error below:

```
[opentelemetry.auto.trace 2021-02-14 20:49:10:635 -0300] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 0.16.1
[opentelemetry.auto.trace 2021-02-14 20:49:10:848 -0300] [main] ERROR io.opentelemetry.javaagent.bootstrap.AgentInitializer - Throwable thrown while installing the agent
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.startAgent(AgentInitializer.java:65)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: io/prometheus/client/exporter/HTTPServer
	at io.opentelemetry.sdk.autoconfigure.MetricExporterConfiguration.configurePrometheusMetrics(MetricExporterConfiguration.java:110)
	at io.opentelemetry.sdk.autoconfigure.MetricExporterConfiguration.configureExporter(MetricExporterConfiguration.java:31)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.configureMeterProvider(OpenTelemetrySdkAutoConfiguration.java:48)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:31)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installAgentTracer(OpenTelemetryInstaller.java:36)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.beforeByteBuddyAgent(OpenTelemetryInstaller.java:27)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installComponentsBeforeByteBuddy(AgentInstaller.java:164)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:98)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:82)
	... 18 more
Caused by: java.lang.ClassNotFoundException: io.prometheus.client.exporter.HTTPServer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 27 more
```
**What version are you using?**
(e.g., `v0.9.0`, `393e4a2`, etc)
v0.16.1

**Environment**
Runtime (if different from JDK above): openjdk version "1.8.0_252"
OS (if different from OS compiled on): MacOS Catalina

**Additional context**

**Comment by anuraaga** [comment]
Hi @fjunior87 - there is indeed an issue with prometheus in the latest version. It's fixed in the latest snapshot, can you give it a try?

https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2255#issuecomment-778495394

**Comment by sonika-gautami** [comment]
updated the file: 
opentelemetry-java-instrumentation/javaagent-tooling/javaagent-tooling.gradle
from
	implementation group: 'io.grpc', name: 'grpc-netty', version: '1.34.1'
to
  implementation group: 'io.prometheus', name: 'simpleclient_httpserver', version: '0.10.0'
  implementation group: 'io.prometheus', name: 'simpleclient', version: '0.10.0'
  implementation group: 'io.prometheus', name: 'simpleclient_common', version: '0.10.0'
  implementation group: 'io.grpc', name: 'grpc-all', version: '1.35.0'

and then 
cd opentelemetry-java-instrumentation/
./gradlew assemble
mv javaagent/build/libs/opentelemetry-javaagent-0.17.0-SNAPSHOT.jar /tmp/opentelemetry-javaagent-all.jar
and then using this jar solved issue for me.

**Comment by fjunior87** [comment]
With latest the prometheus exporter it worked(opentelemetry-javaagent-0.17.0-20210215.034613-5-all.jar). We can close the issue.
Thanks
