### ISSUE TITLE
Fix Grizzly context propagation

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2640]
Grizzly seems to have a grizzly model of possibly serving a different request when handling one after we've created a span. This initial attempt didn't work

```
          // The Grizzly HTTP handler seems to be run within the context of a request which can be
          // suspended causing a different request to be executed. Assuming our tests are complete,
          // it does not seem to be required to propagate context into this task.
          //
          // https://github.com/eclipse-ee4j/grizzly/blob/a2ce7775658e11fbccbb9acd32e2daf2b0799f45/modules/http-server/src/main/java/org/glassfish/grizzly/http/server/HttpHandler.java#L178
          if (enclosingClass.getName().equals("org.glassfish.grizzly.http.server.HttpHandler")) {
            return true;
          }
```

with some exceptions like

```
 java.lang.AssertionError: Thread [Grizzly-worker(3)] opened a scope of {opentelemetry-trace-span-key=RecordEventsReadableSpan{traceId=00000000000000000000000000000123, spanId=f2313f515cc34f57, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000123, spanId=0000000000000456, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=true, valid=true}, name=HttpCodecFilter.handleRead, kind=SERVER, attributes=AttributesMap{data={http.method=GET, net.peer.ip=127.0.0.1, thread.id=36, thread.name=Grizzly-worker(3), http.client_ip=1.1.1.1, http.url=http://localhost:11002/success, net.peer.port=44180, http.user_agent=test-user-agent, http.flavor=1.1, http.status_code=200}, capacity=128, totalAddedValues=10}, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1616742268782002100, endEpochNanos=1616742268785852625}, opentelemetry-traces-server-span-key=RecordEventsReadableSpan{traceId=00000000000000000000000000000123, spanId=f2313f515cc34f57, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000123, spanId=0000000000000456, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=true, valid=true}, name=HttpCodecFilter.handleRead, kind=SERVER, attributes=AttributesMap{data={http.method=GET, net.peer.ip=127.0.0.1, thread.id=36, thread.name=Grizzly-worker(3), http.client_ip=1.1.1.1, http.url=http://localhost:11002/success, net.peer.port=44180, http.user_agent=test-user-agent, http.flavor=1.1, http.status_code=200}, capacity=128, totalAddedValues=10}, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1616742268782002100, endEpochNanos=1616742268785852625}} here:
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:152)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:288)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:206)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:136)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:114)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:838)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:113)
        at org.glassfish.grizzly.strategies.LeaderFollowerNIOStrategy.executeIoEvent(LeaderFollowerNIOStrategy.java:102)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.executeIoEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.nio.SelectorRunner.iterateKeyEvents(SelectorRunner.java:409)
        at org.glassfish.grizzly.nio.SelectorRunner.iterateKeys(SelectorRunner.java:378)
        at org.glassfish.grizzly.nio.SelectorRunner.doSelect(SelectorRunner.java:342)
        at org.glassfish.grizzly.nio.SelectorRunner.run(SelectorRunner.java:274)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:564)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:544)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by trask** [comment]
I think this can be closed now, as the tests are passing with `otel.javaagent.testing.fail-on-context-leak=true`
