### ISSUE TITLE
Sporadic test failure - Netty41 connection inteference

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2718]
I actually get this very frequently locally, first time I saw it on CI

```
Netty41ClientTest > test connection interference FAILED
    Method timed out after 5.00 seconds
        at app//io.opentelemetry.instrumentation.test.asserts.TraceAssert.assertTrace(TraceAssert.groovy:32)
        at app//io.opentelemetry.instrumentation.test.asserts.InMemoryExporterAssert.trace(InMemoryExporterAssert.groovy:75)
        at Netty41ClientTest.test connection interference_closure4(Netty41ClientTest.groovy:120)
        at app//io.opentelemetry.instrumentation.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:42)
        at app//io.opentelemetry.instrumentation.test.InstrumentationSpecification.assertTraces(InstrumentationSpecification.groovy:99)
        at Netty41ClientTest.test connection interference(Netty41ClientTest.groovy:119)

```

https://github.com/open-telemetry/opentelemetry-java-instrumentation/runs/2267961730?check_suite_focus=true

**Comment by iNikem** [comment]
Yeah, 5 sec timeout is too aggressive for that test. And I am not sure that we want this timeout at all.

**Comment by laurit** [comment]
There is another kind of failure from the same test https://scans.gradle.com/s/2twawyc4jzp7c/tests/flaky
```
assert spans.size() == expectedSize	
       |     |      |  |	
       |     2      |  3	
       |            false
```
Currently this test sends 2 requests on the same channel, it fail reliably when more requests are sent. Context is kept in a channel attribute which gets overwritten on each write so some spans will leak and remain unfinished. Is this test a valid use case?

**Comment by iNikem** [comment]
Hmmm... reading comments on `SingleNettyConnection` I now tend to think that "test connection interference" should be removed. Netty CANNOT work with several concurrent requests on the same channel.
