### ISSUE TITLE
Sporadic test failure - apache-camel-2.20

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#2721]
See https://scans.gradle.com/s/5y2jjwe64owh6/console-log?task=:instrumentation:apache-camel-2.20:javaagent:test

```
Caused by:   
   org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://localhost:11004/serviceOne with statusCode: 500   
   at org.apache.camel.component.http.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:274)   
   at org.apache.camel.component.http.HttpProducer.process(HttpProducer.java:183)   
   at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)   
   at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)   
   at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)   
   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)   
   at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)   
   at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)   
   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)   
   at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:62)   
   at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:186)   
   at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:86)   
   at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:541)   
   at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:506)   
   at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:369)   
   at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:506)   
   at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:229)   
   at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:144)   
   at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:161)
```

**Comment by laurit** [comment]
I think we can close this. Hopefully this was fixed by https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2753
