### ISSUE TITLE
Sporadic test failure RMI

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2734]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/runs/2275817476?check_suite_focus=true

```
> Task :instrumentation:rmi:javaagent:test

RmiTest > Client call creates spans FAILED
    java.rmi.ConnectException: Connection refused to host: 10.1.1.4; nested exception is: 
    	java.net.ConnectException: Connection timed out
        at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
        at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
        at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
        at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:132)
        at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:217)
        at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:162)
        at RmiTest.Client call creates spans_closure1(RmiTest.groovy:37)
        at RmiTest.Client call creates spans_closure1(RmiTest.groovy)
        at io.opentelemetry.instrumentation.test.utils.TraceUtils.runUnderTrace_closure1(TraceUtils.groovy:38)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at io.opentelemetry.instrumentation.test.utils.TraceUtils.runUnderTrace(TraceUtils.groovy:37)
        at RmiTest.Client call creates spans(RmiTest.groovy:35)

        Caused by:
        java.net.ConnectException: Connection timed out
            at java.base/sun.nio.ch.Net.connect(Net.java:574)
            at java.base/sun.nio.ch.Net.connect(Net.java:563)
            at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
            at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
            at java.base/java.net.Socket.connect(Socket.java:648)
            at java.base/java.net.Socket.connect(Socket.java:597)
            at java.base/java.net.Socket.<init>(Socket.java:520)
            at java.base/java.net.Socket.<init>(Socket.java:294)
            at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40)
            at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
            ... 12 more

RmiTest > Service throws exception and its propagated to spans FAILED
    Expected exception of type 'java.lang.RuntimeException', but got 'java.rmi.ConnectException'
        at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:80)
        at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:67)
        at RmiTest.Service throws exception and its propagated to spans(RmiTest.groovy:102)

        Caused by:
        java.rmi.ConnectException: Connection refused to host: 10.1.1.4; nested exception is: 
        	java.net.ConnectException: Connection timed out
            at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
            at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
            at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
            at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:132)
            at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:217)
            at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:162)
            at RmiTest.Service throws exception and its propagated to spans_closure4(RmiTest.groovy:98)
            at RmiTest.Service throws exception and its propagated to spans_closure4(RmiTest.groovy)
            at io.opentelemetry.instrumentation.test.utils.TraceUtils.runUnderTrace_closure1(TraceUtils.groovy:38)
            at groovy.lang.Closure.call(Closure.java:405)
            at groovy.lang.Closure.call(Closure.java:421)
            at io.opentelemetry.instrumentation.test.utils.TraceUtils.runUnderTrace(TraceUtils.groovy:37)
            at RmiTest.Service throws exception and its propagated to spans(RmiTest.groovy:96)

            Caused by:
            java.net.ConnectException: Connection timed out
                at java.base/sun.nio.ch.Net.connect(Net.java:574)
                at java.base/sun.nio.ch.Net.connect(Net.java:563)
                at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
                at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
                at java.base/java.net.Socket.connect(Socket.java:648)
                at java.base/java.net.Socket.connect(Socket.java:597)
                at java.base/java.net.Socket.<init>(Socket.java:520)
                at java.base/java.net.Socket.<init>(Socket.java:294)
                at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40)
                at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
                ... 12 more

RmiTest > Client call using ServerLegacy_stub creates spans FAILED
    java.rmi.ConnectException: Connection refused to host: 10.1.1.4; nested exception is: 
    	java.net.ConnectException: Connection timed out
        at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
        at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
        at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
        at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:132)
        at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:217)
        at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:162)
        at RmiTest.Client call using ServerLegacy_stub creates spans_closure6(RmiTest.groovy:145)
        at RmiTest.Client call using ServerLegacy_stub creates spans_closure6(RmiTest.groovy)
        at io.opentelemetry.instrumentation.test.utils.TraceUtils.runUnderTrace_closure1(TraceUtils.groovy:38)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at io.opentelemetry.instrumentation.test.utils.TraceUtils.runUnderTrace(TraceUtils.groovy:37)
        at RmiTest.Client call using ServerLegacy_stub creates spans(RmiTest.groovy:143)

        Caused by:
        java.net.ConnectException: Connection timed out
            at java.base/sun.nio.ch.Net.connect(Net.java:574)
            at java.base/sun.nio.ch.Net.connect(Net.java:563)
            at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
            at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
            at java.base/java.net.Socket.connect(Socket.java:648)
            at java.base/java.net.Socket.connect(Socket.java:597)
            at java.base/java.net.Socket.<init>(Socket.java:520)
            at java.base/java.net.Socket.<init>(Socket.java:294)
            at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40)
            at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
            ... 12 more
```

**Comment by laurit** [comment]
I think we can close this.
