### ISSUE TITLE
gRPC instrumentation breaks ProtoReflectionService

### ISSUE THREAD

**Issue by jguerra** [open-telemetry/opentelemetry-java-instrumentation#2853]
**Describe the bug**
When running with otel agent 1.1.0 and grpc instrumentation the `ProtoReflectionService` (https://github.com/grpc/grpc-java/blob/master/services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java) fails with a NPE.

**Steps to reproduce**
- Run a grpc server with `ProtoReflecitonService` and otel-agent 1.1.0
- call the reflection endpoint. For example, `grpcurl --plaintext host:port list`

**What did you expect to see?**
The service to function

**What did you see instead?**
NPE on grpc server 

> java.lang.NullPointerException: null
	at io.grpc.protobuf.services.ProtoReflectionService.getRefreshedIndex(ProtoReflectionService.java:93)
	at io.grpc.protobuf.services.ProtoReflectionService.serverReflectionInfo(ProtoReflectionService.java:134)
	at io.grpc.reflection.v1alpha.ServerReflectionGrpc$MethodHandlers.invoke(ServerReflectionGrpc.java:220)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler.startCall(ServerCalls.java:228)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
	at io.grpc.Contexts.interceptCall(Contexts.java:52)
	at io.opentelemetry.javaagent.shaded.instrumentation.grpc.v1_5.TracingServerInterceptor.interceptCall(TracingServerInterceptor.java:58)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:648)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:626)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1900(ServerImpl.java:416)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInternal(ServerImpl.java:557)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInContext(ServerImpl.java:532)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**What version are you using?**
otel-agent 1.1.0
grpc 1.34.1

**Environment**
Compiler: AdoptOpenJDK 11.0.9
OS: debian buster

**Additional context**
It looks like the NPE may be due to 

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/grpc-1.5/library/src/main/java/io/opentelemetry/instrumentation/grpc/v1_5/internal/ContextStorageBridge.java

In particular 
`grpc.io.Context$Key.get(Context)` checks `context.keyValueEntries` and it only has `otel-context` in it, not the expected key `io.grpc.Server.SERVER_CONTEXT_KEY`

**Comment by fuleow** [comment]
Thanks for the quick fix @anuraaga . Is there an ETA for the next planned release?

**Comment by anuraaga** [comment]
Hi @fuleow - I think we'll be releasing next week or so. Hope that's ok, in hindsight a patch release may have been a good idea

**Comment by fuleow** [comment]
No problem, next week sounds good. Reflection isn’t a critical production functionality for us but some of our devs have said it’s a nice quality of life feature
