### ISSUE TITLE
Retry muzzle github step

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#3105]
Since we don't use any caching for muzzle, it's not that uncommon for one out of the dozens of muzzle tasks to flake with a random HTTP error. This is a Gradle download error, I also commonly see maven artifact download flakes.

```
Run ./gradlew :instrumentation:scala-executors:javaagent:muzzle
Downloading https://services.gradle.org/distributions/gradle-7.0.1-bin.zip

Error: Exception in thread "main" javax.net.ssl.SSLException: readHandshakeRecord
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1335)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLCo
```

Since we don't use gradle-retry-plugin (nor would it help for random HTTP errors), should we add the GitHub actions retry to muzzle? https://github.com/marketplace/actions/retry-step

**Comment by laurit** [comment]
Lately I have seen downloading gradle fail multiple times so it would be really nice to have this fixed. Maybe instead of retry we could cache it somehow https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#using-the-cache-action should work for this.

**Comment by anuraaga** [comment]
We intentionally don't cache on muzzle since the sheer volume of dependencies gets overwhelming. While we can cache the wrapper only perhaps, I feel I've seen at least as many non-wrapper flakes as wrapper ones so would probably just stick with the retry.
