### ISSUE TITLE
Agent not loading grpc-netty-shaded native libraries

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#3246]
In smoke tests, I see this spam when initializing an OTLP exporter, which is probably a result of our obfuscation not being respected by native library loading. We do have them in the JAR I think so if we don't take advantage, for a bit extra performance, it's a waste of jar size.

```
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    14:30:37.833 INFO  i.o.s.LinuxTestContainerManager - STDERR:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    14:30:37.833 INFO  i.o.s.LinuxTestContainerManager - STDERR:        at java.lang.reflect.Method.invoke(Method.java:498)
    14:30:37.833 INFO  i.o.s.LinuxTestContainerManager - STDERR:        at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
    14:30:37.833 INFO  i.o.s.LinuxTestContainerManager - STDERR:        at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
    14:30:37.833 INFO  i.o.s.LinuxTestContainerManager - STDERR:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    14:30:37.833 INFO  i.o.s.LinuxTestContainerManager - STDERR:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    14:30:37.833 INFO  i.o.s.LinuxTestContainerManager - STDERR:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    14:30:37.833 INFO  i.o.s.LinuxTestContainerManager - STDERR:        at java.lang.reflect.Method.invoke(Method.java:498)
    14:30:37.833 INFO  i.o.s.LinuxTestContainerManager - STDERR:        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:401)
    14:30:37.833 INFO  i.o.s.LinuxTestContainerManager - STDERR:        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:416)
    14:30:37.835 INFO  i.o.s.LinuxTestContainerManager - STDERR:        Suppressed: java.lang.UnsatisfiedLinkError: io_grpc_netty_shaded_netty_transport_native_epoll_x86_64 (Not found in java.library.path)
    14:30:37.835 INFO  i.o.s.LinuxTestContainerManager - STDERR:                at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1468)
    14:30:37.835 INFO  i.o.s.LinuxTestContainerManager - STDERR:                at java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1419)
    14:30:37.835 INFO  i.o.s.LinuxTestContainerManager - STDERR:                at java.lang.System.loadLibrary(System.java:564)
    14:30:37.835 INFO  i.o.s.LinuxTestContainerManager - STDERR:                at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
    14:30:37.835 INFO  i.o.s.LinuxTestContainerManager - STDERR:                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    14:30:37.835 INFO  i.o.s.LinuxTestContainerManager - STDERR:                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    14:30:37.835 INFO  i.o.s.LinuxTestContainerManager - STDERR:                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    14:30:37.835 INFO  i.o.s.LinuxTestContainerManager - STDERR:                at java.lang.reflect.Method.invoke(Method.java:498)
    14:30:37.835 INFO  i.o.s.LinuxTestContainerManager - STDERR:                at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)
    14:30:37.835 INFO  i.o.s.LinuxTestContainerManager - STDERR:                at java.security.AccessController.doPrivileged(AccessController.java:682)
    14:30:37.835 INFO  i.o.s.LinuxTestContainerManager - STDERR:                at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)
    14:30:37.836 INFO  i.o.s.LinuxTestContainerManager - STDERR:                at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
    14:30:37.836 INFO  i.o.s.LinuxTestContainerManager - STDERR:                ... 40 more
```

**Comment by laurit** [comment]
I have also been fooled by this. If you look closely then you'll see that it eventually succeeds
```
2021-05-26T18:40:45.8375970Z     18:40:45.723 INFO  i.o.s.LinuxTestContainerManager - STDERR: [otel.javaagent 2021-05-26 18:40:45:723 +0000] [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - Successfully loaded the library /usr/local/tomcat/temp/libio_grpc_netty_shaded_netty_transport_native_epoll_x86_64289507317395708339.so
```
I guess it tries to load it in different ways and logs exceptions from intermediate steps.

**Comment by anuraaga** [comment]
Oops! Sorry for false alarm, thanks
