### ISSUE TITLE
ClassNotFoundException: HandlerMappingResourceNameFilter

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3306]
Repro at https://github.com/trask/jboss-ear-otel-javaagent-issue

* `mvn clean package`
* copy `hello-ear/target/hello-ear-1.0-SNAPSHOT.ear` to wildfly deployments directory
* start wildfly
* app will fail during startup with exception below

Initial analysis:

* The issue is caused by spring being provided by the ear libs, but used in the war
  https://github.com/trask/jboss-ear-otel-javaagent-issue/blob/a04696c98860255ac7ac4fe2277cb16b429bf16c/hello-web/pom.xml#L19-L20
* JBoss modules keeps an internal record of all the packages that that ear module can load, and since `io.opentelemetry.javaagent.instrumentation.springwebmvc` is not in that list, it doesn't even bother trying to load the helper class
* One potential fix for this is #3101
  We have this fix in our distro for a few months now with no issues
* I believe DataDog fixed this same issue but in a different way DataDog/dd-trace-java#1879
  I would love to understand this comment better, since it points to a potential issue with the above fix (@randomanderson if you happen to remember)
  > This can't be done at BeanDefinition construction time because Spring heavy use of clone() which sometimes only copies the classname
* I wonder if the same issue can occur for other helper classes that are looked up by name, specifically the SPI classes that we inject as helper classes, in which case maybe the better fix is at the class loader level, either generically, or specifically hacking the JBoss modules class loader
* One other thought is to put all the helper classes inside of the same package that we are instrumenting (e.g. `org.springframework.web.context` in this case). This would be nice to avoid, although I wonder if we can have similar issues with JPMS (or do we already account for this somehow)?

```
21:20:21,255 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 78) MSC000001: Failed to start service jboss.deployment.subunit."hello-ear-1.0-SNAPSHOT.ear"."com.example-hello-web-1.0-SNAPSHOT.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.subunit."hello-ear-1.0-SNAPSHOT.ear"."com.example-hello-web-1.0-SNAPSHOT.war".undertow-deployment: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping': Invocation of init method failed; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [io.opentelemetry.javaagent.instrumentation.springwebmvc.HandlerMappingResourceNameFilter] for bean with name 'otelAutoDispatcherFilter'; nested exception is java.lang.ClassNotFoundException: io.opentelemetry.javaagent.instrumentation.springwebmvc.HandlerMappingResourceNameFilter from [Module "deployment.hello-ear-1.0-SNAPSHOT.ear.com.example-hello-web-1.0-SNAPSHOT.war" from Service Module Loader]
Related cause: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [io.opentelemetry.javaagent.instrumentation.springwebmvc.HandlerMappingResourceNameFilter] for bean with name 'otelAutoDispatcherFilter'; nested exception is java.lang.ClassNotFoundException: io.opentelemetry.javaagent.instrumentation.springwebmvc.HandlerMappingResourceNameFilter from [Module "deployment.hello-ear-1.0-SNAPSHOT.ear.com.example-hello-web-1.0-SNAPSHOT.war" from Service Module Loader]
        at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping': Invocation of init method failed; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [io.opentelemetry.javaagent.instrumentation.springwebmvc.HandlerMappingResourceNameFilter] for bean with name 'otelAutoDispatcherFilter'; nested exception is java.lang.ClassNotFoundException: io.opentelemetry.javaagent.instrumentation.springwebmvc.HandlerMappingResourceNameFilter from [Module "deployment.hello-ear-1.0-SNAPSHOT.ear.com.example-hello-web-1.0-SNAPSHOT.war" from Service Module Loader]
Related cause: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [io.opentelemetry.javaagent.instrumentation.springwebmvc.HandlerMappingResourceNameFilter] for bean with name 'otelAutoDispatcherFilter'; nested exception is java.lang.ClassNotFoundException: io.opentelemetry.javaagent.instrumentation.springwebmvc.HandlerMappingResourceNameFilter from [Module "deployment.hello-ear-1.0-SNAPSHOT.ear.com.example-hello-web-1.0-SNAPSHOT.war" from Service Module Loader]
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:702)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:668)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:716)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:591)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:530)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:170)
        at javax.servlet.api@2.0.0.Final//javax.servlet.GenericServlet.init(GenericServlet.java:180)
        at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
        at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
        at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
        at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:305)
        at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)
        at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:588)
        at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
        at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
        at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97)
        at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
        ... 8 more
Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [io.opentelemetry.javaagent.instrumentation.springwebmvc.HandlerMappingResourceNameFilter] for bean with name 'otelAutoDispatcherFilter'; nested exception is java.lang.ClassNotFoundException: io.opentelemetry.javaagent.instrumentation.springwebmvc.HandlerMappingResourceNameFilter from [Module "deployment.hello-ear-1.0-SNAPSHOT.ear.com.example-hello-web-1.0-SNAPSHOT.war" from Service Module Loader]
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1542)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:686)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:656)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1670)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:570)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:550)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:536)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.context.support.AbstractApplicationContext.getBeanNamesForType(AbstractApplicationContext.java:1288)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getCandidateBeanNames(AbstractHandlerMethodMapping.java:239)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:222)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:212)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:206)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
        ... 41 more
Caused by: java.lang.ClassNotFoundException: io.opentelemetry.javaagent.instrumentation.springwebmvc.HandlerMappingResourceNameFilter from [Module "deployment.hello-ear-1.0-SNAPSHOT.ear.com.example-hello-web-1.0-SNAPSHOT.war" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.util.ClassUtils.forName(ClassUtils.java:284)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:469)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1607)
        at deployment.hello-ear-1.0-SNAPSHOT.ear//org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1534)
        ... 54 more
```

**Comment by randomanderson** [comment]
Yes DataDog/dd-trace-java#1879 was to fix the exact scenario of ear and war classloading leading to problems.

> This can't be done at BeanDefinition construction time because Spring heavy use of clone() which sometimes only copies the classname

This was a while ago so I don't remember the exact details. Spring clones beans a lot.  See `clone()`, `cloneBeanDefinition()`, `overrideFrom()`, and all of the copy constructors of `AbstractBeanDefinition` and its class hierarchy.  Somewhere in that mix, I don't remember where, the bean classname is copied but the bean class isn't (maybe it was even jboss specific 🤷‍♂️ ).

I was able to determine this by putting a breakpoint in `AbstractBeanDefinition.resolveBeanClass()` or maybe `doResolveBeanClass()`.  `beanClass` wasn't defined when `beanClassName` was `datadog.trace.instrumentation.springweb.HandlerMappingResourceNameFilter`. That should never be the case given that the bean class is set at construction but it was.

**Comment by laurit** [comment]
From previous experience I know that the best way to make sure that such integration classes are found is to add them to the same package as framework classes. Even if we'd hack jboss modules to make it look for our classes from all modules we'd have the same issue with osgi class loaders.
To me datadog fix seems a bit problematic. `HandlerMappingResourceNameFilter` depends on spring mvc classes but a reference to this class is injected into `AbstractBeanFactory`. If spring-beans and spring-webmvc are not in the same class loader I suspect that this will fail muzzle or cause an exception during runtime.
My understanding is that we don't need to move all helper classes. This problem only affects classes that are injected into loader `A` and a loaded by name from loader `B` which delegates to `A`. If this delegation is conditional (only delegates some packages etc.) then there might be trouble.
