### ISSUE TITLE
Getting exception class java.lang.ClassCircularityError 

### ISSUE THREAD

**Issue by alvinhom** [open-telemetry/opentelemetry-java-instrumentation#3396]
I am using otel java instrumentation to instrument my services.  In one of them, I am getting the following exceptions:

Caught exception class java.lang.ClassCircularityError logging exception class java.lang.ClassCircularityError
java.lang.ClassCircularityError: java/lang/ClassLoader$1
	at com.yyyy.ZZZSecurityManager.checkPermission(ARSecurityManager.java:16)
	at java.base/java.lang.SecurityManager.checkPropertiesAccess(SecurityManager.java:1034)
	at java.base/java.lang.System.getProperties(System.java:718)
	at org.apache.logging.log4j.util.PropertiesUtil$Environment.hasSystemProperty(PropertiesUtil.java:484)
	at org.apache.logging.log4j.util.PropertiesUtil$Environment.get(PropertiesUtil.java:497)
	at org.apache.logging.log4j.util.PropertiesUtil$Environment.access$200(PropertiesUtil.java:422)
	at org.apache.logging.log4j.util.PropertiesUtil.getStringProperty(PropertiesUtil.java:370)
	at org.apache.logging.log4j.util.PropertiesUtil.getBooleanProperty(PropertiesUtil.java:155)
	at org.apache.logging.log4j.status.StatusLogger.isDebugPropertyEnabled(StatusLogger.java:120)
	at org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:407)
	at org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:329)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1906)
	at org.apache.logging.log4j.spi.AbstractLogger.debug(AbstractLogger.java:397)
	at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:311)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$RegisteredCancellable.run(DefaultShutdownCallbackRegistry.java:109)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)

The code in the SecurityManager is really simple.  

public final class ZZZSecurityManager extends SecurityManager {
    @Override
    public final void checkPermission(Permission perm)
    {
        if (perm instanceof BasicPermission || perm instanceof SocketPermission || perm instanceof FilePermission || perm instanceof MBeanPermission)
        {
            return;
        } else {
            super.checkPermission(perm);
        }
    }
    
    @Override
    public void checkPermission(Permission perm, Object context) {
        if (context instanceof AccessControlContext && perm instanceof MBeanTrustPermission) {
            return;
        } 
        super.checkPermission(perm); 
    }

**Comment by trask** [comment]
hey @alvinhom! a couple of questions

* can you post output from your `java -version`?
* is this happening during JVM shutdown? (stack trace looks like possibly a shutdown hook)
* which line is line 16 in your security manager? (to understand the stack trace better)

**Comment by alvinhom** [comment]
JDK Version info:
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)

The exception is happening on service startup, I did not attach all the other exception stacks, but the same exception shows up multiple times on log.  I am guessing this exception triggers the shutdown.  It is basically a custom SecurityManager which is invoked when  a security check is needed.

Line 16 is this one:
if (perm instanceof BasicPermission || perm instanceof SocketPermission || perm instanceof FilePermission || perm instanceof MBeanPermission)

**Comment by laurit** [comment]
@alvinhom a sample app that reproduces this issue would be nice. Does it always fail or only sometimes? Are you using `System.setSecurityManager` or `-Djava.security.manager` to set up security manager? If you are using `System.setSecurityManager` does it help if you call `checkPermission (new AllPermission())` on your security manager before setting it? Does it help if you do `Class.forName(" java.lang.ClassLoader$1")` before setting it? if you set a breakpoint in constructor `ClassCircularityError(String)` where does the stack trace point to? What classes is it loading then?

**Comment by trask** [comment]
@alvinhom are you still seeing this issue? it's definitely something we'd like to investigate further, if you can answer @laurit's questions above it would be really helpful, thx!

**Comment by alvinhom** [comment]
I have reproduce this issue with a very simple class.

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

public class BB {

    private static Logger logger = LogManager.getLogger(BB.class);

    public static void main(String[] args) throws Throwable {
        if (System.getSecurityManager() == null) {
            System.setSecurityManager(new TestSecurityManager());
        }
        logger.info("hello");
    }
}

mport java.io.FilePermission;
import java.net.SocketPermission;
import java.security.AccessControlContext;
import java.security.BasicPermission;
import java.security.Permission;

import javax.management.MBeanPermission;
import javax.management.MBeanTrustPermission;

public final class TestSecurityManager extends SecurityManager {
    @Override
    public final void checkPermission(Permission perm)
    {
        if (perm instanceof BasicPermission || perm instanceof SocketPermission || perm instanceof FilePermission || perm instanceof MBeanPermission)
        {
            return;
        } else {
            super.checkPermission(perm);
        }
    }

    @Override
    public final void checkPermission(Permission perm, Object context) {
        if (context instanceof AccessControlContext && perm instanceof MBeanTrustPermission) {
            return;
        }
        super.checkPermission(perm);
    }

}


Compile this with a log4j jar file and run it with the agent.  I get the following error:

Exception in thread "Logging-Cleaner" java.lang.ClassCircularityError: java/lang/ClassLoader$1
        at TestSecurityManager.checkPermission(TestSecurityManager.java:14)
        at java.logging/java.util.logging.LogManager.checkPermission(LogManager.java:2432)
        at java.logging/java.util.logging.LogManager.reset(LogManager.java:1415)
        at java.logging/java.util.logging.LogManager$Cleaner.run(LogManager.java:282)
Caught exception class java.lang.ClassCircularityError logging exception class java.lang.ClassCircularityError
java.lang.ClassCircularityError: java/lang/ClassLoader$1
        at TestSecurityManager.checkPermission(TestSecurityManager.java:14)
        at java.base/java.lang.SecurityManager.checkPropertiesAccess(SecurityManager.java:1034)
        at java.base/java.lang.System.getProperties(System.java:715)
        at org.apache.logging.log4j.util.PropertiesUtil$Environment.hasSystemProperty(PropertiesUtil.java:484)
        at org.apache.logging.log4j.util.PropertiesUtil$Environment.get(PropertiesUtil.java:497)
        at org.apache.logging.log4j.util.PropertiesUtil$Environment.access$200(PropertiesUtil.java:422)
        at org.apache.logging.log4j.util.PropertiesUtil.getStringProperty(PropertiesUtil.java:370)
        at org.apache.logging.log4j.util.PropertiesUtil.getBooleanProperty(PropertiesUtil.java:155)
        at org.apache.logging.log4j.status.StatusLogger.isDebugPropertyEnabled(StatusLogger.java:120)
        at org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:407)
        at org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:329)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1906)
        at org.apache.logging.log4j.spi.AbstractLogger.debug(AbstractLogger.java:397)
        at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:311)
        at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$RegisteredCancellable.run(DefaultShutdownCallbackRegistry.java:109)
        at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
        at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-1" java.lang.ClassCircularityError: java/lang/ClassLoader$1
        at TestSecurityManager.checkPermission(TestSecurityManager.java:14)
        at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1066)
        at java.base/java.lang.System.getProperty(System.java:810)
        at io.opentelemetry.javaagent.slf4j.impl.SimpleLoggerConfiguration.getStringProperty(SimpleLoggerConfiguration.java:138)
        at io.opentelemetry.javaagent.slf4j.impl.SimpleLoggerConfiguration.getStringProperty(SimpleLoggerConfiguration.java:126)
        at io.opentelemetry.javaagent.slf4j.impl.SimpleLogger.recursivelyComputeLevelString(SimpleLogger.java:231)
        at io.opentelemetry.javaagent.slf4j.impl.SimpleLogger.<init>(SimpleLogger.java:217)
        at io.opentelemetry.javaagent.slf4j.impl.SimpleLoggerFactory.getLogger(SimpleLoggerFactory.java:56)
        at io.opentelemetry.javaagent.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
        at io.opentelemetry.javaagent.bootstrap.PatchLogger.<init>(PatchLogger.java:43)
        at io.opentelemetry.javaagent.bootstrap.PatchLogger.getLogger(PatchLogger.java:35)
        at io.opentelemetry.exporter.otlp.internal.grpc.ManagedChannelUtil.<clinit>(ManagedChannelUtil.java:30)
        at io.opentelemetry.exporter.otlp.internal.grpc.DefaultGrpcExporter.shutdown(DefaultGrpcExporter.java:140)
        at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter.shutdown(OtlpGrpcSpanExporter.java:75)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.lambda$shutdown$2(BatchSpanProcessor.java:271)
        at io.opentelemetry.sdk.common.CompletableResultCode.whenComplete(CompletableResultCode.java:126)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.shutdown(BatchSpanProcessor.java:268)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.access$200(BatchSpanProcessor.java:125)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.shutdown(BatchSpanProcessor.java:110)
        at io.opentelemetry.sdk.trace.MultiSpanProcessor.shutdown(MultiSpanProcessor.java:68)
        at io.opentelemetry.sdk.trace.TracerSharedState.shutdown(TracerSharedState.java:103)
        at io.opentelemetry.sdk.trace.SdkTracerProvider.shutdown(SdkTracerProvider.java:115)
        at io.opentelemetry.sdk.trace.SdkTracerProvider.close(SdkTracerProvider.java:143)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by alvinhom** [comment]
If I add the line with Class.forName("java.lang.ClassLoader$1") before setting the SecurityManager, then it seems to work:

    public static void main(String[] args) throws Throwable {
        if (System.getSecurityManager() == null) {
            Class.forName("java.lang.ClassLoader$1");
            System.setSecurityManager(new TestSecurityManager());
        }
        logger.info("hello");
    }
