### ISSUE TITLE
Guice ServletModule triggers an exception

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-java-instrumentation#340]
Currently, binding [guice](https://github.com/google/guice/wiki/ServletModule) to a ServletModule triggers a runtime error.  However, running with `-Xverify:none` will suppress the error.

Stack trace included below. Looks like the important part may be "Type 'javax/ws/rs/core/Response' (current frame, locals[2]) is not assignable to 'io/opentelemetry/auto/instrumentation/api/SpanWithScope'"

```
20/04/21 10:36:48,548 INFO [main] Server - jetty-9.2.26.v20180806
20/04/21 10:36:48,885 WARN [main] AbstractLifeCycle - FAILED o.e.j.s.ServletContextHandler@319c1d{/,null,STARTING}: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Unable to method intercept: com.XXXX.XXXX.connector_api.RESTIndexResource
  at com.XXXX.XXXX.connector_api.ConnectorServletModule.configureServlets(ConnectorServletModule.java:42)
Caused by: java.lang.IllegalStateException: Unable to load cache item
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:294)
	at com.google.inject.internal.cglib.proxy.$Enhancer.createHelper(Enhancer.java:480)
	at com.google.inject.internal.cglib.proxy.$Enhancer.createClass(Enhancer.java:337)
	at com.google.inject.internal.ProxyFactory$ProxyConstructor.<init>(ProxyFactory.java:253)
	at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:175)
	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:94)
	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30)
	at com.google.inject.internal.ConstructorInjectorStore$
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Unable to method intercept: com.XXXX.XXXX.connector_api.RESTIndexResource
  at com.XXXX.XXXX.connector_api.ConnectorServletModule.configureServlets(ConnectorServletModule.java:42)
Caused by: java.lang.IllegalStateException: Unable to load cache item
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:294)
	at com.google.inject.internal.cglib.proxy.$Enhancer.createHelper(Enhancer.java:480)
	at com.google.inject.internal.cglib.proxy.$Enhancer.createClass(Enhancer.java:337)
	at com.google.inject.internal.ProxyFactory$ProxyConstructor.<init>(ProxyFactory.java:253)
	at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:175)
	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:94)
	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:34)
	at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:54)
	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155)
	at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:592)
	at com.google.inject.internal.AbstractBindingProcessor$Processor.initializeBinding(AbstractBindingProcessor.java:173)
	at com.google.inject.internal.AbstractBindingProcessor$Processor.lambda$scheduleInitialization$0(AbstractBindingProcessor.java:160)
	at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:124)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at com.XXXX.XXXX.utils.Config.getInjector(Config.java:40)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.XXXX.XXXX.utils.RestConnectorAPIApp.start(RestConnectorAPIApp.java:268)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.daemon.support.DaemonLoader.start(DaemonLoader.java:243)
Caused by: java.lang.VerifyError: Stack map does not match the one at exception handler 172
Exception Details:
  Location:
    com/XXXX/XXXX/connector_api/RESTIndexResource$$EnhancerByGuice$$3de995c5.submitToIndex(Lcom/XXXX/common/DocumentLineItems;)Ljavax/ws/rs/core/Response; @172: astore
  Reason:
    Type 'javax/ws/rs/core/Response' (current frame, locals[2]) is not assignable to 'io/opentelemetry/auto/instrumentation/api/SpanWithScope' (stack map, locals[2])
  Current Frame:
    bci: @160
    flags: { }
    locals: { 'com/XXXX/XXXX/connector_api/RESTIndexResource$$EnhancerByGuice$$3de995c5', 'com/XXXX/common/DocumentLineItems', 'javax/ws/rs/core/Response', 'com/XXXX/XXXX/connector_api/RESTIndexResource$$EnhancerByGuice$$3de995c5', 'com/XXXX/common/DocumentLineItems' }
    stack: { 'java/lang/Throwable' }
  Stackmap Frame:
    bci: @172
    flags: { }
    locals: { 'com/XXXX/XXXX/connector_api/RESTIndexResource$$EnhancerByGuice$$3de995c5', 'com/XXXX/common/DocumentLineItems', 'io/opentelemetry/auto/instrumentation/api/SpanWithScope' }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0x0000000: b201 2eb9 0134 0100 4db2 012e 1301 36b9
    0x0000010: 013a 0200 b901 3f01 004e b201 432d 2c2a
    0x0000020: b601 4712 0212 bd04 bd00 b859 0313 0149
    0x0000030: 53b6 014d b601 51b2 0143 2db6 0155 57bb
    0x0000040: 0157 592d 2db8 015d b701 60a7 0018 1301
    0x0000050: 62b8 0168 5f13 016a 5fb9 0170 0300 a700
    0x0000060: 0457 014d 2a4e 2b3a 042d b400 4459 c700
    0x0000070: 0c57 2db8 0048 2db4 0044 59c6 001e 2db2
    0x0000080: 004a 04bd 004c 5903 1904 53b2 004e b900
    0x0000090: 5405 00c0 0056 a700 0f2d 1904 b700 424d
    0x00000a0: 572c a700 034e 013a 04a7 0007 3a04 014e
    0x00000b0: 2cb6 0173 3a05 1904 c600 25b2 0143 1905
    0x00000c0: 1904 b601 7757 b201 4319 05b6 017a 5719
    0x00000d0: 05b9 017f 0100 2cb6 0182 a700 8d01 3a06
    0x00000e0: 04bd 004c 5903 2b53 3a07 1907 be36 0803
    0x00000f0: 3609 1509 1508 a200 2219 0715 0932 3a0a
    0x0000100: 190a c101 8499 000d 190a c001 843a 06a7
    0x0000110: 0009 8409 01a7 ffdd 1906 c600 2219 06b9
    0x0000120: 0189 0100 9900 1813 0184 1301 7cb8 018f
    0x0000130: 1906 1905 b901 9503 00a7 0013 b201 4319
    0x0000140: 05b6 017a 5719 05b9 017f 0100 2cb6 0182
    0x0000150: a700 1713 0162 b801 685f 1301 6a5f b901
    0x0000160: 7003 00a7 0004 5719 04c6 0006 1904 bf2d
    0x0000170: b0
  Exception Handler Table:
    bci [0, 78] => handler: 78
    bci [105, 165] => handler: 172
    bci [176, 339] => handler: 339
    bci [78, 94] => handler: 97
    bci [339, 355] => handler: 358
  Stackmap Table:
    same_locals_1_stack_item_extended(@78,Object[#292])
    same_locals_1_stack_item_frame(@97,Object[#292])
    same_frame(@98)
    same_locals_1_stack_item_frame(@99,Object[#343])
    append_frame(@100,Object[#343])
    append_frame(@105,Object[#2],Object[#329])
    same_locals_1_stack_item_frame(@122,Object[#80])
    same_locals_1_stack_item_frame(@153,Object[#80])
    full_frame(@165,{Object[#2],Object[#329],Object[#343]},{Object[#86]})
    same_locals_1_stack_item_frame(@172,Object[#292])
    append_frame(@176,Object[#86],Object[#292])
    append_frame(@221,Object[#380])
    full_frame(@242,{Object[#2],Object[#329],Object[#343],Object[#86],Object[#292],Object[#380],Object[#388],Object[#389],Integer,Integer},{})
    same_frame(@274)
    chop_frame(@280,3)
    same_frame(@316)
    same_frame(@332)
    full_frame(@339,{Object[#2],Object[#329],Object[#343],Object[#86],Object[#292]},{Object[#292]})
    same_locals_1_stack_item_frame(@358,Object[#292])
    same_frame(@359)
    same_frame(@367)

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.google.inject.internal.cglib.core.$ReflectUtils.defineClass(ReflectUtils.java:467)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:339)
	at com.google.inject.internal.cglib.proxy.$Enhancer.generate(Enhancer.java:492)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
	... 52 more
```

**Comment by trask** [comment]
@tedsuo Thanks for reporting this!

I'm trying to build a repro here: https://github.com/trask/auto-instr-guice-issue

A couple of questions:
* What JAX-RS framework (and version) is being used?
* What version Guice is being used?
* What version of Java is being used?

Also, are you able to post the source code for this method, to help me build a similar repro?
com/XXXX/XXXX/connector_api/RESTIndexResource.submitToIndex(Lcom/XXXX/common/DocumentLineItems;)Ljavax/ws/rs/core/Response;

Another option for debugging this is to run with `-Dnet.bytebuddy.dump=some/folder` and it will dump all the class files that are transformed, and then post the class file that triggers the `VerifyError`.

If the source/class files cannot be posted publicly but can be shared privately, you can upload them here: https://www.dropbox.com/request/r3m2ZS8ZVMkMq7nzHbHg

**Comment by trask** [comment]
Pinging @tedsuo

**Comment by tedsuo** [comment]
Sorry @trask, missed this! I'll get back to you with the details.

**Comment by tedsuo** [comment]
Here's the version info I was able to get today; I will see about getting the source code:
```
Jaxrs Jersey 1.19
Guice 3.0 guice persist 4.0 (tried guice 4.2.3 )
Java 8
```

**Comment by trask** [comment]
Hey @tedsuo, do you still have access to this repro? Can you try with the latest release `0.6.0`?

If the issue persists, run with -Dnet.bytebuddy.dump=some/folder and it will dump all the class files that are transformed, and then post the class file that triggers the VerifyError.

If the source/class files cannot be posted publicly but can be shared privately, you can upload them here: https://www.dropbox.com/request/r3m2ZS8ZVMkMq7nzHbHg

**Comment by trask** [comment]
Closing, but please comment here if you are able to get hold of this info, and we will re-open and investigate further.
