### ISSUE TITLE
java.lang.ClassNotFoundException: io/opentelemetry/javaagent/shaded/instrumentation/grpc/v1_6/GrpcNetAttributesExtractor

### ISSUE THREAD

**Issue by goto1134** [open-telemetry/opentelemetry-java-instrumentation#3518]
**Describe the bug**
I get the following exception:
```
[otel.javaagent 2021-07-07 14:45:13:595 +0300] [main] WARN io.opentelemetry.javaagent.instrumentation.api.instrumenter.ReflectionPeerServiceAttributesExtractorFactory - Could not add PeerServiceAttributesExtractor wrapping io.opentelemetry.javaagent.shaded.instrumentation.grpc.v1_6.GrpcNetAttributesExtractor
java.lang.ClassNotFoundException: io/opentelemetry/javaagent/shaded/instrumentation/grpc/v1_6/GrpcNetAttributesExtractor
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at io.opentelemetry.javaagent.instrumentation.api.instrumenter.ReflectionPeerServiceAttributesExtractorFactory.create(ReflectionPeerServiceAttributesExtractorFactory.java:26)
	at io.opentelemetry.javaagent.instrumentation.api.instrumenter.PeerServiceAttributesExtractor.createUsingReflection(PeerServiceAttributesExtractor.java:60)
	at io.opentelemetry.javaagent.instrumentation.grpc.v1_6.GrpcSingletons.<clinit>(GrpcSingletons.java:38)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:505)
	at ru.tinkoff.helicopter.core.services.executor.configuration.GprcEngineChannelConfiguration.managedChannelBuilder(GprcEngineChannelConfiguration.java:22)
	at ru.tinkoff.helicopter.core.services.executor.configuration.GprcEngineChannelConfiguration$$EnhancerBySpringCGLIB$$d625eaf9.CGLIB$managedChannelBuilder$0(<generated>)
	at ru.tinkoff.helicopter.core.services.executor.configuration.GprcEngineChannelConfiguration$$EnhancerBySpringCGLIB$$d625eaf9$$FastClassBySpringCGLIB$$7bd67df7.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at ru.tinkoff.helicopter.core.services.executor.configuration.GprcEngineChannelConfiguration$$EnhancerBySpringCGLIB$$d625eaf9.managedChannelBuilder(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	at ...
```
**Steps to reproduce**
Run a project with grpc-server

**What did you expect to see?**
No exceptions

**What did you see instead?**
an exception

**What version are you using?**
opentelemetry-bom 1.3.0 
opentelemetry-javaagent 1.3.1

**Comment by goto1134** [comment]
it actually duplicates https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3445
