### ISSUE TITLE
Jaeger gRPC Exporter enabled but opentelemetry-exporter-jaeger not found on classpath

### ISSUE THREAD

**Issue by chengtangzheng2021** [open-telemetry/opentelemetry-java-instrumentation#3641]
**Describe the bug**
of verion 1.3, 1.3.1 and 1.4.0, set OTEL_TRACES_EXPORTER=jaeger, got opentelemetry-exporter-jaeger not found on classpath,
The same is of set set OTEL_TRACES_EXPORTER=otlp
**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.
version 1.2.0 and 1.1.0 are all working well, when upgrade to 1.30, 1.3.1, the same code is not working.
**What did you see instead?**
A clear and concise description of what you saw instead.
at app start got:
021-07-20 18:49:44:223 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: null
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR ERROR io.opentelemetry.javaagent.OpenTelemetryAgent
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR java.lang.reflect.InvocationTargetException
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at java.lang.reflect.Method.invoke(Method.java:498)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:40)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:51)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:44)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at java.lang.reflect.Method.invoke(Method.java:498)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR Caused by: io.opentelemetry.sdk.autoconfigure.ConfigurationException: Jaeger gRPC Exporter enabled but opentelemetry-exporter-jaeger not found on classpath. Make sure to add it as a dependency to enable this feature.
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at io.opentelemetry.sdk.autoconfigure.ClasspathUtil.checkClassExists(ClasspathUtil.java:15)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureJaeger(SpanExporterConfiguration.java:107)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureExporter(SpanExporterConfiguration.java:45)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:51)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:47)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installAgentTracer(OpenTelemetryInstaller.java:58)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.beforeAgent(OpenTelemetryInstaller.java:39)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at io.opentelemetry.javaagent.tooling.AgentInstaller.runBeforeAgentListeners(AgentInstaller.java:181)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:118)
   2021-07-20T14:49:44.31-0400 [APP/PROC/WEB/1] ERR     at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:96)
**What version are you using?**
(e.g., `v0.9.0`, `393e4a2`, etc)

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6")
OS: (e.g., "Ubuntu 20.04")
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**

**Comment by jkwatson** [comment]
Make sure you're using the `opentelemetry-javaagent-all.jar` jar, not just the `opentelemetry-javaagent.jar` Only the `-all` contains all the extra goodies like exporters.

**Comment by chengtangzheng2021** [comment]
<dependency>
			<groupId>io.opentelemetry.javaagent</groupId>
			<artifactId>opentelemetry-javaagent</artifactId>
			<version>1.4.0</version>
		</dependency>

**Comment by jkwatson** [comment]
There was a bug that too much was being bundled into the jar until very recently.

**Comment by chengtangzheng2021** [comment]
version 1.3.0 said made otlp and jaeger exporter's memory usage greatly reduced, eager to try new version, now only can keep using version 1.2.0 
I looked at the source code, the exporter class is there, but it said not find it.

**Comment by chengtangzheng2021** [comment]
java implementation is much better than python implementation, it is the best, just found this issue

**Comment by jkwatson** [comment]
Have you tried what I suggested? Using the opentelemetry-javaagent-all artifact?

**Comment by chengtangzheng2021** [comment]
how to specify that in java dependency?

**Comment by chengtangzheng2021** [comment]
just hard code the path of opentelemetry-javaagent-all ,
The error is not there, the app got started.

**Comment by chengtangzheng2021** [comment]
<dependency>
		<groupId>io.opentelemetry.javaagent</groupId>
		<artifactId>opentelemetry-javaagent</artifactId>
		<version>1.4.0</version>
	</dependency>

**Comment by jkwatson** [comment]
the artifact id *must* be `opentelemetry-javaagent-all`
It is strongly discouraged to pull down the javaagent as a maven dependency, however. You don't want it to be on your classpath, but only specified via the `-javaagent` command line option.

**Comment by laurit** [comment]
Try adding all classifier
```
<dependency>
    <groupId>io.opentelemetry.javaagent</groupId>
    <artifactId>opentelemetry-javaagent</artifactId>
    <version>1.4.0</version>
    <classifier>all</classifier>
</dependency>
```

**Comment by chengtangzheng2021** [comment]
Thanks Laurit,
You posted is working.
with maven dependency, I deployed javaagent to PCF and K8s
Thanks jkwatson for your so many responses

**Comment by jkwatson** [comment]
I had forgotten it was published under a separate classifier! Thanks, @laurit for catching that!
