### ISSUE TITLE
ClassNotFoundException: io/opentelemetry/javaagent/shaded/instrumentation/grpc/v1_6/GrpcNetAttributesExtractor

### ISSUE THREAD

**Issue by haingo-kenshjn** [open-telemetry/opentelemetry-java-instrumentation#3654]
**Describe the bug**
When working with opentelemetry-java-instrumentation and stared my service, found this error. Could anyone help take a look at the rootcause for it 

Version: 1.3.1

```
WARN io.opentelemetry.javaagent.instrumentation.api.instrumenter.ReflectionPeerServiceAttributesExtractorFactory - Could not add PeerServiceAttributesExtractor wrapping io.opentelemetry.javaagent.shaded.instrumentation.grpc.v1_6.GrpcNetAttributesExtractor
java.lang.ClassNotFoundException: io/opentelemetry/javaagent/shaded/instrumentation/grpc/v1_6/GrpcNetAttributesExtractor
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at io.opentelemetry.javaagent.instrumentation.api.instrumenter.ReflectionPeerServiceAttributesExtractorFactory.create(ReflectionPeerServiceAttributesExtractorFactory.java:26)
	at io.opentelemetry.javaagent.instrumentation.api.instrumenter.PeerServiceAttributesExtractor.createUsingReflection(PeerServiceAttributesExtractor.java:60)
	at io.opentelemetry.javaagent.instrumentation.grpc.v1_6.GrpcSingletons.<clinit>(GrpcSingletons.java:38)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:404)
	at io.vertx.grpc.VertxChannelBuilder.build(VertxChannelBuilder.java:260)
	at api.modules.ServiceBinder.messagingGroupGrpcChannel(ServiceBinder.java:176)
	at api.modules.ServiceBinder$$FastClassByGuice$$b8dc32ae.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:402)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:402)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:402)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050)
	at com.axon.hermod.api.Main.main(Main.java:41)
```

**Comment by laurit** [comment]
This has already been fixed, though it is safe to ignore it.
