### ISSUE TITLE
Fix context leaks in existing tests

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3916]
This is a tracking issue to fix context leaks in existing tests for all instrumentations that currently have to disable the strict context check.

- [ ] akka-http-10.0/javaagent/build.gradle.kts
- [ ] aws-sdk/aws-sdk-1.11/javaagent-unit-tests/build.gradle.kts 
- [ ] finatra-2.9/javaagent/build.gradle.kts 
- [ ] grpc-1.6/javaagent/build.gradle.kts 
- [ ] kotlinx-coroutines/javaagent/build.gradle.kts 
- [ ] kubernetes-client-7.0/javaagent/build.gradle.kts 
- [ ] okhttp/okhttp-3.0/javaagent/build.gradle.kts

**Comment by trask** [comment]
Starting to track associated errors in case they are useful:
```
Elasticsearch6NodeClientTest > test elasticsearch get[0] FAILED	
    java.lang.AssertionError: Thread [elasticsearch[default node name][masterService#updateTask][T#1]] opened a scope of {opentelemetry-trace-span-key=RecordEventsReadableSpan{traceId=1551d3e6b043be93c1b2dbd4457d9ba9, spanId=620f959ffafc836a, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, name=DeleteIndexAction, kind=CLIENT, attributes=AttributesMap{data={db.system=elasticsearch, elasticsearch.request.indices=test-index, elasticsearch.action=DeleteIndexAction, elasticsearch.request=DeleteIndexRequest, db.operation=DeleteIndexAction}, capacity=128, totalAddedValues=5}, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1629767596124752000, endEpochNanos=1629767596169849223}, opentelemetry-traces-span-key-client=RecordEventsReadableSpan{traceId=1551d3e6b043be93c1b2dbd4457d9ba9, spanId=620f959ffafc836a, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, name=DeleteIndexAction, kind=CLIENT, attributes=AttributesMap{data={db.system=elasticsearch, elasticsearch.request.indices=test-index, elasticsearch.action=DeleteIndexAction, elasticsearch.request=DeleteIndexRequest, db.operation=DeleteIndexAction}, capacity=128, totalAddedValues=5}, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1629767596124752000, endEpochNanos=1629767596169849223}, thread-propagation-locations=[io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug$Propagation@79bf0709, io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug$Propagation@1c0ecb4a, io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug$Propagation@77f12823, io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug$Propagation@5fb2b87c, io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug$Propagation@2ec7a995, io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug$Propagation@647e7df7, io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug$Propagation@36fc70c8, io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug$Propagation@5cfd2a98, io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug$Propagation@53627011, io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug$Propagation@7bf1362d]} here:	
        at io.opentelemetry.javaagent.instrumentation.api.concurrent.TaskAdviceHelper.makePropagatedContextCurrent(TaskAdviceHelper.java:27)	
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:198)	
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)	
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)	
        at java.base/java.lang.Thread.run(Thread.java:829)	
```

**Comment by trask** [comment]
```
Mongo4ReactiveClientTest > test create collection FAILED	
    java.lang.AssertionError: Thread [AsyncGetter-1-thread-1] opened a scope of {opentelemetry-trace-span-key=RecordEventsReadableSpan{traceId=342add72e4a4ec95c7cc41621f324771, spanId=4a73de3e7903d89d, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, name=parent, kind=INTERNAL, attributes=null, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1629771066420432133, endEpochNanos=1629771067201377940}, otel-context={}, thread-propagation-locations=[io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug$Propagation@43cae8d3]} here:	
        at io.opentelemetry.javaagent.instrumentation.api.concurrent.TaskAdviceHelper.makePropagatedContextCurrent(TaskAdviceHelper.java:27)	
        at io.opentelemetry.javaagent.instrumentation.api.concurrent.RunnableWrapper.run(RunnableWrapper.java:38)	
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)	
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)	
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)	
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)	
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jaydeluca** [comment]
ZIO is the only one left, and that one has some history: https://github.com/open-telemetry/opentelemetry-java/issues/5303

@trask do you think it's worth leaving this open for that one, or could we consider this complete?

**Comment by jaydeluca** [comment]
we discussed this in the SIG meeting today. We'll leave this issue open for a bit as we keep an eye out for any flakyness from re-enabling the strict context checking. 

A new issue has been opened to focus on what to do about the remaining module (ZIO): #14938
