### ISSUE TITLE
Upgrade to spring-boot 2.5.x

### ISSUE THREAD

**Issue by davidkarlsen** [open-telemetry/opentelemetry-java-instrumentation#4025]
**Is your feature request related to a problem? Please describe.**
Upgrade to latest spring-boot, currently 2.5.x

**Describe the solution you'd like**
Support latest boot version

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by davidkarlsen** [comment]
Breaking changes (and in general changes) are documented at https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes

I tried adding

```
  <dependency>
      <groupId>io.opentelemetry.instrumentation</groupId>
      <artifactId>opentelemetry-jaeger-exporter-starter</artifactId>
      <version>1.5.2-alpha</version>
```
along with the jaeger-exporter, but it fails with [1]


[1]
```
04.1936169Z 2021-08-30 15:38:04,137 [main][][][][][][][] WARN org.springframework.context.annotation.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'otelJaegerSpanExporter' defined in class path resource [io/opentelemetry/instrumentation/spring/autoconfigure/exporters/jaeger/JaegerSpanExporterAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporter]: Factory method 'otelJaegerSpanExporter' threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder
2021-08-30T13:38:04.1948478Z 2021-08-30 15:38:04,147 [main][][][][][][][] INFO org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener - 
2021-08-30T13:38:04.1951181Z 
2021-08-30T13:38:04.1952237Z Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-08-30T13:38:04.1954164Z 2021-08-30 15:38:04,152 [main][][][][][][][] ERROR org.springframework.boot.SpringApplication - Application run failed
2021-08-30T13:38:04.1961728Z org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'otelJaegerSpanExporter' defined in class path resource [io/opentelemetry/instrumentation/spring/autoconfigure/exporters/jaeger/JaegerSpanExporterAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporter]: Factory method 'otelJaegerSpanExporter' threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder
2021-08-30T13:38:04.2003877Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
2021-08-30T13:38:04.2008862Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
2021-08-30T13:38:04.2014319Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
2021-08-30T13:38:04.2021608Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
2021-08-30T13:38:04.2028427Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
2021-08-30T13:38:04.2033762Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
2021-08-30T13:38:04.2037601Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
2021-08-30T13:38:04.2042604Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
2021-08-30T13:38:04.2046552Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
2021-08-30T13:38:04.2050230Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
2021-08-30T13:38:04.2054078Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
2021-08-30T13:38:04.2062200Z 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
2021-08-30T13:38:04.2066776Z 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
2021-08-30T13:38:04.2069358Z 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
2021-08-30T13:38:04.2071249Z 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
2021-08-30T13:38:04.2073022Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
2021-08-30T13:38:04.2075950Z 	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:123)
2021-08-30T13:38:04.2081127Z 	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
2021-08-30T13:38:04.2111598Z 	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
2021-08-30T13:38:04.2115755Z 	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
2021-08-30T13:38:04.2121181Z 	at org.springframework.test.context.junit.jupiter.SpringExtension.getApplicationContext(SpringExtension.java:283)
2021-08-30T13:38:04.2127504Z 	at org.springframework.test.context.junit.jupiter.SpringExtension.resolveParameter(SpringExtension.java:269)
2021-08-30T13:38:04.2130799Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:216)
2021-08-30T13:38:04.2133405Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:183)
2021-08-30T13:38:04.2135756Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:74)
2021-08-30T13:38:04.2141402Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:342)
2021-08-30T13:38:04.2145770Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:289)
2021-08-30T13:38:04.2150212Z 	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
2021-08-30T13:38:04.2154979Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:267)
2021-08-30T13:38:04.2160382Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:259)
2021-08-30T13:38:04.2162553Z 	at java.base/java.util.Optional.orElseGet(Optional.java:362)
2021-08-30T13:38:04.2164618Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:258)
2021-08-30T13:38:04.2169229Z 	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
2021-08-30T13:38:04.2174325Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:101)
2021-08-30T13:38:04.2180823Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-30T13:38:04.2185981Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:100)
2021-08-30T13:38:04.2191218Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:65)
2021-08-30T13:38:04.2195811Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:111)
2021-08-30T13:38:04.2200620Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-30T13:38:04.2205459Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:111)
2021-08-30T13:38:04.2209753Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:79)
2021-08-30T13:38:04.2212505Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2021-08-30T13:38:04.2217888Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2021-08-30T13:38:04.2224497Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2021-08-30T13:38:04.2229321Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-30T13:38:04.2234077Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2021-08-30T13:38:04.2238083Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2021-08-30T13:38:04.2241800Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2021-08-30T13:38:04.2246383Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-30T13:38:04.2251358Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2021-08-30T13:38:04.2255983Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2021-08-30T13:38:04.2258940Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2021-08-30T13:38:04.2264628Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2021-08-30T13:38:04.2271501Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2021-08-30T13:38:04.2276128Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-30T13:38:04.2283091Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2021-08-30T13:38:04.2286817Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2021-08-30T13:38:04.2290646Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2021-08-30T13:38:04.2295321Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-30T13:38:04.2300395Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2021-08-30T13:38:04.2305057Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2021-08-30T13:38:04.2311536Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2021-08-30T13:38:04.2319268Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2021-08-30T13:38:04.2324769Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2021-08-30T13:38:04.2329979Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
2021-08-30T13:38:04.2334731Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
2021-08-30T13:38:04.2339724Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
2021-08-30T13:38:04.2345425Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
2021-08-30T13:38:04.2351087Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
2021-08-30T13:38:04.2355158Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
2021-08-30T13:38:04.2359792Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
2021-08-30T13:38:04.2363897Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
2021-08-30T13:38:04.2369147Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
2021-08-30T13:38:04.2374114Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
2021-08-30T13:38:04.2378374Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
2021-08-30T13:38:04.2381922Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2021-08-30T13:38:04.2384757Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
2021-08-30T13:38:04.2387489Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
2021-08-30T13:38:04.2394828Z Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporter]: Factory method 'otelJaegerSpanExporter' threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder
2021-08-30T13:38:04.2402744Z 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
2021-08-30T13:38:04.2408337Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
2021-08-30T13:38:04.2411696Z 	... 77 common frames omitted
2021-08-30T13:38:04.2413972Z Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder
2021-08-30T13:38:04.2418238Z 	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForTarget(NettyChannelProvider.java:42)
2021-08-30T13:38:04.2431629Z 	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForTarget(NettyChannelProvider.java:23)
2021-08-30T13:38:04.2435314Z 	at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76)
2021-08-30T13:38:04.2440121Z 	at io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporterBuilder.build(JaegerGrpcSpanExporterBuilder.java:93)
2021-08-30T13:38:04.2449567Z 	at io.opentelemetry.instrumentation.spring.autoconfigure.exporters.jaeger.JaegerSpanExporterAutoConfiguration.otelJaegerSpanExporter(JaegerSpanExporterAutoConfiguration.java:43)
2021-08-30T13:38:04.2461122Z 	at io.opentelemetry.instrumentation.spring.autoconfigure.exporters.jaeger.JaegerSpanExporterAutoConfiguration$$EnhancerBySpringCGLIB$$8706f831.CGLIB$otelJaegerSpanExporter$0(<generated>)
2021-08-30T13:38:04.2470798Z 	at io.opentelemetry.instrumentation.spring.autoconfigure.exporters.jaeger.JaegerSpanExporterAutoConfiguration$$EnhancerBySpringCGLIB$$8706f831$$FastClassBySpringCGLIB$$729b19d3.invoke(<generated>)
2021-08-30T13:38:04.2477758Z 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
2021-08-30T13:38:04.2482160Z 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
2021-08-30T13:38:04.2489749Z 	at io.opentelemetry.instrumentation.spring.autoconfigure.exporters.jaeger.JaegerSpanExporterAutoConfiguration$$EnhancerBySpringCGLIB$$8706f831.otelJaegerSpanExporter(<generated>)
2021-08-30T13:38:04.2495898Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-08-30T13:38:04.2499277Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
2021-08-30T13:38:04.2503062Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-08-30T13:38:04.2505837Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2021-08-30T13:38:04.2509837Z 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
2021-08-30T13:38:04.2513379Z 	... 78 common frames omitted
```

**Comment by trask** [comment]
hey @daviddenton, this looks like maybe a version mismatch between `grpc` and `grpc-netty-shaded` dependencies, can you confirm that the versions of those dependencies match in your application, or share your pom/gradle file?

**Comment by daviddenton** [comment]
> hey @daviddenton, this looks like maybe a version mismatch between `grpc` and `grpc-netty-shaded` dependencies, can you confirm that the versions of those dependencies match in your application, or share your pom/gradle file?
Think you've got the wrong David... 😄

**Comment by mateuszrzeszutek** [comment]
Hm, now that I've looked at it we don't publish `opentelemetry-jaeger-exporter-starter`. There's `opentelemetry-jaeger-exporter`, but I think it doesn't include the actual gRPC implementation (@jkwatson @anuraaga please correct me if I'm wrong) - so the reason it's failing might be a missing `grpc` or `grpc-netty-shaded` dependency.

**Comment by trask** [comment]
> Think you've got the wrong David... 😄

oops! cc: @davidkarlsen

**Comment by davidkarlsen** [comment]
https://repo1.maven.org/maven2/io/opentelemetry/instrumentation/opentelemetry-jaeger-exporter-starter/1.5.2-alpha/

> Hm, now that I've looked at it we don't publish `opentelemetry-jaeger-exporter-starter`. There's `opentelemetry-jaeger-exporter`, but I think it doesn't include the actual gRPC implementation (@jkwatson @anuraaga please correct me if I'm wrong) - so the reason it's failing might be a missing `grpc` or `grpc-netty-shaded` dependency.

https://repo1.maven.org/maven2/io/opentelemetry/instrumentation/opentelemetry-jaeger-exporter-starter/1.5.2-alpha/

**Comment by jkwatson** [comment]
yes, you need to provide an grpc transport implementation. grpc-netty-shaded is usually a good option. No idea if that should be included in the dependencies of the starter or not (probably?)

**Comment by davidkarlsen** [comment]
> yes, you need to provide an grpc transport implementation. grpc-netty-shaded is usually a good option. No idea if that should be included in the dependencies of the starter or not (probably?)

It's already there, but not working as can be seen from the stack-traces:

```
[INFO] +- io.opentelemetry.instrumentation:opentelemetry-jaeger-exporter-starter:jar:1.5.2-alpha:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.5.4:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.28:compile
[INFO] |  +- io.opentelemetry.instrumentation:opentelemetry-spring-starter:jar:1.5.2-alpha:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-aop:jar:2.5.4:compile
[INFO] |  |  |  \- org.aspectj:aspectjweaver:jar:1.9.7:compile
[INFO] |  |  +- io.opentelemetry.instrumentation:opentelemetry-spring-boot-autoconfigure:jar:1.5.2-alpha:compile
[INFO] |  |  |  +- io.opentelemetry.instrumentation:opentelemetry-instrumentation-api-annotation-support:jar:1.5.2-alpha:runtime
[INFO] |  |  |  |  +- io.opentelemetry.instrumentation:opentelemetry-instrumentation-api:jar:1.5.2-alpha:runtime
[INFO] |  |  |  |  \- io.opentelemetry:opentelemetry-api-metrics:jar:1.5.0-alpha:compile
[INFO] |  |  |  +- io.opentelemetry.instrumentation:opentelemetry-spring-web-3.1:jar:1.5.2-alpha:runtime
[INFO] |  |  |  +- io.opentelemetry.instrumentation:opentelemetry-spring-webmvc-3.1:jar:1.5.2-alpha:runtime
[INFO] |  |  |  |  +- io.opentelemetry.instrumentation:opentelemetry-servlet-common:jar:1.5.2-alpha:runtime
[INFO] |  |  |  |  \- io.opentelemetry.instrumentation:opentelemetry-servlet-javax-common:jar:1.5.2-alpha:runtime
[INFO] |  |  |  \- io.opentelemetry.instrumentation:opentelemetry-spring-webflux-5.0:jar:1.5.2-alpha:runtime
[INFO] |  |  +- io.opentelemetry:opentelemetry-extension-annotations:jar:1.5.0:compile
[INFO] |  |  +- io.opentelemetry:opentelemetry-api:jar:1.5.0:compile
[INFO] |  |  |  \- io.opentelemetry:opentelemetry-context:jar:1.5.0:compile
[INFO] |  |  +- io.opentelemetry:opentelemetry-exporter-logging:jar:1.5.0:compile
[INFO] |  |  |  \- io.opentelemetry:opentelemetry-sdk-metrics:jar:1.5.0-alpha:compile
[INFO] |  |  \- io.opentelemetry:opentelemetry-sdk:jar:1.5.0:compile
[INFO] |  |     +- io.opentelemetry:opentelemetry-sdk-common:jar:1.5.0:compile
[INFO] |  |     \- io.opentelemetry:opentelemetry-sdk-trace:jar:1.5.0:compile
[INFO] |  +- io.opentelemetry:opentelemetry-exporter-jaeger:jar:1.5.0:compile
[INFO] |  |  +- io.opentelemetry:opentelemetry-semconv:jar:1.5.0-alpha:runtime
[INFO] |  |  +- io.grpc:grpc-protobuf:jar:1.38.0:runtime
[INFO] |  |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  |  +- com.google.api.grpc:proto-google-common-protos:jar:2.0.1:runtime
[INFO] |  |  |  +- io.grpc:grpc-protobuf-lite:jar:1.38.0:runtime
[INFO] |  |  |  +- com.google.errorprone:error_prone_annotations:jar:2.4.0:runtime
[INFO] |  |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.19:runtime
[INFO] |  |  +- io.grpc:grpc-stub:jar:1.38.0:runtime
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:3.17.2:runtime
[INFO] |  |  \- com.google.protobuf:protobuf-java-util:jar:3.17.2:runtime
[INFO] |  |     \- com.google.code.gson:gson:jar:2.8.7:runtime
[INFO] |  \- io.grpc:grpc-netty-shaded:jar:1.30.2:runtime
[INFO] |     \- io.grpc:grpc-core:jar:1.30.2:runtime (version selected from constraint [1.30.2,1.30.2])
[INFO] |        +- io.grpc:grpc-api:jar:1.30.2:compile (version selected from constraint [1.30.2,1.30.2])
[INFO] |        |  \- io.grpc:grpc-context:jar:1.30.2:compile
[INFO] |        +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |        \- io.perfmark:perfmark-api:jar:0.19.0:runtime

```

**Comment by jkwatson** [comment]
hm. weird, with this error, then:  `nested exception is java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder`

**Comment by anuraaga** [comment]
I think you need to apply `grpc-bom` - I see some at 1.38.0 and some at 1.30.2, misaligned gRPC versions generally will fail to classload

**Comment by trask** [comment]
Closing, but please comment if you are still having the issue and we will re-open it!

**Comment by trask** [comment]
Closing, let us know if you are still facing this issue and we'll re-open it.
