### ISSUE TITLE
Jetty instrumentation fails if `jdk.unsupported` module is not available

### ISSUE THREAD

**Issue by brunojcm** [open-telemetry/opentelemetry-java-instrumentation#4096]
**Is your feature request related to a problem? Please describe.**
The current version of `opentelemetry-java-instrumentation` (1.5.3 as of this report) requires the `jdk.unsupported` JDK module to be available at runtime. This is not a sustainable approach.

If `jdk.unsupported` is not present, the following error occurs:

```
2021-09-11 13:21:15.629000 +0000 [main] INFO org.eclipse.jetty.server.Server - Started @9476ms
[otel.javaagent 2021-09-11 13:21:20:451 +0000] [qtp413177525-18] ERROR io.opentelemetry.javaagent.tooling.HelperInjector - Error preparing helpers while processing class org.eclipse.jetty.server.Request for servlet. Failed to inject helper classes into instance jdk.internal.loader.ClassLoaders$AppClassLoader@ea9e141
java.lang.UnsupportedOperationException: Cannot get defined package using reflection: sun.misc.Unsafe
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.getDefinedPackage(ClassInjector.java:445)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:221)
	at io.opentelemetry.javaagent.tooling.HelperInjector.injectClassLoader(HelperInjector.java:247)
	at io.opentelemetry.javaagent.tooling.HelperInjector.lambda$injectHelperClasses$1(HelperInjector.java:195)
	at io.opentelemetry.javaagent.shaded.instrumentation.api.caching.WeakLockFreeCache.computeIfAbsent(WeakLockFreeCache.java:35)
	at io.opentelemetry.javaagent.tooling.HelperInjector.injectHelperClasses(HelperInjector.java:184)
	at io.opentelemetry.javaagent.tooling.HelperInjector.transform(HelperInjector.java:150)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10889)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10827)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10569)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:11292)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:11231)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10769)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(Unknown Source)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.jetty.server.HttpChannel.<init>(HttpChannel.java:111)
	at org.eclipse.jetty.server.HttpChannelOverHttp.<init>(HttpChannelOverHttp.java:67)
	at org.eclipse.jetty.server.HttpConnection.newHttpChannel(HttpConnection.java:140)
	at org.eclipse.jetty.server.HttpConnection.<init>(HttpConnection.java:109)
	at org.eclipse.jetty.server.HttpConnectionFactory.newConnection(HttpConnectionFactory.java:86)
	at org.eclipse.jetty.server.ServerConnector$ServerConnectorManager.newConnection(ServerConnector.java:618)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:386)
	at org.eclipse.jetty.io.ManagedSelector.access$2100(ManagedSelector.java:65)
	at org.eclipse.jetty.io.ManagedSelector$Accept.run(ManagedSelector.java:890)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Describe the solution you'd like**
I would like to be able to run `opentelemetry-java-instrumentation` with a custom built JDK that does NOT include `jdk.unsupported`.

**Describe alternatives you've considered**
I'm currenlty adding `jdk.unsupported` in my `jlink` command, but I need to have a plan to remove those eventually. opentelemetry-java is the most important dependency in my classpath that requires `jdk.unsupported`.

**Comment by brunojcm** [comment]
I found this issue after applying a patch for https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4092 locally.

**Comment by anuraaga** [comment]
@brunojcm Can you try with the latest snapshot? We changed the agent injecting a bit which may have fixed this but not sure.

**Comment by anuraaga** [comment]
Oh but you say you found it locally - does it mean you found it on the latest code?

**Comment by brunojcm** [comment]
Yes, @anuraaga, that's the history of the version I tried:
![image](https://user-images.githubusercontent.com/251695/132971466-5b9dc228-e461-4411-9164-b30ff8e11253.png)

**Comment by brunojcm** [comment]
It seems to me that bytebuddy's `net.bytebuddy.dynamic.loading.ClassInjector` still needs `sun.misc.Unsafe`, but I don't know much about it to be sure.

I tried to find which version of bytebuddy we are using, but it's used in so many places, I'm a bit lost here.

**Comment by brunojcm** [comment]
I'm actually using Ktor/Jetty here, so I gave it another try with Netty, and I got a similar error. Reporter another issue https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4100, but it seems to be a widespread issue (bytebuddy?).

**Comment by brunojcm** [comment]
Thanks!
