### ISSUE TITLE
StackMapTable error with Wowza Streaming Engine

### ISSUE THREAD

**Issue by jantekb** [open-telemetry/opentelemetry-java-instrumentation#4158]
**Describe the bug**
I have added the Java agent to Wowza Streaming Engine and as soon as it starts booting, I am getting the below error:

Error starting: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at com.wowza.wms.bootstrap.Bootstrap.startServer(Bootstrap.java:656)
        at com.wowza.wms.bootstrap.Bootstrap.main(Bootstrap.java:73)
Caused by: java.lang.ClassFormatError: StackMapTable format error: bad offset for Uninitialized in method 'void com.wowza.wms.util.IdleWorkerUtil.run()'
        at com.wowza.wms.util.IdleWorkersUtil.start(IdleWorkersUtil.java:28)
        at com.wowza.wms.vhost.VHost.init(VHost.java:554)
        at com.wowza.wms.vhost.VHostSingleton.init(VHostSingleton.java:62)
        at com.wowza.wms.server.Server.startVHost(Server.java:3802)
        at com.wowza.wms.server.Server.startVHosts(Server.java:4318)
        at com.wowza.wms.server.Server.start(Server.java:1143)
        ... 6 more

**Steps to reproduce**
1) Install Wowza Streaming Engine with trial license
2) Edit the bin/startup.sh file and add the otel java agent 1.5.3
3) Start the server

**What did you expect to see?**
I expected the server to operate as usual, but with the ability to get metrics

**What did you see instead?**
The server did not start up and the above mentioned stacktrace was printed and it exited.

**What version are you using?**
Java version:
Otel version:

**Environment**
INFO server comment - Java Name: OpenJDK 64-Bit Server VM
INFO server comment - Java Vendor: Oracle Corporation
INFO server comment - Java Version: 13.0.2
INFO server comment - Java VM Version: 13.0.2+8
INFO server comment - Java Spec Version: 13
INFO server comment - Java Home: w:\java\jdk-13.0.2
INFO server comment - Java Max Heap Size: 4000MB
INFO server comment - Java Architecture: 64
INFO server comment - Java Locale[user.language]: hu
INFO server comment - Java Locale[user.country]: HU
INFO server comment - Java Locale[user.variant]:
INFO server comment - Java Locale[file.encoding]: Cp1250
INFO server comment - Java Timezone[user.timezone]: UTC
INFO server comment - Java Args[0]: -Duser.timezone=UTC
INFO server comment - Java Args[1]: -javaagent:opentelemetry-javaagent-all.jar
INFO server comment - Java Args[2]: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7777
INFO server comment - Java Args[3]: -Xmx4000M
INFO server comment - Java Args[4]: -XX:+UseG1GC
INFO server comment - Java Args[5]: -XX:MaxGCPauseMillis=100
INFO server comment - Java Args[6]: -XX:SurvivorRatio=1
INFO server comment - Java Args[7]: -Djava.net.preferIPv4Stack=true
INFO server comment - Java Args[8]: -Dcom.sun.management.jmxremote=true
INFO server comment - Java Args[9]: -Dcom.wowza.wms.runmode=standalone
INFO server comment - Java Args[10]: -Dcom.wowza.wms.native.base=win
INFO server comment - Java Args[11]: -Dlog4j.configurationFile=C:\wowza-4.8.13/conf/log4j2-config.xml
INFO server comment - Java Args[12]: -Dcom.wowza.wms.ConfigURL=

**Additional context**
Wowza Streaming Engine uses some bytecode obfuscation technique which might be related to the problem.

**Comment by laurit** [comment]
Reported to bytebuddy https://github.com/raphw/byte-buddy/issues/1113
