### ISSUE TITLE
v1.6.1 crashes when extension project is built with muzzle plugin 0.7.0

### ISSUE THREAD

**Issue by edwardxia** [open-telemetry/opentelemetry-java-instrumentation#4244]
Commit https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/0d0d2ca09b0952340bf7cfeb4aa9b1cdcd423727 in v1.6.1 which rename tons of muzzle related package names causes crash with extensions repository with muzzle plugin 0.7.0, and meanwhile muzzle plugin 0.8.0 is not yet released.

```
Caused by: java.lang.NoClassDefFoundError: io/opentelemetry/javaagent/extension/muzzle/Flag
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
        at java.base/java.lang.Class.getConstructor0(Class.java:3342)
        at java.base/java.lang.Class.getConstructor(Class.java:2151)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:659)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:656)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:667)
        ... 22 more
Caused by: java.lang.ClassNotFoundException: io.opentelemetry.javaagent.extension.muzzle.Flag
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 30 more
```

**Comment by edwardxia** [comment]
I don't understand how a breaking change get into a patch release. I see two ways out:

- Revert this commit and release 1.6.2 ASAP. - This option is probably more appropriate.
- Release muzzle plugin 0.8.0 and clarify that 1.6.1 will need muzzle plugin 0.8.0

**Comment by trask** [comment]
oh no 😞, thanks for reporting this

unfortunately the 1.6.0 tag depended on a gradle-plugins snapshot, which made releasing 1.6.1 really painful. i think the best is to revert everything in the 1.6.x branch and release 1.6.2 which is essentially the same as 1.6.0, and give up on making a patch release for #4191

**Comment by trask** [comment]
oh, and of course we can't just roll back and release 1.6.2 as a copy of 1.6.0, because the problem is that the 1.6.0 tag doesn't build anymore 😭

in the meantime, I've added a warning to the release notes, and posted the warning in the slack channel

**Comment by edwardxia** [comment]
That is unfortunate, but thanks for getting to it quickly!

**Comment by trask** [comment]
1.6.2 is released, please let us know if it resolves the issue for you
