### ISSUE TITLE
Sporadic test failure (15x): AkkaActorTest

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#443]
```
Condition not satisfied:

java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

assert spans.size() == expectedSize
       |     |      |  |
       |     1      |  2
       |            false
       [SpanData{traceId=TraceId{traceId=54aa75ea2461ba7e118a9aa2f13e300c}, spanId=SpanId{spanId=9e7765b988c2941f}, traceFlags=TraceFlags{sampled=true}, traceState=TraceState{entries=[]}, parentSpanId=SpanId{spanId=0000000000000000}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.auto, version=null}, name=parent, kind=INTERNAL, startEpochNanos=1590519095521003064, attributes={}, timedEvents=[], links=[], status=Status{canonicalCode=OK, description=null}, endEpochNanos=1590519095521520153, hasRemoteParent=false, hasEnded=true, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=0}]

	at io.opentelemetry.auto.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:70)
	at io.opentelemetry.auto.test.AgentTestRunner.assertTraces(AgentTestRunner.java:207)
	at AkkaActorTest.akka #testMethod(AkkaActorTest.groovy:26)
Caused by: Assertion failed: 

assert spans.size() == expectedSize
       |     |      |  |
       |     1      |  2
       |            false
       [SpanData{traceId=TraceId{traceId=54aa75ea2461ba7e118a9aa2f13e300c}, spanId=SpanId{spanId=9e7765b988c2941f}, traceFlags=TraceFlags{sampled=true}, traceState=TraceState{entries=[]}, parentSpanId=SpanId{spanId=0000000000000000}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.auto, version=null}, name=parent, kind=INTERNAL, startEpochNanos=1590519095521003064, attributes={}, timedEvents=[], links=[], status=Status{canonicalCode=OK, description=null}, endEpochNanos=1590519095521520153, hasRemoteParent=false, hasEnded=true, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=0}]

	at io.opentelemetry.auto.test.asserts.TraceAssert.assertTrace(TraceAssert.groovy:47)
	at io.opentelemetry.auto.test.asserts.InMemoryExporterAssert.trace(InMemoryExporterAssert.groovy:85)
	at AkkaActorTest.akka #testMethod_closure1(AkkaActorTest.groovy:27)
	at io.opentelemetry.auto.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:52)
	... 2 more
```

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-auto-instr-java/1118/workflows/9ca817ef-8468-4f89-9c7c-4e511ecc7ef2/jobs/9329/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1189/workflows/23ce19da-8893-46fa-98e8-ffa5ae342977/jobs/9817/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1253/workflows/8c174529-2418-46d2-96e9-aa9cfbabaac9/jobs/10255/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1257/workflows/30351823-ad07-43da-81a9-99652e8a00f0/jobs/10289/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1344/workflows/6399a0ab-3ceb-48dd-963e-c60ee43f2257/jobs/10902/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1344/workflows/226c7d71-60eb-45e3-886d-1b7c86f1d3d4/jobs/10906

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1344/workflows/6399a0ab-3ceb-48dd-963e-c60ee43f2257/jobs/10902

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1349/workflows/778e0569-a72c-4b03-93e0-8ef9fbb51d55/jobs/10971/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1479/workflows/762365ca-b6d9-4398-bc52-08b0c5080701/jobs/11773/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1506/workflows/9eee9141-45fe-4655-97be-713ef8bacdaa/jobs/11959/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1573/workflows/68255f11-39b9-4cfb-945f-30334354886a/jobs/12360/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1606/workflows/29a9a8c8-03b5-4db6-851a-aab4b000696e/jobs/12556/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/2016/workflows/cbcaea81-f7e8-4b7d-aa49-61e4e3311489/jobs/14010/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/2023/workflows/a25613a5-7aeb-4874-8ddc-d28906591120/jobs/14044/tests

**Comment by trask** [comment]
Closing per #925
