### ISSUE TITLE
Sporadic test failure (2x): CassandraClientTest

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#445]
```
com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1, use getErrors() for more: localhost/127.0.0.1:39553: com.datastax.oss.driver.api.core.DriverTimeoutException: [s0|control|id: 0xa4d65631, L:/127.0.0.1:54970 - R:localhost/127.0.0.1:39553] init query GET_CLUSTER_NAME: timed out after 500 ms)
	at com.datastax.oss.driver.api.core.AllNodesFailedException.copy(AllNodesFailedException.java:95)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:113)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:336)
	at CassandraClientTest.getSession(CassandraClientTest.groovy:127)
	at CassandraClientTest.test sync(CassandraClientTest.groovy:51)
```

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-auto-instr-java/1125/workflows/46557765-fa72-4c99-9f66-abfa73e3255f/jobs/9374/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/2384/workflows/17f3daee-cb6e-4f51-a39c-8821f991f7fa/jobs/15330

**Comment by trask** [comment]
Closing per #925
