### ISSUE TITLE
Sporadic test failure (3x): JerseyClientTest

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#447]
```
Condition not satisfied:

org.spockframework.runtime.GroovyRuntimeUtil.invokeMethod(GroovyRuntimeUtil.java:171)

assert spans.size() == expectedSize
       |     |      |  |
       |     5      |  4
       |            false
       [SpanData{traceId=TraceId{traceId=490cbdb11ac04f618721ec94c0963b14}, spanId=SpanId{spanId=b3b68c24c636bda5}, traceFlags=TraceFlags{sampled=true}, traceState=TraceState{entries=[]}, parentSpanId=SpanId{spanId=0000000000000000}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.auto.jaxrs-client-2.0, version=null}, name=HTTP GET, kind=CLIENT, startEpochNanos=1590602976514001721, attributes={http.status_code=AttributeValueLong{longValue=200}, http.method=AttributeValueString{stringValue=GET}, http.url=AttributeValueString{stringValue=http://localhost:35805/another-redirect}, net.peer.port=AttributeValueLong{longValue=35805}, net.peer.name=AttributeValueString{stringValue=localhost}}, timedEvents=[], links=[], status=Status{canonicalCode=OK, description=null}, endEpochNanos=1590602976532647985, hasRemoteParent=false, hasEnded=true, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=5}, SpanData{traceId=TraceId{traceId=490cbdb11ac04f618721ec94c0963b14}, spanId=SpanId{spanId=ff1a06505e2703cc}, traceFlags=TraceFlags{sampled=true}, traceState=TraceState{entries=[]}, parentSpanId=SpanId{spanId=b3b68c24c636bda5}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.auto, version=null}, name=test-http-server, kind=SERVER, startEpochNanos=1590602976517001446, attributes={}, timedEvents=[], links=[], status=Status{canonicalCode=OK, description=null}, endEpochNanos=1590602976517204314, hasRemoteParent=true, hasEnded=true, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=0}, SpanData{traceId=TraceId{traceId=490cbdb11ac04f618721ec94c0963b14}, spanId=SpanId{spanId=8883d309a24f4e1d}, traceFlags=TraceFlags{sampled=true}, traceState=TraceState{entries=[]}, parentSpanId=SpanId{spanId=b3b68c24c636bda5}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.auto, version=null}, name=test-http-server, kind=SERVER, startEpochNanos=1590602976522001795, attributes={}, timedEvents=[], links=[], status=Status{canonicalCode=OK, description=null}, endEpochNanos=1590602976522186955, hasRemoteParent=true, hasEnded=true, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=0}, SpanData{traceId=TraceId{traceId=490cbdb11ac04f618721ec94c0963b14}, spanId=SpanId{spanId=fc8878972fce0cfc}, traceFlags=TraceFlags{sampled=true}, traceState=TraceState{entries=[]}, parentSpanId=SpanId{spanId=b3b68c24c636bda5}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.auto, version=null}, name=test-http-server, kind=SERVER, startEpochNanos=1590602976531001421, attributes={}, timedEvents=[], links=[], status=Status{canonicalCode=OK, description=null}, endEpochNanos=1590602976531228232, hasRemoteParent=true, hasEnded=true, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=0}, SpanData{traceId=TraceId{traceId=490cbdb11ac04f618721ec94c0963b14}, spanId=SpanId{spanId=f420e930805d4886}, traceFlags=TraceFlags{sampled=true}, traceState=TraceState{entries=[]}, parentSpanId=SpanId{spanId=b3b68c24c636bda5}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.auto, version=null}, name=test-http-server, kind=SERVER, startEpochNanos=1590602976531001174, attributes={}, timedEvents=[], links=[], status=Status{canonicalCode=OK, description=null}, endEpochNanos=1590602976531157610, hasRemoteParent=true, hasEnded=true, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=0}]

	at io.opentelemetry.auto.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:70)
	at io.opentelemetry.auto.test.AgentTestRunner.assertTraces(AgentTestRunner.java:233)
	at io.opentelemetry.auto.test.base.HttpClientTest.basic #method request with 2 redirects(HttpClientTest.groovy:241)
Caused by: Assertion failed: 

assert spans.size() == expectedSize
       |     |      |  |
       |     5      |  4
       |            false
       [SpanData{traceId=TraceId{traceId=490cbdb11ac04f618721ec94c0963b14}, spanId=SpanId{spanId=b3b68c24c636bda5}, traceFlags=TraceFlags{sampled=true}, traceState=TraceState{entries=[]}, parentSpanId=SpanId{spanId=0000000000000000}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.auto.jaxrs-client-2.0, version=null}, name=HTTP GET, kind=CLIENT, startEpochNanos=1590602976514001721, attributes={http.status_code=AttributeValueLong{longValue=200}, http.method=AttributeValueString{stringValue=GET}, http.url=AttributeValueString{stringValue=http://localhost:35805/another-redirect}, net.peer.port=AttributeValueLong{longValue=35805}, net.peer.name=AttributeValueString{stringValue=localhost}}, timedEvents=[], links=[], status=Status{canonicalCode=OK, description=null}, endEpochNanos=1590602976532647985, hasRemoteParent=false, hasEnded=true, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=5}, SpanData{traceId=TraceId{traceId=490cbdb11ac04f618721ec94c0963b14}, spanId=SpanId{spanId=ff1a06505e2703cc}, traceFlags=TraceFlags{sampled=true}, traceState=TraceState{entries=[]}, parentSpanId=SpanId{spanId=b3b68c24c636bda5}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.auto, version=null}, name=test-http-server, kind=SERVER, startEpochNanos=1590602976517001446, attributes={}, timedEvents=[], links=[], status=Status{canonicalCode=OK, description=null}, endEpochNanos=1590602976517204314, hasRemoteParent=true, hasEnded=true, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=0}, SpanData{traceId=TraceId{traceId=490cbdb11ac04f618721ec94c0963b14}, spanId=SpanId{spanId=8883d309a24f4e1d}, traceFlags=TraceFlags{sampled=true}, traceState=TraceState{entries=[]}, parentSpanId=SpanId{spanId=b3b68c24c636bda5}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.auto, version=null}, name=test-http-server, kind=SERVER, startEpochNanos=1590602976522001795, attributes={}, timedEvents=[], links=[], status=Status{canonicalCode=OK, description=null}, endEpochNanos=1590602976522186955, hasRemoteParent=true, hasEnded=true, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=0}, SpanData{traceId=TraceId{traceId=490cbdb11ac04f618721ec94c0963b14}, spanId=SpanId{spanId=fc8878972fce0cfc}, traceFlags=TraceFlags{sampled=true}, traceState=TraceState{entries=[]}, parentSpanId=SpanId{spanId=b3b68c24c636bda5}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.auto, version=null}, name=test-http-server, kind=SERVER, startEpochNanos=1590602976531001421, attributes={}, timedEvents=[], links=[], status=Status{canonicalCode=OK, description=null}, endEpochNanos=1590602976531228232, hasRemoteParent=true, hasEnded=true, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=0}, SpanData{traceId=TraceId{traceId=490cbdb11ac04f618721ec94c0963b14}, spanId=SpanId{spanId=f420e930805d4886}, traceFlags=TraceFlags{sampled=true}, traceState=TraceState{entries=[]}, parentSpanId=SpanId{spanId=b3b68c24c636bda5}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.auto, version=null}, name=test-http-server, kind=SERVER, startEpochNanos=1590602976531001174, attributes={}, timedEvents=[], links=[], status=Status{canonicalCode=OK, description=null}, endEpochNanos=1590602976531157610, hasRemoteParent=true, hasEnded=true, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=0}]

	at io.opentelemetry.auto.test.asserts.TraceAssert.assertTrace(TraceAssert.groovy:47)
	at io.opentelemetry.auto.test.asserts.InMemoryExporterAssert.trace(InMemoryExporterAssert.groovy:85)
	at io.opentelemetry.auto.test.base.HttpClientTest.basic #method request with 2 redirects_closure15(HttpClientTest.groovy:242)
	at io.opentelemetry.auto.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:52)
	... 2 more
```

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-auto-instr-java/1130/workflows/79a1ec5e-172f-444a-af21-88c6837b8a03/jobs/9408/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1404/workflows/8557626c-c743-49e3-90bc-35b99ce12ef5/jobs/11337/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1614/workflows/a233fe76-ec29-4f9c-8dac-039da7fc30cb/jobs/12603/tests

**Comment by trask** [comment]
Closing per #925
