### ISSUE TITLE
Support JDK 17

### ISSUE THREAD

**Issue by harel-e** [open-telemetry/opentelemetry-java-instrumentation#4552]
**Is your feature request related to a problem? Please describe.**

The latest release (1.7.1) fails to start with JDK 17
I tested with OpenJDK 17 and Oracle JDK 17

```
[otel.javaagent 2021-10-31 19:52:09:746 +0200] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.7.1
[otel.javaagent 2021-10-31 19:52:11:687 +0200] [main] ERROR io.opentelemetry.javaagent.tooling.HelperInjector - Error preparing helpers while processing class sun.rmi.transport.ObjectTable for rmi. Failed to inject helper classes into instance <bootstrap>
java.lang.IllegalStateException: java.lang.IllegalAccessError: superinterface check failed: class io.opentelemetry.javaagent.instrumentation.rmi.context.server.ContextDispatcher (in unnamed module @0x5ac86ba5) cannot access class sun.rmi.server.Dispatcher (in module java.rmi) because module java.rmi does not export sun.rmi.server to unnamed module @0x5ac86ba5
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe$Dispatcher$Enabled.defineClass(ClassInjector.java:2023)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe.injectRaw(ClassInjector.java:1798)

...

Caused by: java.lang.IllegalAccessError: superinterface check failed: class io.opentelemetry.javaagent.instrumentation.rmi.context.server.ContextDispatcher (in unnamed module @0x5ac86ba5) cannot access class sun.rmi.server.Dispatcher (in module java.rmi) because module java.rmi does not export sun.rmi.server to unnamed module @0x5ac86ba5
	at java.base/jdk.internal.misc.Unsafe.defineClass0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.defineClass(Unsafe.java:1325)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe$Dispatcher$Enabled.defineClass(ClassInjector.java:2013)
```

**Workaround**

Add the following VM param:
-Dotel.javaagent.exclude-classes="sun.rmi.transport.ObjectTable"

**Comment by iNikem** [comment]
@harel-e Does your application use RMI? We do have tests successfully running with agent on Java 17, which means that probably your application uses something that we don't check that triggers this failure. Can you provide a small reproducible example of this?

**Comment by harel-e** [comment]
@iNikem - My application does not use RMI. It's a simple Spring Boot application using spring-boot-starter-web dependency that I created to test OT. My guess is that the RMI dependency comes from Spring Boot.

**Comment by harel-e** [comment]
After further investigation, it seems the dependency came from enabling JMX monitoring, which depends on RMI.
Simply add -Dcom.sun.management.jmxremote to reproduce the issue.

**Comment by RashmiRam** [comment]
Does this mean that latest version supports JDK17 too. Is it okay if the support is mentioned here https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md#jvms-and-operating-systems?

**Comment by trask** [comment]
Hi @RashmiRam! I just sent a PR (#4715) to try to clarify this.

While we run smoke tests against Java 17, we are currently blocked from running integration tests against Java 17 due to #4266.

**Comment by RashmiRam** [comment]
Hi @trask Thanks for the clarification. Looking forward to it.
