### ISSUE TITLE
NoClassDefFoundError: Could not initialize class io.opentelemetry.javaagent.instrumentation.netty.v4_0.AttributeKeys

### ISSUE THREAD

**Issue by qiansheng91** [open-telemetry/opentelemetry-java-instrumentation#4612]
My application had started failure when I used the OpenTelemetry agent.

Here are the pieces of information: 

Here is my java agent version:
![image](https://user-images.githubusercontent.com/81615037/140847289-8ad7f7e5-7a67-4aa4-a84c-d6c7751c46af.png)

Here is  the error message:
```
 ERROR 15548 [     parallel-5] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception
java.lang.NoClassDefFoundError: Could not initialize class io.opentelemetry.javaagent.instrumentation.netty.v4_0.AttributeKeys
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305)
	at io.lettuce.core.protocol.DefaultEndpoint.channelWriteAndFlush(DefaultEndpoint.java:342)
	at io.lettuce.core.protocol.DefaultEndpoint.writeToChannelAndFlush(DefaultEndpoint.java:282)
	at io.lettuce.core.protocol.DefaultEndpoint.write(DefaultEndpoint.java:142)
	at io.lettuce.core.protocol.CommandExpiryWriter.write(CommandExpiryWriter.java:112)
	at io.lettuce.core.RedisChannelHandler.dispatch(RedisChannelHandler.java:184)
	at io.lettuce.core.StatefulRedisConnectionImpl.dispatch(StatefulRedisConnectionImpl.java:152)
	at io.lettuce.core.RedisPublisher$RedisSubscription.dispatchCommand(RedisPublisher.java:390)
	at io.lettuce.core.RedisPublisher$CommandDispatch$1.dispatch(RedisPublisher.java:477)
	at io.lettuce.core.RedisPublisher$RedisSubscription.checkCommandDispatch(RedisPublisher.java:385)
	at io.lettuce.core.RedisPublisher$State$2.request(RedisPublisher.java:543)
	at io.lettuce.core.RedisPublisher$RedisSubscription.request(RedisPublisher.java:242)
	at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:102)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onSubscribe(MonoFlatMap.java:230)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onSubscribe(TracingSubscriber.java:53)
	at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:64)
	at io.lettuce.core.RedisPublisher$State$1.subscribe(RedisPublisher.java:522)
	at io.lettuce.core.RedisPublisher$RedisSubscription.subscribe(RedisPublisher.java:225)
	at io.lettuce.core.RedisPublisher.subscribe(RedisPublisher.java:126)
	at reactor.core.publisher.MonoFromPublisher.subscribe(MonoFromPublisher.java:43)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:45)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:58)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:92)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:58)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:127)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1515)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
....
```

**Comment by mateuszrzeszutek** [comment]
Hey @qiansheng91 ,
Does the issue still appear when using agent [v1.7.2](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.7.2)?
If so, can you provide a reproduction scenario, a simple app that fails with the error listed above?

**Comment by laurit** [comment]
@qiansheng91 what version of netty are you using? Does your application include `io.netty:netty-codec-http` jar, if so what version? Before the `NoClassDefFoundError` is there another exception, something like `java.lang.NoSuchMethodError: io.netty.util.AttributeKey.<init>(Ljava/lang/String;)V`?

**Comment by qiansheng91** [comment]
> Hey @qiansheng91 , Does the issue still appear when using agent [v1.7.2](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.7.2)? If so, can you provide a reproduction scenario, a simple app that fails with the error listed above?

Thanks for your response; I will try it and give your the response

**Comment by qiansheng91** [comment]
> @qiansheng91 what version of netty are you using? Does your application include `io.netty:netty-codec-http` jar, if so what version? Before the `NoClassDefFoundError` is there another exception, something like `java.lang.NoSuchMethodError: io.netty.util.AttributeKey.<init>(Ljava/lang/String;)V`?

The package I imported is `netty-all .` The version is `4.0.36.Final`, and  I haven't seen the exception.

**Comment by laurit** [comment]
> The package I imported is `netty-all .` The version is `4.0.36.Final`, my application doesn't include the jar, and I haven't seen the exception.

Thanks, I think this explains it. Lettuce also depends on the netty (but not the all artifact) which is probably how you end up in having both netty 4.0 and 4.1 in the same application.

**Comment by qiansheng91** [comment]
@mateuszrzeszutek  I had changed the agent version, but it still doesn't work.  My application is vast. And I don't know how to write the demo. Is there any way to resolve this problem?

 Here is the new information:

![image](https://user-images.githubusercontent.com/81615037/141711100-b4e24a3a-5de1-435b-8963-d775aa801187.png)


![image](https://user-images.githubusercontent.com/81615037/141711108-68c60795-e947-44d3-95ad-a1e3268fe079.png)

**Comment by mateuszrzeszutek** [comment]
Hey @qiansheng91 ,
Actually there is no need for that anymore - Lauri has fixed this issue in #4626. Sorry for not telling you sooner, I kinda assumed you'd noticed the PR linked to this issue.

**Comment by laurit** [comment]
@qiansheng91 Could you try with nightly build https://oss.sonatype.org/content/repositories/snapshots/io/opentelemetry/javaagent/opentelemetry-javaagent/1.8.0-SNAPSHOT/ and let us know whether this fixes the issue for you.

**Comment by qiansheng91** [comment]
@mateuszrzeszutek  Thanks very much. 
@laurit  OK, I will try it. Thanks.

**Comment by qiansheng91** [comment]
@laurit @mateuszrzeszutek  Thanks all, it works.
