### ISSUE TITLE
Sporadic test failure: RatpackForkedHttpServerTest test timed out after 10 minutes

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4618]
https://scans.gradle.com/s/cjsx2lqhgstlg/console-log?task=:instrumentation:ratpack-1.4:javaagent:test

```
RatpackForkedHttpServerTest > high concurrency test FAILED	
    org.junit.runners.model.TestTimedOutException: test timed out after 10 minutes	
        at java.base@15.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)	
        at java.base@15.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:714)	
        at java.base@15.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1046)	
        at java.base@15.0.2/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)	
        at io.opentelemetry.instrumentation.test.base.HttpServerTest.high concurrency test(HttpServerTest.groovy:457)
```

**Comment by trask** [comment]
Copying in @mateuszrzeszutek's comment from https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4658#issuecomment-971396532:

Looks like ratpack instrumentation (combined with underlying netty instrumentation) leaks scopes:
```
java.lang.AssertionError: Thread [ratpack-compute-4-2] opened a scope of {
  opentelemetry-netty-error=io.opentelemetry.javaagent.instrumentation.netty.common.NettyErrorHolder@e3db6cfc,
  opentelemetry-servlet-span-naming-key=io.opentelemetry.javaagent.shaded.instrumentation.api.servlet.ServerSpanNaming@26ddc9f3, 
  http-server-request-metrics-state=State{startAttributes={http.user_agent=test-user-agent, http.flavor=1.1, http.target=/success, net.peer.name=localhost, http.scheme=http, http.host=localhost:11002, http.client_ip=1.1.1.1, net.peer.ip=127.0.0.1, http.method=GET, net.peer.port=56352}, startTimeNanos=955060984188}, 
  opentelemetry-trace-span-key=RecordEventsReadableSpan{traceId=f63dc4191d0dd37b7c685b1129f64119, spanId=15ce41f79f0941e2, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, name=HTTP GET, kind=SERVER, attributes=AttributesMap{data={http.user_agent=test-user-agent, http.flavor=1.1, http.target=/success, net.peer.name=localhost, http.scheme=http, http.host=localhost:11002, http.client_ip=1.1.1.1, net.peer.ip=127.0.0.1, http.method=GET, net.peer.port=56352}, capacity=128, totalAddedValues=10}, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1637120124299000000, endEpochNanos=0}, 
  opentelemetry-traces-span-key-server=RecordEventsReadableSpan{traceId=f63dc4191d0dd37b7c685b1129f64119, spanId=15ce41f79f0941e2, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, name=HTTP GET, kind=SERVER, attributes=AttributesMap{data={http.user_agent=test-user-agent, http.flavor=1.1, http.target=/success, net.peer.name=localhost, http.scheme=http, http.host=localhost:11002, http.client_ip=1.1.1.1, net.peer.ip=127.0.0.1, http.method=GET, net.peer.port=56352}, capacity=128, totalAddedValues=10}, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1637120124299000000, endEpochNanos=0}
} here:
            at io.opentelemetry.javaagent.instrumentation.netty.v4_1.server.HttpServerRequestTracingHandler.channelRead(HttpServerRequestTracingHandler.java:55)
```
