### ISSUE TITLE
Sporadic failure: RocketMqClienttest

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4728]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/runs/4330460695

```
RocketMqClientTest > test rocketmq produce and consume FAILED
    Condition not satisfied:

    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

    assert spans.size() == expectedSize
           |     |      |  |
           |     2      |  4
           |            false
           [SpanData{spanContext=ImmutableSpanContext{traceId=13aa6f9e2f6095cab13ce8297fee1634, spanId=fa1b57c0ba76af31, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=null, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.9.1"}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=test, version=1.10.0-alpha-SNAPSHOT, schemaUrl=null}, name=parent, kind=INTERNAL, startEpochNanos=1637905982509205648, endEpochNanos=1637905982545411953, attributes={}, totalAttributeCount=0, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}, SpanData{spanContext=ImmutableSpanContext{traceId=13aa6f9e2f6095cab13ce8297fee1634, spanId=7abac9b3ea8d34ca, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=13aa6f9e2f6095cab13ce8297fee1634, spanId=fa1b57c0ba76af31, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, resource=Resource{schemaUrl=null, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.9.1"}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.rocketmq-client-4.8, version=1.10.0-alpha-SNAPSHOT, schemaUrl=null}, name=2a4079cc-288d-491d-aede-4c67cab50163 send, kind=PRODUCER, startEpochNanos=1637905982529391800, endEpochNanos=1637905982543709930, attributes=AttributesMap{data={messaging.rocketmq.tags=TagA, messaging.rocketmq.send_result=SEND_OK, messaging.destination=2a4079cc-288d-491d-aede-4c67cab50163, messaging.message_id=7F0000015157F27F13DA82022F390000, messaging.destination_kind=topic, messaging.system=rocketmq, messaging.rocketmq.broker_address=127.0.0.1:11104}, capacity=128, totalAddedValues=7}, totalAttributeCount=7, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}]
        at app//io.opentelemetry.instrumentation.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:61)
        at app//io.opentelemetry.instrumentation.test.InstrumentationSpecification.assertTraces(InstrumentationSpecification.groovy:106)
        at io.opentelemetry.instrumentation.rocketmq.AbstractRocketMqClientTest.test rocketmq produce and consume(AbstractRocketMqClientTest.groovy:127)
```

**Comment by laurit** [comment]
Haven't seen these lately, assuming this has been fixed.
