### ISSUE TITLE
Add jaeger remote sampler

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#4898]
**Is your feature request related to a problem? Please describe.**

I want to use Jaeger remote sampler https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/jaeger-remote-sampler with Javaagent

**Describe the solution you'd like**

Make https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/jaeger-remote-sampler available in the javaagent distribution.

**Describe alternatives you've considered**

Build a custom javaagent.

**Additional context**

Jaeger remote sampler in the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md

**Comment by mateuszrzeszutek** [comment]
You don't really need to build a custom javaagent, you can use the sampler as an [extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/README.md).

**Comment by trask** [comment]
> You don't really need to build a custom javaagent, you can use the sampler as an [extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/README.md).

👍

it would still be nice to add this to the javaagent distribution since there's already spec support for `OTEL_TRACES_SAMPLER=jaeger_remote`

@pavolloffay is this the same as #1953?

**Comment by pavolloffay** [comment]
It seems related to #1953. I would say the #1953 is not correctly defined as the sampling strategies are not pulled by the exporter.

**Comment by pavolloffay** [comment]
I have started looking at this. 

@anuraaga is my understanding correct that the Jaeger remote sampler will require some work to make this work in the auto-instrumentation? The root cause is https://github.com/open-telemetry/opentelemetry-specification/discussions/1996? 

Or could we use one of `grpc-okhttp, grpc-netty, or grpc-netty-shaded` for the remote sampler? 

I am getting the following error.
```
[otel.javaagent 2021-12-15 16:09:07:268 +0100] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.10.0-SNAPSHOT
ERROR io.opentelemetry.javaagent.OpenTelemetryAgent
io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
	at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:43)
	at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76)
	at io.opentelemetry.exporter.otlp.internal.grpc.DefaultGrpcExporterBuilder.build(DefaultGrpcExporterBuilder.java:131)
	at io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporterBuilder.build(JaegerGrpcSpanExporterBuilder.java:92)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureJaeger(SpanExporterConfiguration.java:186)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureExporter(SpanExporterConfiguration.java:104)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.lambda$configureSpanExporters$1(SpanExporterConfiguration.java:94)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureSpanExporters(SpanExporterConfiguration.java:89)
	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:61)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.newOpenTelemetrySdk(OpenTelemetrySdkAutoConfiguration.java:104)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:177)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installOpenTelemetrySdk(OpenTelemetryInstaller.java:42)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:125)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:96)
	at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:65)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:37)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:55)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
^C% 
```

**Comment by trask** [comment]
oh ya, this is because we don't use grpc or protobuf dependencies anymore. all the standard otel exporters (including the jaeger exporter) now hand marshal the protobuf data and send it directly using okhttp. check out for example https://github.com/open-telemetry/opentelemetry-java/pull/3800.

not including grpc/netty/protobuf dependencies saved us a few MB in the javaagent jar, so I don't think we would want to bring those dependencies back just to support jaeger remote sampler.

probably will need to update the jaeger remote sampler to use similar "grpc lite" mechanism first

**Comment by pavolloffay** [comment]
thanks Trask, I will take a look at it in the otel-java repo.
