### ISSUE TITLE
App crashes on missing headers using RabbitMQ instrumentation

### ISSUE THREAD

**Issue by Asafb26** [open-telemetry/opentelemetry-java-instrumentation#4902]
**Describe the bug**
We found a bug in RabbitMQ consumption using OpenTelemetry instrumentation, the bug crashed the entire app. pointed on null pointer exception on missing headers, on the 100% telemetry ecosystem it should not happen, but it's not the case for most uses.

**Steps to reproduce**
Consume a RabbitMQ event without headers.

**What did you expect to see?**
A working consumer holds a root context.

**What did you see instead?**
```
msg:Consumer io.opentelemetry.javaagent.instrumentation.rabbitmq.TracedDelegatingConsumer@39d1bec8 (amq.ctag-59xS-Tsm-Tg1f-gYeYr2hA) method handleDelivery for channel AMQChannel(amqp://****@***.***.***.***:5672/,1) threw an exception for channel AMQChannel(amqp://****@***.***.***.***:5672/,1)
stack:java.lang.NullPointerException: null
at io.opentelemetry.javaagent.instrumentation.rabbitmq.DeliveryRequestGetter.get(DeliveryRequestGetter.java:24)
at io.opentelemetry.javaagent.instrumentation.rabbitmq.DeliveryRequestGetter.get(DeliveryRequestGetter.java:11)
at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.propagation.W3CTraceContextPropagator.extractImpl(W3CTraceContextPropagator.java:165)
at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.propagation.W3CTraceContextPropagator.extract(W3CTraceContextPropagator.java:156)
at io.opentelemetry.javaagent.shaded.io.opentelemetry.context.propagation.MultiTextMapPropagator.extract(MultiTextMapPropagator.java:65)
at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.ServerInstrumenter.start(ServerInstrumenter.java:29)
at io.opentelemetry.javaagent.instrumentation.rabbitmq.TracedDelegatingConsumer.handleDelivery(TracedDelegatingConsumer.java:69)
at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
```

**What version are you using?**
`v0.9.1`

**Comment by Asafb26** [comment]
@trask Thanks, will it be published anytime soon? we are thinking about a temp solution in our services for now.

**Comment by trask** [comment]
hey @Asafb26, we are skipping the December monthly release in order to stay in sync with the SDK repo version (the SDK published a metrics RC this month). next release will be January (~3rd week).

just in case you haven't seen, you can [disable individual instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/suppressing-instrumentation.md#suppressing-specific-agent-instrumentation) (though of course then you lose its telemetry also)
