### ISSUE TITLE
Sporadic test failure (1x): ApacheClientUriRequestResponseHandler

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#492]
```
org.apache.http.conn.ConnectTimeoutException: Connect to www.google.com/172.217.7.196:443 timed out
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:335)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:123)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:147)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:101)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:381)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:641)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:730)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:708)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:699)
	at ApacheClientUriRequestResponseHandler.executeRequest(ApacheHttpClientTest.groovy:183)
	at ApacheHttpClientTest.doRequest(ApacheHttpClientTest.groovy:46)
	at io.opentelemetry.auto.test.base.HttpClientTest.test https request(HttpClientTest.groovy:362)
```

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1267/workflows/d5d53b6d-2572-4fc7-b638-4c070d23527d/jobs/10371/tests

**Comment by trask** [comment]
Closing per #925
