### ISSUE TITLE
Sporadic micrometer library test failure

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#5103]
I saw this on the original micrometer library instrumentation PR: https://github.com/open-telemetry/opentelemetry-java-instrumentation/runs/4797134585

And again on next PR: https://github.com/open-telemetry/opentelemetry-java-instrumentation/runs/4798756656

Not sure what's going on with the lack of details about the error...

```
> Task :instrumentation:micrometer-1.5:library:compileTestJava
> Task :instrumentation:micrometer-1.5:library:compileTestGroovy NO-SOURCE
> Task :instrumentation:micrometer-1.5:library:processTestResources NO-SOURCE
> Task :instrumentation:micrometer-1.5:library:testClasses
> Task :instrumentation:micrometer-1.5:library:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':instrumentation:micrometer-1.5:library:test'.
> java.lang.NullPointerException (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 20s
408 actionable tasks: 104 executed, 304 from cache

A build scan cannot be produced as an error occurred gathering build data.
Please report this problem via https://gradle.com/help/plugin and include the following via copy/paste:

----------
Gradle version: 7.3.3
Plugin version: 3.8

java.lang.NullPointerException
	at com.gradle.scan.plugin.internal.i.g.b(SourceFile:61)
	at com.gradle.scan.plugin.internal.b.t.b.a(SourceFile:74)
	at com.gradle.scan.plugin.internal.b.t.b.a(SourceFile:47)
	at com.gradle.scan.plugin.internal.b.h.a.a(SourceFile:92)
	at com.gradle.scan.plugin.internal.b.h.a.f(SourceFile:79)
	at com.gradle.scan.plugin.internal.b.h.a.g(SourceFile:103)
```

**Comment by trask** [comment]
enabling `--debug` in #5104 printed out the real error:

```
2022-01-13T05:59:46.5141084Z 2022-01-13T05:59:46.481+0000 [DEBUG] [TestEventLogger] FunctionTimerTest > functionTimersWithSameNameAndDifferentTags() FAILED
2022-01-13T05:59:46.5142184Z 2022-01-13T05:59:46.482+0000 [DEBUG] [TestEventLogger]     org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in io.opentelemetry.instrumentation.testing.junit.InstrumentationExtension
2022-01-13T05:59:46.5143060Z 2022-01-13T05:59:46.482+0000 [DEBUG] [TestEventLogger]     Expecting any element of:
2022-01-13T05:59:46.5143573Z 2022-01-13T05:59:46.482+0000 [DEBUG] [TestEventLogger]       []
2022-01-13T05:59:46.5144224Z 2022-01-13T05:59:46.482+0000 [DEBUG] [TestEventLogger]     to satisfy the given assertions requirements but none did:
2022-01-13T05:59:46.5144727Z 2022-01-13T05:59:46.482+0000 [DEBUG] [TestEventLogger]
2022-01-13T05:59:46.5145219Z 2022-01-13T05:59:46.482+0000 [DEBUG] [TestEventLogger]      within 10 seconds.
2022-01-13T05:59:46.5145876Z 2022-01-13T05:59:46.482+0000 [DEBUG] [TestEventLogger]         at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
2022-01-13T05:59:46.5146671Z 2022-01-13T05:59:46.482+0000 [DEBUG] [TestEventLogger]         at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
2022-01-13T05:59:46.5147463Z 2022-01-13T05:59:46.482+0000 [DEBUG] [TestEventLogger]         at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
2022-01-13T05:59:46.5148254Z 2022-01-13T05:59:46.482+0000 [DEBUG] [TestEventLogger]         at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
2022-01-13T05:59:46.5149338Z 2022-01-13T05:59:46.482+0000 [DEBUG] [TestEventLogger]         at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
2022-01-13T05:59:46.5150409Z 2022-01-13T05:59:46.482+0000 [DEBUG] [TestEventLogger]         at io.opentelemetry.instrumentation.testing.junit.InstrumentationExtension.waitAndAssertMetrics(InstrumentationExtension.java:81)
2022-01-13T05:59:46.5151707Z 2022-01-13T05:59:46.482+0000 [DEBUG] [TestEventLogger]         at io.opentelemetry.instrumentation.micrometer.v1_5.AbstractFunctionTimerTest.functionTimersWithSameNameAndDifferentTags(AbstractFunctionTimerTest.java:165)
```

**Comment by mateuszrzeszutek** [comment]
Thanks for the debug PR :heart:
That really helped pinpointing the issue

**Comment by anuraaga** [comment]
Looks like this might still be happening

https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/runs/1696262868/attempts/1
https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/runs/1696262868/attempts/2
