### ISSUE TITLE
Sporadic test failure (3x): CxfClient*Test

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#530]
```
Condition not satisfied:

org.spockframework.runtime.GroovyRuntimeUtil.invokeMethod(GroovyRuntimeUtil.java:171)

assert spans.size() == expectedSize
       |     |      |  |
       |     3      |  2
       |            false
       [SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@57fa00e5, resolvedLinks=[], resolvedEvents=[], attributes={net.peer.name=AttributeValueString{stringValue=localhost}, http.status_code=AttributeValueLong{longValue=200}, net.peer.port=AttributeValueLong{longValue=34985}, http.url=AttributeValueString{stringValue=http://localhost:34985/success}, http.method=AttributeValueString{stringValue=GET}}, totalAttributeCount=5, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}, SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@3007ccf9, resolvedLinks=[], resolvedEvents=[], attributes={}, totalAttributeCount=0, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}, SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@4e3e5163, resolvedLinks=[], resolvedEvents=[], attributes={}, totalAttributeCount=0, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}]

	at io.opentelemetry.auto.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:70)
	at io.opentelemetry.auto.test.AgentTestRunner.assertTraces(AgentTestRunner.java:233)
	at io.opentelemetry.auto.test.base.HttpClientTest.basic #method request #url - tagQueryString=#tagQueryString(HttpClientTest.groovy:95)
Caused by: Assertion failed: 

assert spans.size() == expectedSize
       |     |      |  |
       |     3      |  2
       |            false
       [SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@57fa00e5, resolvedLinks=[], resolvedEvents=[], attributes={net.peer.name=AttributeValueString{stringValue=localhost}, http.status_code=AttributeValueLong{longValue=200}, net.peer.port=AttributeValueLong{longValue=34985}, http.url=AttributeValueString{stringValue=http://localhost:34985/success}, http.method=AttributeValueString{stringValue=GET}}, totalAttributeCount=5, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}, SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@3007ccf9, resolvedLinks=[], resolvedEvents=[], attributes={}, totalAttributeCount=0, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}, SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@4e3e5163, resolvedLinks=[], resolvedEvents=[], attributes={}, totalAttributeCount=0, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}]

	at io.opentelemetry.auto.test.asserts.TraceAssert.assertTrace(TraceAssert.groovy:47)
	at io.opentelemetry.auto.test.asserts.InMemoryExporterAssert.trace(InMemoryExporterAssert.groovy:85)
	at io.opentelemetry.auto.test.base.HttpClientTest.basic #method request #url - tagQueryString=#tagQueryString_closure5(HttpClientTest.groovy:96)
	at io.opentelemetry.auto.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:52)
	... 2 more
```

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1349/workflows/706a5c59-70a1-40cf-8638-910db03c3f8b/jobs/10947/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1373/workflows/a856798b-5954-458f-aab2-400011465899/jobs/11125/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1437/workflows/d2d83693-bf49-435f-a805-b6095ce96090/jobs/11545/tests

**Comment by trask** [comment]
Closing per #925
