### ISSUE TITLE
Sporadic test failure: vaadin142Test timeout

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#5318]
> * What went wrong:
Execution failed for task ':instrumentation:vaadin-14.2:javaagent:vaadin142Test'.
> Timeout has been exceeded

https://github.com/open-telemetry/opentelemetry-java-instrumentation/runs/5075801672

**Comment by trask** [comment]
Another example: https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/runs/1975243874

**Comment by laurit** [comment]
From deadlock detector
```
"Test worker" #1 prio=5 os_prio=0 cpu=6081.61ms elapsed=325.81s tid=0x00007f35d002fa20 nid=0x5abc runnable  [0x00007f35d5115000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(java.base@17.0.2/Native Method)
	at java.io.FileInputStream.read(java.base@17.0.2/FileInputStream.java:276)
	at java.io.BufferedInputStream.read1(java.base@17.0.2/BufferedInputStream.java:282)
	at java.io.BufferedInputStream.read(java.base@17.0.2/BufferedInputStream.java:343)
	- locked <0x00000000e6661320> (a java.lang.ProcessImpl$ProcessPipeInputStream)
	at sun.nio.cs.StreamDecoder.readBytes(java.base@17.0.2/StreamDecoder.java:270)
	at sun.nio.cs.StreamDecoder.implRead(java.base@17.0.2/StreamDecoder.java:313)
	at sun.nio.cs.StreamDecoder.read(java.base@17.0.2/StreamDecoder.java:188)
	- locked <0x00000000e6663568> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(java.base@17.0.2/InputStreamReader.java:177)
	at java.io.BufferedReader.fill(java.base@17.0.2/BufferedReader.java:162)
	at java.io.BufferedReader.readLine(java.base@17.0.2/BufferedReader.java:329)
	- locked <0x00000000e6663568> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(java.base@17.0.2/BufferedReader.java:396)
	at com.vaadin.flow.server.frontend.TaskRunNpmInstall.runNpmInstall(TaskRunNpmInstall.java:287)
	at com.vaadin.flow.server.frontend.TaskRunNpmInstall.execute(TaskRunNpmInstall.java:99)
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:445)
	at com.vaadin.flow.server.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:316)
	at com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener.contextInitialized(VaadinServletContextInitializer.java:349)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4683)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5146)
```
