### ISSUE TITLE
Smoke tests fail on windows-latest

### ISSUE THREAD

**Issue by laurit** [open-telemetry/opentelemetry-java-instrumentation#5391]
```
Jetty10Jdk11 > initializationError FAILED
    com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"hcsshim::CreateComputeSystem 30ca6fdac9faec01130df4fa1b28906a5316d5d20092a38b3e8db05809bec72c: The container operating system does not match the host operating system."}
        at app//com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
        at app//com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:103)
        at app//com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
        at app//com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
        at app//com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at app//com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at app//com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
        at app//io.opentelemetry.smoketest.windows.WindowsTestContainerManager.startContainer(WindowsTestContainerManager.java:293)
        at app//io.opentelemetry.smoketest.windows.WindowsTestContainerManager.startEnvironment(WindowsTestContainerManager.java:88)
        at app//io.opentelemetry.smoketest.AbstractTestContainerManager.startEnvironmentOnce(AbstractTestContainerManager.java:44)
        at app//io.opentelemetry.smoketest.SmokeTest.setupSpec(SmokeTest.groovy:62)
```
`windows-latest` seems to have changed to `windows-2022` but our tests only work with `windows-2019`

**Comment by trask** [comment]
Resolved by #7299
