### ISSUE TITLE
NoClassDefFoundError Issue for opentelemetry.1.9.2

### ISSUE THREAD

**Issue by c609942867** [open-telemetry/opentelemetry-java-instrumentation#5545]
**Describe the bug**
I use opentelemetry as java agent and set -Dotel.javaagent.debug=true,  I found this debug log in catalina.out.
Do you know whether it has any impact on tracing path if the following error is thrown or not.

```
[otel.javaagent 2022-03-11 09:38:50:237 +0000] [http-nio-10099-exec-9] DEBUG io.opentelemetry.javaagent.bootstrap.ExceptionLogger - Failed to handle exception in instrumentation for org.apache.catalina.connector.CoyoteAdapter on java.net.URLClassLoader@cb03411
java.lang.NoClassDefFoundError: Could not initialize class io.opentelemetry.javaagent.instrumentation.tomcat.v7_0.Tomcat7Singletons
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:414)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by laurit** [comment]
This error is definitely unexpected. It will breaks starting `SERVER` spans for tomcat. It is possible that this will not affect tracing much as if tomcat instrumentation did not create the `SERVER` span servlet instrumentation will.
Before `NoClassDefFoundError` there might be an `ExceptionInInitializerError`. Could you add the stack trace for that here. Hopefully it will reveal the root cause of the issue.

**Comment by c609942867** [comment]
the issue caused by permission rules in catalina.policy
