### ISSUE TITLE
Crashes when using the Aleph library (built on top of netty)

### ISSUE THREAD

**Issue by HughPowell** [open-telemetry/opentelemetry-java-instrumentation#5901]
**Describe the bug**
The binary created by the [reproduction repo](https://github.com/HughPowell/honeycomb-aleph) crashes when using the OpenTelemetry javaagent.

**Steps to reproduce**
1. Install [Clojure](https://clojure.org/guides/getting_started#_clojure_installer_and_cli_tools)
2. Clone [the project](https://github.com/HughPowell/honeycomb-aleph)
3. Build the project `clj -T:build uber`
4. [Download](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.13.0/opentelemetry-javaagent.jar) the OpenTelemetry javaagent
5. Run the resulting jar `OTEL_TRACES_EXPORTER=logging java -javaagent:opentelemetry-javaagent.jar -jar target/honeycomb-aleph-0.1.2-standalone.jar`

Unfortunately it's a Clojure project and my Java-foo isn't strong enough to extract a purely Java project from the code.

**What did you expect to see?**
The HTML for `http://www.example.com` printed to the terminal.

**What did you see instead?**
The following output and exception stack trace
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2022-04-21 11:22:55:997 +1000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.13.0
Exception in thread "main" java.lang.NullPointerException
	at io.opentelemetry.javaagent.instrumentation.netty.v4_1.InstrumentedAddressResolverGroup.getResolver(InstrumentedAddressResolverGroup.java:42)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:194)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1012)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at manifold.executor$thread_factory$reify__527$f__528.invoke(executor.clj:47)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:829)
[otel.javaagent 2022-04-21 11:23:07:045 +1000] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/0:0:0:0:0:0:0:1:4317
```

**What version are you using?**
v1.13.0

**Environment**
All on my laptop
`java --version`
> openjdk 11.0.14.1 2022-02-08
> OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.21.10)
> OpenJDK 64-Bit Server VM (build 11.0.14.1+1-Ubuntu-0ubuntu1.21.10, mixed mode, sharing)

`javac --version`
> javac 11.0.14.1

`clj --version`

**Comment by trask** [comment]
@HughPowell thanks for reporting this!

**Comment by HughPowell** [comment]
Amazing! Thanks for the super fast fix.
