### ISSUE TITLE
custom trace exporter: classloader issue

### ISSUE THREAD

**Issue by system-designer** [open-telemetry/opentelemetry-java-instrumentation#6087]
**Describe the bug**
I wrote a custom trace exporter to export span to a mq, in the exporter I used "com.sun.jndi.dns.DnsContextFactory" to get dns info, details code like below: 

      Properties env = new Properties();
      env.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.dns.DnsContextFactory");
      InitialDirContext idc = new InitialDirContext(env);
      Attributes attributes = idc.getAttributes(LCS_SERVER_DOMAIN, new String[] {"CNAME"});
      Attribute attribute = attributes.get("CNAME");
      String domain = attribute.get().toString();

When I run javaagent in openjdk11 it throws an exception below **while it's ok in openjdk8**.

javax.naming.NoInitialContextException: Cannot instantiate class: com.sun.jndi.dns.DnsContextFactory [Root exception is java.lang.ClassNotFoundException: com.sun.jndi.dns.DnsContextFactory]
        at java.naming/javax.naming.spi.NamingManager.getFactory(NamingManager.java:760)
        at java.naming/javax.naming.spi.NamingManager.lambda$getInitialContext$1(NamingManager.java:722)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
        at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:722)
        at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
        at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
        at java.naming/javax.naming.InitialContext.<init>(InitialContext.java:208)
        at java.naming/javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
        at io.opentelemetry.exporter.talos.MySpanExporter.createExporter(MySpanExporter.java:230)
        at io.opentelemetry.javaagent.tooling.AgentTracerProviderConfigurer.maybeMyExporterAndSampler(AgentTracerProviderConfigurer.java:84)

Caused by: java.lang.ClassNotFoundException: com.sun.jndi.dns.DnsContextFactory
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.findClass(AgentClassLoader.java:160)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.loadClass(AgentClassLoader.java:141)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at java.naming/com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:127)
        at java.naming/com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:133)
        at java.naming/com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:96)
        at java.naming/javax.naming.spi.NamingManager.getFactory(NamingManager.java:757)

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
It's ok in openjdk11.

**What did you see instead?**
It's error in openjdk11.

**What version are you using?**
opentelemetry-javaagent-instrumentation: v1.13.1

**Environment**
Compiler/Runtime: ("AdoptOpenJDK 11.0.6")
OS: ("CentOS Linux 7 (Core)")

**Additional context**
Thanks for watching.

**Comment by laurit** [comment]
With the introduction of jdk module system some classes that were previously loaded by the boot loader are now loaded by the `PlatformClassLoader`. The class loader used by opentelemetry agent only delegates to boot loader so classes in platform loader won't be available. As `com.sun.naming.internal.VersionHelper` uses thread context class loader you should be able to overcome this issue by setting thread context class loader to system class loader before initializing naming context.

**Comment by system-designer** [comment]
> With the introduction of jdk module system some classes that were previously loaded by the boot loader are now loaded by the `PlatformClassLoader`. The class loader used by opentelemetry agent only delegates to boot loader so classes in platform loader won't be available. As `com.sun.naming.internal.VersionHelper` uses thread context class loader you should be able to overcome this issue by setting thread context class loader to system class loader before initializing naming context.

Thanks for your suggugestion, I fix the problem by adding code below in AgentClassLoader:

protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
  // prometheus exporter uses jdk http server, load it from the platform class loader
  // my exporter uses jdk naming dns, load it from the platform class loader
  if (name != null
      && (name.startsWith("com.sun.net.httpserver.") || name.startsWith("com.sun.jndi.dns."))) {
    return platformClassLoader.loadClass(name);
  }
  return Class.forName(name, false, null);
}

And then adding jvm args "--add-exports jdk.naming.dns/com.sun.jndi.dns=java.naming" to the test application.
