### ISSUE TITLE
Sporadic test failure (1x): MongoClientTest

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#612]
```
java.io.IOException: Could not start process: failed errno:98 Address already in use for socket: 127.0.0.1:41969
2020-06-29T20:43:38.124+0000 E NETWORK  [initandlisten]   addr already in use
2020-06-29T20:43:38.124+0000 E STORAGE  [initandlisten] Failed to set up sockets during startup.
2020-06-29T20:43:38.124+0000 I CONTROL  [initandlisten] dbexit:  rc: 48

	at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:114)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101)
	at MongoBaseTest.setup(MongoBaseTest.groovy:63)
```

https://12570-210933087-gh.circle-artifacts.com/0/reports/instrumentation/mongo/mongo-3.1/tests/test/classes/MongoClientTest.html

**Comment by trask** [comment]
Closing per #925
