### ISSUE TITLE
Sporadic test failure: akka-testing

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#625]
https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1639/workflows/4575e8c7-aa19-4447-a4c6-bc7d8a1983db/jobs/12743/tests

`:instrumentation:java-concurrent:akka-testing:test`

```
    akka basicTell - AkkaActorTest

    Condition not satisfied:

    org.spockframework.runtime.GroovyRuntimeUtil.invokeMethod(GroovyRuntimeUtil.java:171)

    assert traces.size() == expectedSize
           |      |      |  |
           |      2      |  1
           |             false
           [[SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@7441df7, resolvedLinks=[], resolvedEvents=[], attributes={}, totalAttributeCount=0, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}], [SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@a809d82, resolvedLinks=[], resolvedEvents=[], attributes={}, totalAttributeCount=0, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}]]

    	at io.opentelemetry.auto.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:71)
    	at io.opentelemetry.auto.test.AgentTestRunner.assertTraces(AgentTestRunner.java:234)
    	at AkkaActorTest.akka #testMethod(AkkaActorTest.groovy:27)
    Caused by: Assertion failed: 

    assert traces.size() == expectedSize
           |      |      |  |
           |      2      |  1
           |             false
           [[SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@7441df7, resolvedLinks=[], resolvedEvents=[], attributes={}, totalAttributeCount=0, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}], [SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@a809d82, resolvedLinks=[], resolvedEvents=[], attributes={}, totalAttributeCount=0, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}]]

    	at io.opentelemetry.auto.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:48)
    	... 2 more

```

**Comment by trask** [comment]
this looks like a duplicate of #443, i've been tagging issues with "sporadic test failure" label, so you can look across them easily: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues?q=is%3Aissue+is%3Aopen+label%3A%22sporadic+test+failure%22

**Comment by trask** [comment]
and for the most part naming them using the class name to help with finding/incrementing duplicates

**Comment by anuraaga** [comment]
Oops, sorry, good point to look at the label, and not just expect it on the first page of the list >D
