### ISSUE TITLE
Sporadic test failure VertxRxCircuitBreakerWebClientTest

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#627]
https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1640/workflows/3672638d-be57-48bf-97b4-4fa921ec7133/jobs/12754

```
Condition not satisfied:

java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

assert traces.size() == expectedSize
       |      |      |  |
       |      2      |  1
       |             false
       [[SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@48a89333, resolvedLinks=[], resolvedEvents=[], attributes={}, totalAttributeCount=0, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}], [SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@6eea9454, resolvedLinks=[], resolvedEvents=[], attributes={net.peer.name=AttributeValueString{stringValue=localhost}, http.status_code=AttributeValueLong{longValue=200}, net.peer.port=AttributeValueLong{longValue=42791}, http.user_agent=AttributeValueString{stringValue=Vert.x-WebClient/3.9.1}, http.url=AttributeValueString{stringValue=http://localhost:42791/success}, net.peer.ip=AttributeValueString{stringValue=127.0.0.1}, http.method=AttributeValueString{stringValue=GET}}, totalAttributeCount=9, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}]]

	at io.opentelemetry.auto.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:71)
	at io.opentelemetry.auto.test.AgentTestRunner.assertTraces(AgentTestRunner.java:234)
	at io.opentelemetry.auto.test.base.HttpClientTest.trace request without propagation(HttpClientTest.groovy:166)
Caused by: Assertion failed: 

assert traces.size() == expectedSize
       |      |      |  |
       |      2      |  1
       |             false
       [[SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@48a89333, resolvedLinks=[], resolvedEvents=[], attributes={}, totalAttributeCount=0, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}], [SpanWrapper{delegate=io.opentelemetry.sdk.trace.RecordEventsReadableSpan@6eea9454, resolvedLinks=[], resolvedEvents=[], attributes={net.peer.name=AttributeValueString{stringValue=localhost}, http.status_code=AttributeValueLong{longValue=200}, net.peer.port=AttributeValueLong{longValue=42791}, http.user_agent=AttributeValueString{stringValue=Vert.x-WebClient/3.9.1}, http.url=AttributeValueString{stringValue=http://localhost:42791/success}, net.peer.ip=AttributeValueString{stringValue=127.0.0.1}, http.method=AttributeValueString{stringValue=GET}}, totalAttributeCount=9, totalRecordedEvents=0, status=Status{canonicalCode=OK, description=null}}]]

	at io.opentelemetry.auto.test.asserts.InMemoryExporterAssert.assertTraces(InMemoryExporterAssert.groovy:48)
	... 2 more
```

**Comment by trask** [comment]
Closing per #925
