### ISSUE TITLE
cannot add extension (not a subtype)

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java-instrumentation#6298]
**Describe the bug**

"Class cast exception" when adding an extension.

`io.opentelemetry.sdk.autoconfigure.spi.AutoConfigurationCustomizerProvider: org.zalando.observability.config.DemoAutoConfigurationCustomizerProvider not a subtype`

I believe `isAssignableFrom` fails because the interface is loaded from a different classloader (see [explanantion](https://stackoverflow.com/questions/5375349/class-instance-obtained-through-multiple-class-loader)).

**Steps to reproduce**

```java
@AutoService(AutoConfigurationCustomizerProvider.class)
public class DemoAutoConfigurationCustomizerProvider
    implements AutoConfigurationCustomizerProvider {

  @Override
  public void customize(AutoConfigurationCustomizer autoConfiguration) {
    
  }
}
```

This class is put in a jar and added in the "extensions"  path in the agent jar ([instructions](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/177f0aec7c0629ad77cf64d4ab8ccb42648fae1b/examples/extension/build.gradle#L121))

**What did you see instead?**

```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Observability SDK installed.
[otel.javaagent 2022-07-09 14:28:03:191 +0200] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.15.0
OpenTelemetry Javaagent failed to start
java.util.ServiceConfigurationError: io.opentelemetry.sdk.autoconfigure.spi.AutoConfigurationCustomizerProvider: org.zalando.observability.config.DemoAutoConfigurationCustomizerProvider not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:301)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installOpenTelemetrySdk(OpenTelemetryInstaller.java:43)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:115)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:91)
	at io.opentelemetry.javaagent.tooling.AgentStarterImpl.internalStart(AgentStarterImpl.java:89)
	at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:69)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:35)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:57)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:45)
	at org.zalando.observability.config.ObservabilitySDKBootstrap.premain(ObservabilitySDKBootstrap.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
```

**What version are you using?**

1.15.0

**Environment**

temurin-17.0.3

**Comment by laurit** [comment]
@zeitlinger Did you shade `io.opentelemetry.sdk.autoconfigure.spi.AutoConfigurationCustomizerProvider` inside your extension? Add `-verbose:class` to jvm arguments and from the output find where `AutoConfigurationCustomizerProvider` is loaded from. Verify that it is loaded only once.

**Comment by zeitlinger** [comment]
Thanks for the hint @laurit - yes, my project setup was messed up, but now I've figured it out
I think a demo project would really help - happy to share the details of how I got it to work.
