### ISSUE TITLE
gson java.lang.NoClassDefFoundError: java/sql/Time

### ISSUE THREAD

**Issue by XiaoWeiKIN** [open-telemetry/opentelemetry-java-instrumentation#6372]
I was building a distribution in reference [splunk](https://github.com/signalfx/splunk-otel-java) when I was using GSON the distribution had the following error,but `opentelemetry-java-instrumentation` is normal, how should I solve it.
```
OpenTelemetry Javaagent failed to start
java.lang.NoClassDefFoundError: java/sql/Time
	at com.google.gson.internal.bind.TimeTypeAdapter$1.create(TimeTypeAdapter.java:44)
	at com.google.gson.Gson.getAdapter(Gson.java:423)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at io.opentelemetry.javaagent.xiao.otel.config.ApolloConfigurationService.fetchConfigFromApollo(ApolloConfigurationService.java:143)
	at io.opentelemetry.javaagent.xiao.otel.config.ApolloConfigurationService.lambda$getConfig$2(ApolloConfigurationService.java:92)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.opentelemetry.javaagent.xiao.otel.config.ApolloConfigurationService.getConfig(ApolloConfigurationService.java:87)
	at io.opentelemetry.javaagent.xiao.otel.config.ApolloConfigurationService.getConfig(ApolloConfigurationService.java:40)
	at io.opentelemetry.javaagent.xiao.otel.exporters.LiAutoSpanExporter.<init>(LiAutoSpanExporter.java:61)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureExporter(SpanExporterConfiguration.java:103)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.lambda$configureSpanExporters$0(SpanExporterConfiguration.java:79)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureSpanExporters(SpanExporterConfiguration.java:74)
	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:50)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:324)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installOpenTelemetrySdk(OpenTelemetryInstaller.java:41)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:114)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:94)
	at io.opentelemetry.javaagent.tooling.AgentStarterImpl.internalStart(AgentStarterImpl.java:89)
	at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:69)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:35)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:57)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:49)
	at com.lixiang.lse.javaagent.LseAgent.agentmain(LseAgent.java:29)
	at com.lixiang.lse.javaagent.LseAgent.premain(LseAgent.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.ClassNotFoundException: java.sql.Time
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.loadClass(AgentClassLoader.java:149)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 41 more
```

**Comment by mateuszrzeszutek** [comment]
Hey @XiaoWeiKIN ,
Are you perhaps using a custom modular JDK that does not have the `java.sql` module?

**Comment by XiaoWeiKIN** [comment]
hi @mateuszrzeszutek  , I not use modular JDK, I just used the `gson` library.

**Comment by mateuszrzeszutek** [comment]
Hm, that's strange. Would you be able to create a repro scenario for this issue?

**Comment by XiaoWeiKIN** [comment]
Oh, it's very difficult because there are so many internal libraries in the distribution. Let me check again.

**Comment by laurit** [comment]
The problem is that in jdk11 `java.sql.Time` is loaded by platform class loader, but the agent class loader only delegates to bootstrap loader so the classes that are in platform loader are not available in the agent. If you wish to use this class you'll need to modify https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/6a24080fe9f624510bdc1dc618bd0dc6364e1219/javaagent-bootstrap/src/main/java/io/opentelemetry/javaagent/bootstrap/AgentClassLoader.java#L463

**Comment by XiaoWeiKIN** [comment]
I added `gson` version `META-INF/maven/gosn` to `opentelemetry-java-instrumentation` and found that it works fine. 

```
artifactId=gson
groupId=com.google.code.gson
version=2.9.0

```


It dependence on some internal libraries,but when I built the distribution, I found that the `META-INF/maven/gosn` version was `2.8.2`
```
#Generated by Maven
#Tue Sep 19 18:42:34 PDT 2017
version=2.8.2
groupId=com.google.code.gson
artifactId=gson
```
I'm not sure if that's the problem.

**Comment by XiaoWeiKIN** [comment]
> The problem is that in jdk11 `java.sql.Time` is loaded by platform class loader, but the agent class loader only delegates to bootstrap loader so the classes that are in platform loader are not available in the agent. If you wish to use this class you'll need to modify
> 
> https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/6a24080fe9f624510bdc1dc618bd0dc6364e1219/javaagent-bootstrap/src/main/java/io/opentelemetry/javaagent/bootstrap/AgentClassLoader.java#L463

but I'm not using this package, I'm just using `gson`

**Comment by XiaoWeiKIN** [comment]
hi @mateuszrzeszutek ,i analyzed the project using `gradle build --scan` and I found that GSON 2.9.0 was replaced with 2.8.2, how can I avoid this. this is my analysis report. 
[analysis](https://gradle.com/s/nhpafl7puac4q)

**Comment by mateuszrzeszutek** [comment]
Hey @XiaoWeiKIN ,

I honestly have no idea why this happened and how to fix this, I can't really help you without seeing the build files.

Also, if you're still running into the problem with the `java.sql` module, please take a look at Lauri's comment: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6372#issuecomment-1196418687
If you modify the `AgentClassLoader` accordingly you should be able to fix it.
