### ISSUE TITLE
Java 2 Security permission error from ConfigPropertiesUtil

### ISSUE THREAD

**Issue by yasmin-aumeeruddy** [open-telemetry/opentelemetry-java-instrumentation#6416]
**Describe the bug**

Access to the system properties in [ConfigPropertiesUtil.java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/internal/ConfigPropertiesUtil.java) when Java Security Manager is enabled.

**Steps to reproduce**
Enable the Java Security Manager on your runtime and initialise the InstrumenterBuilder, e.g.

```
InstrumenterBuilder<ClientRequestContext, ClientResponseContext> builder = Instrumenter.builder(
                    openTelemetry,
                    "instrumenter builder",
                    HttpSpanNameExtractor.create(clientAttributesExtractor)); 
```

**What did you see?**
```
java.security.AccessControlException: access denied ("java.util.PropertyPermission" "otel.javaagent.debug" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at com.ibm.ws.kernel.launch.internal.MissingDoPrivDetectionSecurityManager.checkPermission(MissingDoPrivDetectionSecurityManager.java:45)
	at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1066)
	at java.base/java.lang.System.getProperty(System.java:816)
	at io.opentelemetry.instrumentation.api.internal.ConfigPropertiesUtil.getString(ConfigPropertiesUtil.java:24)
	at io.opentelemetry.instrumentation.api.internal.ConfigPropertiesUtil.getBoolean(ConfigPropertiesUtil.java:18)
	at io.opentelemetry.instrumentation.api.internal.SupportabilityMetrics.<clinit>(SupportabilityMetrics.java:31)
	at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.<clinit>(Instrumenter.java:65)`
```
**What version are you using?**
v.1.16.0

**Environment**
java.version = 11.0.11
java.runtime = OpenJDK Runtime Environment (11.0.11+9)
os = Mac OS X (11.4; x86_64) (en_GB)

**Suggested fix**
Change  [ConfigPropertiesUtil.java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/internal/ConfigPropertiesUtil.java#L23)

```
import java.security.AccessController;

AccessController.doPrivileged(new PrivilegedAction() {
  public static String getString(String propertyName) {
      String value = System.getProperty(propertyName);
      if (value != null) {
        return value;
      }
      return System.getenv(toEnvVarName(propertyName));
    }
});
```

And restrict access to ConfigPropertiesUtil by making it not public

**Comment by laurit** [comment]
@yasmin-aumeeruddy considering that SecurityManager and AccessController are deprecate for removal it is unlikely that this will be implemented unless there is a good reason. If this is something that you definitely need then please elaborate why you would need this. Consider joining the java + instrumentation SIG meeting and presenting your case there (you can find the meeting in opentelemetry google calendar). Also would adding doPrivileged to this one place really be enough? We don't use doPrivileged anywhere so there are other places where security manager could complain.

**Comment by trask** [comment]
hi @yasmin-aumeeruddy, are you able to create a `java.policy` to give the java agent the permissions it needs?
