### ISSUE TITLE
Encountering NPE on bootstrapping with java agent

### ISSUE THREAD

**Issue by yue9944882** [open-telemetry/opentelemetry-java-instrumentation#655]
as is shown in the following, the error won't actually influence the tracer from running:

```
[opentelemetry.auto.trace 2020-07-09 16:21:10:188 +0800] [main] ERROR io.opentelemetry.auto.tooling.VersionLogger - failed to read version stream
java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
        at io.opentelemetry.auto.tooling.VersionLogger.getVersionString(VersionLogger.java:48)
        at io.opentelemetry.auto.tooling.VersionLogger.logAllVersions(VersionLogger.java:32)
        at io.opentelemetry.auto.tooling.TracerInstaller.logVersionInfo(TracerInstaller.java:176)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.opentelemetry.auto.bootstrap.Agent.installAgentTracer(Agent.java:177)
        at io.opentelemetry.auto.bootstrap.Agent.start(Agent.java:88)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.opentelemetry.auto.bootstrap.AgentBootstrap.agentmain(AgentBootstrap.java:73)
        at io.opentelemetry.auto.bootstrap.AgentBootstrap.premain(AgentBootstrap.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
[opentelemetry.auto.trace 2020-07-09 16:21:10:189 +0800] [main] INFO io.opentelemetry.auto.tooling.VersionLogger - opentelemetry-auto - version: unknown
```

**Comment by trask** [comment]
Hi @yue9944882, thanks for reporting this! I have submitted a PR to fix #664
