### ISSUE TITLE
Lost default configuration for OTLP exporter endpoint

### ISSUE THREAD

**Issue by RashmiRam** [open-telemetry/opentelemetry-java-instrumentation#722]
Upon further digging, it is found out that endpoint to otel exporter to be configured via env var else results in the following error. 

Stacktrace for reference
`[opentelemetry.auto.trace 2020-07-17 17:27:26:373 +0530] [main] ERROR io.opentelemetry.auto.bootstrap.Agent - Throwable thrown while installing the agent tracer
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.opentelemetry.auto.bootstrap.Agent.installAgentTracer(Agent.java:175)
	at io.opentelemetry.auto.bootstrap.Agent.start(Agent.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.opentelemetry.auto.bootstrap.AgentBootstrap.agentmain(AgentBootstrap.java:73)
	at io.opentelemetry.auto.bootstrap.AgentBootstrap.premain(AgentBootstrap.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NullPointerException: channel
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:910)
	at io.opentelemetry.auto.shaded.io.grpc.stub.AbstractStub.<init>(AbstractStub.java:73)
	at io.opentelemetry.auto.shaded.io.grpc.stub.AbstractBlockingStub.<init>(AbstractBlockingStub.java:39)
	at io.opentelemetry.proto.collector.trace.v1.TraceServiceGrpc$TraceServiceBlockingStub.<init>(TraceServiceGrpc.java:185)
	at io.opentelemetry.proto.collector.trace.v1.TraceServiceGrpc$TraceServiceBlockingStub.<init>(TraceServiceGrpc.java:182)
	at io.opentelemetry.proto.collector.trace.v1.TraceServiceGrpc$2.newStub(TraceServiceGrpc.java:89)
	at io.opentelemetry.proto.collector.trace.v1.TraceServiceGrpc$2.newStub(TraceServiceGrpc.java:86)
	at io.opentelemetry.auto.shaded.io.grpc.stub.AbstractBlockingStub.newStub(AbstractBlockingStub.java:64)
	at io.opentelemetry.auto.shaded.io.grpc.stub.AbstractBlockingStub.newStub(AbstractBlockingStub.java:51)
	at io.opentelemetry.proto.collector.trace.v1.TraceServiceGrpc.newBlockingStub(TraceServiceGrpc.java:92)
	at io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter.<init>(OtlpGrpcSpanExporter.java:87)
	at io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter.<init>(OtlpGrpcSpanExporter.java:71)
	at io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter$Builder.build(OtlpGrpcSpanExporter.java:259)
	at io.opentelemetry.auto.exporters.otlp.OtlpSpanExporterFactory.fromConfig(OtlpSpanExporterFactory.java:31)
	at io.opentelemetry.auto.tooling.TracerInstaller.installExporter(TracerInstaller.java:133)
	at io.opentelemetry.auto.tooling.TracerInstaller.installExporters(TracerInstaller.java:65)
	at io.opentelemetry.auto.tooling.TracerInstaller.installAgentTracer(TracerInstaller.java:52)
	... 18 more`
Checked in [opentelemetry-java otel exporter](https://github.com/open-telemetry/opentelemetry-java/blob/v0.6.0/exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/OtlpGrpcSpanExporter.java#L171). There is no default managed channel pointing to the otel exporter endpoint. 

Probably, Can't we can change this documentation to make the endpoint setting as mandatory.

> By default OpenTelemetry Java agent uses OTLP exporter configured to send data to OpenTelemetry collector at localhost:55680.

**Comment by iNikem** [comment]
I would very much prefer to revive default configuration, which was lost during updating auto exporter factories to latest otel-java version.

**Comment by trask** [comment]
Thanks for reporting this @RashmiRam!

@iNikem makes sense to me 👍

**Comment by iNikem** [comment]
Now the question remain, where and how to plug that default value. I started to think that we should do that in otel-java repo. If otlp exporter is selected, and endpoint is not provided, then use the default one.

**Comment by trask** [comment]
I submitted PR to add this default in otel-java, and will carry over here once it's merged (btw @anuraaga I really like that we are on snapshot versions of otel-java now, way more motivating to submit PRs upstream in otel-java!)
