### ISSUE TITLE
Spring Webflux server side library instrumentation

### ISSUE THREAD

**Issue by jamesmoessis** [open-telemetry/opentelemetry-java-instrumentation#7436]
**Is your feature request related to a problem? Please describe.**

There isn't any library instrumentation for server side webflux currently. There is instrumentation for the agent, but there's a hole in the current featureset of library instrumentations for spring.

**Describe the solution you'd like**

There are examples of library instrumentation in Webflux.  For example, sleuth's [TraceWebFilter](https://github.com/spring-cloud/spring-cloud-sleuth/blob/a6e1dcbfcdde3cfe81bda8fdfb485536fa4540d3/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java#L62).

Something similar to that would be my initial thoughts on a solution. 

**Additional context**

Briefly discussed in slack: https://cloud-native.slack.com/archives/C0150QF88FL/p1671081502211849

**Comment by aschugunov** [comment]
@jamesmoessis Could you share discussion from slack here, please?

**Comment by trask** [comment]
> @jamesmoessis Could you share discussion from slack here, please?

James Moessis
  [1 month ago](https://cloud-native.slack.com/archives/C0150QF88FL/p1671081502211849)
How come webflux has no server library instrumentation? Is there a reason or it just hasn't been implemented?
9 replies


Trask Stalnaker
  [1 month ago](https://cloud-native.slack.com/archives/C0150QF88FL/p1671082369180749?thread_ts=1671081502.211849&cid=C0150QF88FL)
ya


James Moessis
  [1 month ago](https://cloud-native.slack.com/archives/C0150QF88FL/p1671083006755089?thread_ts=1671081502.211849&cid=C0150QF88FL)
:eyes: what's the reason?


Mateusz Rzeszutek
  [1 month ago](https://cloud-native.slack.com/archives/C0150QF88FL/p1671094247978899?thread_ts=1671081502.211849&cid=C0150QF88FL)
judging by how the javaagent instrumentation looks, server-side webflux might not provide enough hooks for us to correctly instrument it


Mateusz Rzeszutek
  [1 month ago](https://cloud-native.slack.com/archives/C0150QF88FL/p1671094271607639?thread_ts=1671081502.211849&cid=C0150QF88FL)
the javaagent instrumentation digs quite deep into somewhat internal stuff


James Moessis
  [1 month ago](https://cloud-native.slack.com/archives/C0150QF88FL/p1671146884943579?thread_ts=1671081502.211849&cid=C0150QF88FL)
Interesting


James Moessis
  [1 month ago](https://cloud-native.slack.com/archives/C0150QF88FL/p1671146898755679?thread_ts=1671081502.211849&cid=C0150QF88FL)
But there are other library instrumentations for webflux - for example in sleuth there's this: [https://github.com/spring-cloud/spring-cloud-sleuth/blob/a6e1dcbfcdde3cfe81bda8fdf[…]springframework/cloud/sleuth/instrument/web/TraceWebFilter.java](https://github.com/spring-cloud/spring-cloud-sleuth/blob/a6e1dcbfcdde3cfe81bda8fdfb485536fa4540d3/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java#L62)
[TraceWebFilter.java](https://github.com/spring-cloud/spring-cloud-sleuth/blob/a6e1dcbfcdde3cfe81bda8fdfb485536fa4540d3/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java)
public class TraceWebFilter implements WebFilter, Ordered, ApplicationContextAware {
<https://github.com/[spring-cloud/spring-cloud-sleuth](https://github.com/spring-cloud/spring-cloud-sleuth)|spring-cloud/spring-cloud-sleuth>spring-cloud/spring-cloud-sleuth | Added by [GitHub](https://cloud-native.slack.com/services/B01UCB8113P)
:+1:
2



James Moessis
  [1 month ago](https://cloud-native.slack.com/archives/C0150QF88FL/p1671147072236079?thread_ts=1671081502.211849&cid=C0150QF88FL)
It must be possible, right? Unless it's not compatible with the OTel context?


Trask Stalnaker
  [1 month ago](https://cloud-native.slack.com/archives/C0150QF88FL/p1671147246472129?thread_ts=1671081502.211849&cid=C0150QF88FL)
I would hope it would work also. it would be great to try out a webflux WebFilter implementation and run it through our standard server instrumentation battery of tests and see if there are any gaps.


James Moessis
  [1 month ago](https://cloud-native.slack.com/archives/C0150QF88FL/p1671147760107189?thread_ts=1671081502.211849&cid=C0150QF88FL)
Awesome, I'm willing to take a look at doing that. I've created the issue: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7436
[#7436 Spring Webflux server side library instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7436)
Is your feature request related to a problem? Please describe.
There isn't any library instrumentation for server side webflux currently. There is instrumentation for the agent, but there's a hole in the current featureset of library instrumentations for spring.
Describe the solution you'd like
There are examples of library instrumentation in Webflux. For example, sleuth's [TraceWebFilter](https://github.com/spring-cloud/spring-cloud-sleuth/blob/a6e1dcbfcdde3cfe81bda8fdfb485536fa4540d3/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java#L62).
Something similar to that would be my initial thoughts on a solution.
Additional context
Briefly discussed in slack: https://cloud-native.slack.com/archives/C0150QF88FL/p1671081502211849
Labels
enhancement
<https://github.com/[open-telemetry/opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation)|open-telemetry/opentelemetry-java-instrumentation>open-telemetry/opentelemetry-java-instrumentation | Dec 15th, 2022 | Added by [GitHub](https://cloud-native.slack.com/services/B01UCB8113P)
:heart:
1
:rocket:
1

**Comment by jamesmoessis** [comment]
@trask @mateuszrzeszutek 

I've been looking into how this might work. Below is my rough plan for a `WebFilter` for library instrumentation. I'm not a Webflux expert so I wouldn't mind some sanity checks here if you have the time.

The [WebFilter](https://github.com/spring-cloud/spring-cloud-sleuth/blob/a6e1dcbfcdde3cfe81bda8fdfb485536fa4540d3/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java#L62) interface defines a `Mono<Void> filter(ServerWebExchange exchange, WebFilterChain chain)`, in which we can wrap the existing filter chain, in order to intercept calls to `subscribe()` among other things. We don't have access to the chain returned by the handler itself, but we do have access to the filter chain. We wrap the filter chain `Mono<Void>` in such a way that: 

1. Context is retrieved via `Context.current()`. I am assuming there is no other context active, which I *think* is safe judging from how the agent instrumentation is written, but I wouldn't mind a sanity check on that one.
2. The instrumentation starts upon subscription (`subscribe()`) and ends during `onComplete()` as the subscription completes or errors.
3. We wrap the Mono returned by the filter. `instrumenter.start()` is called right before `WebFilter.filter().subscribe()` .
4. `Scope` is open during `WebFilter.filter().subscribe()` and then closed on exit of this method (it appears the `Controller` is synchronously called via `subscribe()`). 
5. After Scope is closed, the request can still be processing due to async nature.
6. We can wrap the subscriber used in the filter chain, and use that to call `instrumenter.end()` during `onSuccess()` and similar methods.
	1. Sleuth's `WebFilter` wraps the subscriber in this fashion.
	2. Note: the filter chain is separate to the chain returned by the handler.
7. I believe we have access to the handler via request attributes to construct span names/attributes if required. 
	1. Sleuth uses [this request attribute](https://github.com/spring-cloud/spring-cloud-sleuth/blob/a6e1dcbfcdde3cfe81bda8fdfb485536fa4540d3/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java#L293) to retrieve the handler, so it can use it's for the span name. I assume we can do the same thing.

**Comment by RahulPerri** [comment]
Hi I am facing this issue, by any chance this post is related to this issue?

at io.opentelemetry.instrumentation.spring.webflux.v5_3.internal.WebClientTracingFilter$MonoWebClientTrace.subscribe(WebClientTracingFilter.java:65)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
		at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64)
		at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97)
		at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91)
		at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64)
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
		at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64)
		at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97)
		at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91)
		at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2545)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341)
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2215)
		at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onSubscribe$0(TracingSubscriber.java:59)
		at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97)
		at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91)
		at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onSubscribe(TracingSubscriber.java:59)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)

**Comment by mateuszrzeszutek** [comment]
Hey @RahulPerri ,

Please open [a new bug report issue](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/new/choose), and include all the details about your problem -- ideally a repro scenario.
