### ISSUE TITLE
java.lang.NoClassDefFoundError: java/beans/IntrospectionException if `java.desktop` not included

### ISSUE THREAD

**Issue by bcmedeiros** [open-telemetry/opentelemetry-java-instrumentation#7580]
**Describe the bug**
In version 1.21.0 (this was probably introduced earlier than that), the agent is failing to initialize in the absence of the `java.desktop` module if you use a JDK built with jlink that does not include this module.

**Steps to reproduce**
1. Create a custom JDK distribution using jlink and do not include the `java.desktop` module.
2. Try to initialize the otel agent

**What did you expect to see?**
Initialization works successfully.

**What did you see instead?**
Initialization crashes with the following exception:
```
OpenTelemetry Javaagent failed to start
java.lang.NoClassDefFoundError: java/beans/IntrospectionException
    at org.yaml.snakeyaml.constructor.BaseConstructor.getPropertyUtils(BaseConstructor.java:645)
    at org.yaml.snakeyaml.constructor.BaseConstructor.addTypeDescription(BaseConstructor.java:664)
    at org.yaml.snakeyaml.constructor.Constructor.<init>(Constructor.java:134)
    at org.yaml.snakeyaml.constructor.Constructor.<init>(Constructor.java:79)
    at org.yaml.snakeyaml.constructor.Constructor.<init>(Constructor.java:60)
    at org.yaml.snakeyaml.Yaml.<init>(Yaml.java:64)
    at io.opentelemetry.instrumentation.spring.resources.SpringBootServiceNameDetector.parseNameFromYaml(SpringBootServiceNameDetector.java:178)
    at io.opentelemetry.instrumentation.spring.resources.SpringBootServiceNameDetector.loadFromClasspath(SpringBootServiceNameDetector.java:259)
    at io.opentelemetry.instrumentation.spring.resources.SpringBootServiceNameDetector.findByClasspathApplicationYaml(SpringBootServiceNameDetector.java:158)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
    at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
    at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
    at io.opentelemetry.instrumentation.spring.resources.SpringBootServiceNameDetector.createResource(SpringBootServiceNameDetector.java:92)
    at io.opentelemetry.sdk.autoconfigure.ResourceConfiguration.configureResource(ResourceConfiguration.java:59)
```

**What version are you using?**
1.21.0+ (might have been introduced before that)

**Environment**
Compiler: (e.g., "Adoptium 11.0.7")
OS: (e.g., "Alpine Linux")

**Comment by bcmedeiros** [comment]
If you don't care about Spring, there is a workaround, just initialize the agent with:
```
-Dotel.java.disabled.resource.providers=io.opentelemetry.instrumentation.spring.resources.SpringBootServiceNameDetector
```
