### ISSUE TITLE
Opentracing Shim Propagation Errors

### ISSUE THREAD

**Issue by FrankSpitulski** [open-telemetry/opentelemetry-java-instrumentation#764]
The https://github.com/open-telemetry/opentelemetry-java/tree/master/opentracing_shim throws the following errors when it tries to inject context, but this is supposed to be a supported use case as per @trask's guidance. I invoked this by using the 0.6.0 agent, and shim and performing an okhttp opentracing request.

```
[opentelemetry.auto.trace 2020-07-22 17:29:07:517 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.tooling.Instrumenter$Default - Applying instrumentation: opentelemetry-api -- io.opentelemetry.auto.instrumentation.opentelemetryapi.TracingContextUtilsInstrumentation on sun.misc.Launcher$AppClassLoader@18b4aac2
[opentelemetry.auto.trace 2020-07-22 17:29:07:517 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.tooling.HelperInjector - Injecting classes onto classloader sun.misc.Launcher$AppClassLoader@18b4aac2 -> [io.opentelemetry.auto.instrumentation.opentelemetryapi.context.ContextUtils, io.opentelemetry.auto.instrumentation.opentelemetryapi.context.UnshadedScope, io.opentelemetry.auto.instrumentation.opentelemetryapi.context.NoopScope, io.opentelemetry.auto.instrumentation.opentelemetryapi.context.propagation.UnshadedContextPropagators, io.opentelemetry.auto.instrumentation.opentelemetryapi.context.propagation.UnshadedHttpTextFormat, io.opentelemetry.auto.instrumentation.opentelemetryapi.context.propagation.UnshadedHttpTextFormat$UnshadedSetter, io.opentelemetry.auto.instrumentation.opentelemetryapi.context.propagation.UnshadedHttpTextFormat$UnshadedGetter, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedBatchRecorder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleCounter, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleCounter$BoundInstrument, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleCounter$Builder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleSumObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleSumObserver$Builder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleSumObserver$ShadedResultDoubleSumObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleSumObserver$UnshadedResultDoubleSumObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleUpDownCounter, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleUpDownCounter$BoundInstrument, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleUpDownCounter$Builder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleUpDownSumObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleUpDownSumObserver$Builder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleUpDownSumObserver$ShadedResultDoubleUpDownSumObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleUpDownSumObserver$UnshadedResultDoubleUpDownSumObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleValueObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleValueObserver$Builder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleValueObserver$ShadedResultDoubleValueObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleValueObserver$UnshadedResultDoubleValueObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleValueRecorder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleValueRecorder$BoundInstrument, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedDoubleValueRecorder$Builder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongCounter, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongCounter$BoundInstrument, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongCounter$Builder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongSumObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongSumObserver$Builder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongSumObserver$ShadedResultLongSumObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongSumObserver$UnshadedResultLongSumObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongUpDownCounter, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongUpDownCounter$BoundInstrument, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongUpDownCounter$Builder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongUpDownSumObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongUpDownSumObserver$Builder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongUpDownSumObserver$ShadedResultLongUpDownSumObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongUpDownSumObserver$UnshadedResultLongUpDownSumObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongValueObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongValueObserver$Builder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongValueObserver$ShadedResultLongValueObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongValueObserver$UnshadedResultLongValueObserver, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongValueRecorder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongValueRecorder$BoundInstrument, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedLongValueRecorder$Builder, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedMeter, io.opentelemetry.auto.instrumentation.opentelemetryapi.metrics.UnshadedMeterProvider, io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.Bridging, io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.Bridging$1, io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.Bridging$2, io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.TracingContextUtils, io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.UnshadedSpan, io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.UnshadedSpan$Builder, io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.UnshadedTracer, io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.UnshadedTracerProvider, io.opentelemetry.auto.instrumentation.opentelemetryapi.LabelsShader, io.opentelemetry.auto.instrumentation.opentelemetryapi.LabelsShader$Consumer]
[opentelemetry.auto.trace 2020-07-22 17:29:07:519 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.tooling.HelperInjector - Injecting classes onto classloader <bootstrap> -> [io.opentelemetry.auto.bootstrap.instrumentation.context.FieldBackedProvider$ContextAccessor$io$grpc$Context$io$opentelemetry$auto$shaded$io$grpc$Context]
[opentelemetry.auto.trace 2020-07-22 17:29:07:521 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.tooling.HelperInjector - Injecting classes onto classloader <bootstrap> -> [io.opentelemetry.auto.bootstrap.instrumentation.context.FieldBackedProvider$ContextStore$io$grpc$Context$io$opentelemetry$auto$shaded$io$grpc$Context]
[opentelemetry.auto.trace 2020-07-22 17:29:07:526 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.tooling.context.FieldBackedProvider - Found context-store access in io.opentelemetry.auto.instrumentation.opentelemetryapi.TracingContextUtilsInstrumentation
[opentelemetry.auto.trace 2020-07-22 17:29:07:526 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.tooling.context.FieldBackedProvider - Rewriting context-store map fetch for instrumenter io.opentelemetry.auto.instrumentation.opentelemetryapi.TracingContextUtilsInstrumentation: io.grpc.Context -> io.opentelemetry.auto.shaded.io.grpc.Context
[opentelemetry.auto.trace 2020-07-22 17:29:07:527 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.tooling.context.FieldBackedProvider - Found context-store access in io.opentelemetry.auto.instrumentation.opentelemetryapi.TracingContextUtilsInstrumentation
[opentelemetry.auto.trace 2020-07-22 17:29:07:527 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.tooling.context.FieldBackedProvider - Rewriting context-store map fetch for instrumenter io.opentelemetry.auto.instrumentation.opentelemetryapi.TracingContextUtilsInstrumentation: io.grpc.Context -> io.opentelemetry.auto.shaded.io.grpc.Context
[opentelemetry.auto.trace 2020-07-22 17:29:07:527 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.tooling.context.FieldBackedProvider - Found context-store access in io.opentelemetry.auto.instrumentation.opentelemetryapi.TracingContextUtilsInstrumentation
[opentelemetry.auto.trace 2020-07-22 17:29:07:527 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.tooling.context.FieldBackedProvider - Rewriting context-store map fetch for instrumenter io.opentelemetry.auto.instrumentation.opentelemetryapi.TracingContextUtilsInstrumentation: io.grpc.Context -> io.opentelemetry.auto.shaded.io.grpc.Context
[opentelemetry.auto.trace 2020-07-22 17:29:07:527 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.tooling.AgentInstaller$TransformLoggingListener - Transformed io.opentelemetry.trace.TracingContextUtils -- sun.misc.Launcher$AppClassLoader@18b4aac2
[opentelemetry.auto.trace 2020-07-22 17:29:07:527 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.TracingContextUtils - unexpected span: DefaultSpan
java.lang.Exception: unexpected span
	at io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.TracingContextUtils.withSpan(TracingContextUtils.java:41)
	at io.opentelemetry.trace.TracingContextUtils.withSpan(TracingContextUtils.java:44)
	at io.opentelemetry.opentracingshim.Propagation.injectTextFormat(Propagation.java:37)
	at io.opentelemetry.opentracingshim.TracerShim.inject(TracerShim.java:79)
	at io.opentracing.util.GlobalTracer.inject(GlobalTracer.java:199)
	at io.opentracing.contrib.okhttp3.TracingCallFactory$NetworkInterceptor.intercept(TracingCallFactory.java:102)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:219)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:219)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at io.opentracing.contrib.okhttp3.TracingCallFactory$1.intercept(TracingCallFactory.java:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
[opentelemetry.auto.trace 2020-07-22 17:29:07:532 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.tooling.AgentInstaller$TransformLoggingListener - Transformed io.grpc.Context$CancellableContext -- sun.misc.Launcher$AppClassLoader@18b4aac2
[opentelemetry.auto.trace 2020-07-22 17:29:07:533 -0700] [http-nio-8080-exec-2] DEBUG io.opentelemetry.auto.instrumentation.opentelemetryapi.context.propagation.UnshadedHttpTextFormat - unexpected context: io.grpc.Context@5839d0b4
java.lang.Exception: unexpected context
	at io.opentelemetry.auto.instrumentation.opentelemetryapi.context.propagation.UnshadedHttpTextFormat.inject(UnshadedHttpTextFormat.java:68)
	at io.opentelemetry.opentracingshim.Propagation.injectTextFormat(Propagation.java:43)
	at io.opentelemetry.opentracingshim.TracerShim.inject(TracerShim.java:79)
	at io.opentracing.util.GlobalTracer.inject(GlobalTracer.java:199)
	at io.opentracing.contrib.okhttp3.TracingCallFactory$NetworkInterceptor.intercept(TracingCallFactory.java:102)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:219)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:219)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at io.opentracing.contrib.okhttp3.TracingCallFactory$1.intercept(TracingCallFactory.java:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
```

**Comment by trask** [comment]
hey @FrankSpitulski, can you create a sample app / github repo that we can use to reproduce / troubleshoot this issue?

**Comment by FrankSpitulski** [comment]
here you go @trask, thanks for taking a look. https://github.com/FrankSpitulski/rest-api-example/tree/ot-shim-example

**Comment by iNikem** [comment]
As a first step I would recommend to upgrade `lightstep/opentelemetry-exporter-java` to use otel-java 0.7.0. And then use that together with 0.7.0 version of auto-instrumentation. So far the most common source of bugs between two repos is version mismatch.

**Comment by FrankSpitulski** [comment]
@iNikem I've pushed an update to my repo to remove the external exporter jar so it is not a variable. It still has the same lack of propagation headers when using the shim.

**Comment by iNikem** [comment]
Yeah, I now see the problem. `io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.Bridging#toShadedOrNull(unshaded.io.opentelemetry.trace.Span)` does not work with `DefaultSpan` created by `io.opentelemetry.opentracingshim.Propagation#injectTextFormat`.

@trask can you give some advice? Our shading-unshading business is still somewhat confusing to me :(

**Comment by trask** [comment]
will review tomorrow 👍

**Comment by anuraaga** [comment]
Stepped through a bit and yeah, it looks like we should instrument `DefaultSpan.create` to return a wrapper span same as what we do for tracers. There doesn't seem to be a need for a distinction there.

**Comment by anuraaga** [comment]
Looked into instrumenting `DefaultSpan.create` and found an SDK change is probably needed first - https://github.com/open-telemetry/opentelemetry-java/pull/1519

**Comment by iNikem** [comment]
@anuraaga have you changes solved this issue?

**Comment by anuraaga** [comment]
Don't think so - just starting up the repro app to debug some more :)
