### ISSUE TITLE
Agent does not start in OpenJDK 21 | Unable to make protected final java.lang.Class accessible

### ISSUE THREAD

**Issue by shrinidhi111** [open-telemetry/opentelemetry-java-instrumentation#7694]
**Describe the bug**

Upgraded OpenJDK to the latest version, after an internal exercise. Our project works fine but once it was deployed noticed the telemetry did not start

**Steps to reproduce**

Use the Java instrumentation on docker image `openjdk:21-ea-jdk`

**What did you expect to see?**

Telemetry should start

**What did you see instead?**

```
auth.1.afb729mhouxe@e2e-75-115    | [otel.javaagent 2023-01-31 10:37:51:695 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.22.1
auth.1.afb729mhouxe@e2e-75-115    | OpenTelemetry Javaagent failed to start
auth.1.afb729mhouxe@e2e-75-115    | java.lang.ExceptionInInitializerError
auth.1.afb729mhouxe@e2e-75-115    | 	at io.opentelemetry.javaagent.tooling.muzzle.AgentTooling.<clinit>(AgentTooling.java:22)
auth.1.afb729mhouxe@e2e-75-115    | 	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:139)
auth.1.afb729mhouxe@e2e-75-115    | 	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:94)
auth.1.afb729mhouxe@e2e-75-115    | 	at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:78)
auth.1.afb729mhouxe@e2e-75-115    | 	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:35)
auth.1.afb729mhouxe@e2e-75-115    | 	at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:57)
auth.1.afb729mhouxe@e2e-75-115    | 	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:45)
auth.1.afb729mhouxe@e2e-75-115    | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
auth.1.afb729mhouxe@e2e-75-115    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
auth.1.afb729mhouxe@e2e-75-115    | 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
auth.1.afb729mhouxe@e2e-75-115    | 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
auth.1.afb729mhouxe@e2e-75-115    | Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @7382f612
auth.1.afb729mhouxe@e2e-75-115    | 	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
auth.1.afb729mhouxe@e2e-75-115    | 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
auth.1.afb729mhouxe@e2e-75-115    | 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
auth.1.afb729mhouxe@e2e-75-115    | 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:201)
auth.1.afb729mhouxe@e2e-75-115    | 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:195)
auth.1.afb729mhouxe@e2e-75-115    | 	at io.opentelemetry.javaagent.tooling.muzzle.AgentCachingPoolStrategy.getFindLoadedClassMethod(AgentCachingPoolStrategy.java:114)
auth.1.afb729mhouxe@e2e-75-115    | 	at io.opentelemetry.javaagent.tooling.muzzle.AgentCachingPoolStrategy.<clinit>(AgentCachingPoolStrategy.java:57)
auth.1.afb729mhouxe@e2e-75-115    | 	... 11 more

```

**What version are you using?**

`1.22.1`

**Environment**

Docker Image : openjdk:21-ea-jdk

**Additional context**

**Comment by laurit** [comment]
Byte-buddy doesn't support jdk21 yet. It doesn't detect the jdk version correctly so we skip running some code that would prevent this exception. I guess we could catch this to prevent agent startup from failing but it is hard to predict whether something else would fail later on.

**Comment by shrinidhi111** [comment]
As of version `1.22.1`, which is the highest JDK that it supports? Readme says `any Java 8+ application` so I assumed any JDK 8+ too

**Comment by laurit** [comment]
The lates version we currently test with is jdk 19 which is the latest released version.

**Comment by shrinidhi111** [comment]
> 

Thank you!

**Comment by Starefossen** [comment]
This still seams to be a problem with applications running java 21

**Comment by laurit** [comment]
@Starefossen we run tests with java 21 and they work. Please create a new issue, include steps to reproduce.

**Comment by maradanasai** [comment]
@laurit This still seams to be an issue with jdk 24

docker image: bellsoft/liberica-openjre-debian:24-cds

```
2025-08-13 13:03:08.347	
Picked up JAVA_TOOL_OPTIONS:  -javaagent:/otel-auto-instrumentation-java-snap-engine/javaagent.jar
2025-08-13 13:03:08.634	
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2025-08-13 13:03:08.857	
[otel.javaagent 2025-08-13 07:33:08:855 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.33.6
2025-08-13 13:03:09.248	
WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
2025-08-13 13:03:09.248	
WARNING: sun.misc.Unsafe::objectFieldOffset has been called by io.opentelemetry.internal.shaded.jctools.util.UnsafeAccess (file:/otel-auto-instrumentation-java-snap-engine/javaagent.jar)
2025-08-13 13:03:09.248	
WARNING: Please consider reporting this to the maintainers of class io.opentelemetry.internal.shaded.jctools.util.UnsafeAccess
2025-08-13 13:03:09.248	
WARNING: sun.misc.Unsafe::objectFieldOffset will be removed in a future release
2025-08-13 13:03:09.427	
OpenTelemetry Javaagent failed to start
2025-08-13 13:03:09.427	
java.lang.ExceptionInInitializerError
2025-08-13 13:03:09.427	
	at io.opentelemetry.javaagent.tooling.muzzle.AgentTooling.<clinit>(AgentTooling.java:23)
2025-08-13 13:03:09.427	
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:151)
2025-08-13 13:03:09.427	
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:103)

2025-08-13 13:03:09.427	
	at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:98)
2025-08-13 13:03:09.427	
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer$1.run(AgentInitializer.java:53)
2025-08-13 13:03:09.427	
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer$1.run(AgentInitializer.java:47)
2025-08-13 13:03:09.427	
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.execute(AgentInitializer.java:68)
2025-08-13 13:03:09.427	
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:46)
2025-08-13 13:03:09.427	
	at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:57)
2025-08-13 13:03:09.427	
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:45)
2025-08-13 13:03:09.427	
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
2025-08-13 13:03:09.427	
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2025-08-13 13:03:09.427	
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
2025-08-13 13:03:09.427	
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
2025-08-13 13:03:09.427	
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @4909b8da
2025-08-13 13:03:09.427	
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(Unknown Source)
2025-08-13 13:03:09.427	
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
2025-08-13 13:03:09.427	
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
2025-08-13 13:03:09.428	
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
2025-08-13 13:03:09.428	
	at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
2025-08-13 13:03:09.428	
	at io.opentelemetry.javaagent.tooling.muzzle.AgentCachingPoolStrategy.getFindLoadedClassMethod(AgentCachingPoolStrategy.java:115)
2025-08-13 13:03:09.428	
	at io.opentelemetry.javaagent.tooling.muzzle.AgentCachingPoolStrategy.<clinit>(AgentCachingPoolStrategy.java:58)
2025-08-13 13:03:09.428	
	... 14 more
```
