### ISSUE TITLE
[AWS] NPE for `ReceiveMessageRequest` when instrumentation hasn't started

### ISSUE THREAD

**Issue by awelless** [open-telemetry/opentelemetry-java-instrumentation#7903]
When instrumentation hasn't started for `ReceiveMessageRequest` in `afterMarshalling` hook, request fails later in `afterExecution` phase, because `httpRequest` is `null` in `ExecutionAttributes`.

<details>
  <summary>Stack trace</summary>
```
java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.http.SdkHttpRequest.method()" because "httpRequest" is null
	at io.opentelemetry.instrumentation.awssdk.v2_2.AwsSdkHttpAttributesGetter.getMethod(AwsSdkHttpAttributesGetter.java:38)
	at io.opentelemetry.instrumentation.awssdk.v2_2.AwsSdkHttpAttributesGetter.getMethod(AwsSdkHttpAttributesGetter.java:18)
	at io.opentelemetry.instrumentation.api.instrumenter.http.HttpCommonAttributesExtractor.onStart(HttpCommonAttributesExtractor.java:47)
	at io.opentelemetry.instrumentation.api.instrumenter.http.HttpClientAttributesExtractor.onStart(HttpClientAttributesExtractor.java:93)
	at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.doStart(Instrumenter.java:176)
	at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.start(Instrumenter.java:129)
	at io.opentelemetry.instrumentation.awssdk.v2_2.TracingExecutionInterceptor.createConsumerSpan(TracingExecutionInterceptor.java:196)
	at io.opentelemetry.instrumentation.awssdk.v2_2.TracingExecutionInterceptor.afterConsumerResponse(TracingExecutionInterceptor.java:181)
	at io.opentelemetry.instrumentation.awssdk.v2_2.TracingExecutionInterceptor.afterExecution(TracingExecutionInterceptor.java:163)
	at io.opentelemetry.instrumentation.awssdk.v2_2.autoconfigure.TracingExecutionInterceptor.afterExecution(TracingExecutionInterceptor.java:134)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.lambda$afterExecution$10(ExecutionInterceptorChain.java:195)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.reverseForEach(ExecutionInterceptorChain.java:237)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.afterExecution(ExecutionInterceptorChain.java:195)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AfterExecutionInterceptorsStage.execute(AfterExecutionInterceptorsStage.java:26)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$AsyncRequestPipelineWrapper.lambda$execute$0(RequestPipelineBuilder.java:229)
	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeFunction$3(FunctionalUtils.java:92)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	```
</details>

However, we could put `SDK_HTTP_REQUEST_ATTRIBUTE` even if instrumentation shouldn't start. It seems, this should resolve the issue

**Comment by frombrest** [comment]
I still see this problem in `opentelemetry-aws-sdk-2.2-1.27.0-alpha.jar`

```
. . .
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Cannot invoke "software.amazon.awssdk.http.SdkHttpRequest.method()" because "httpRequest" is null
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
	at software.amazon.awssdk.core.internal.util.ThrowableUtils.asSdkException(ThrowableUtils.java:98)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:177)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:105)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.completeResponseFuture(MakeAsyncHttpRequestStage.java:238)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:163)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	... 3 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.http.SdkHttpRequest.method()" because "httpRequest" is null
	at io.opentelemetry.instrumentation.awssdk.v2_2.AwsSdkHttpAttributesGetter.getHttpRequestMethod(AwsSdkHttpAttributesGetter.java:31)
	at io.opentelemetry.instrumentation.awssdk.v2_2.AwsSdkHttpAttributesGetter.getHttpRequestMethod(AwsSdkHttpAttributesGetter.java:17)
	at io.opentelemetry.instrumentation.api.instrumenter.http.HttpCommonAttributesExtractor.onStart(HttpCommonAttributesExtractor.java:48)
	at io.opentelemetry.instrumentation.api.instrumenter.http.HttpClientAttributesExtractor.onStart(HttpClientAttributesExtractor.java:107)
	at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.doStart(Instrumenter.java:178)
	at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.start(Instrumenter.java:131)
	at io.opentelemetry.instrumentation.awssdk.v2_2.TracingExecutionInterceptor.createConsumerSpan(TracingExecutionInterceptor.java:338)
	at io.opentelemetry.instrumentation.awssdk.v2_2.TracingExecutionInterceptor.afterConsumerResponse(TracingExecutionInterceptor.java:318)
	at io.opentelemetry.instrumentation.awssdk.v2_2.TracingExecutionInterceptor.afterExecution(TracingExecutionInterceptor.java:292)
	at io.opentelemetry.instrumentation.awssdk.v2_2.autoconfigure.TracingExecutionInterceptor.afterExecution(TracingExecutionInterceptor.java:139)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.lambda$afterExecution$10(ExecutionInterceptorChain.java:195)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.reverseForEach(ExecutionInterceptorChain.java:237)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.afterExecution(ExecutionInterceptorChain.java:195)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AfterExecutionInterceptorsStage.execute(AfterExecutionInterceptorsStage.java:26)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$AsyncRequestPipelineWrapper.lambda$execute$0(RequestPipelineBuilder.java:229)
	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeFunction$3(FunctionalUtils.java:92)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 20 common frames omitted
```

**Comment by laurit** [comment]
@frombrest please create a new issue, also provide a minimal sample app that reproduces the issue

**Comment by frombrest** [comment]
> @frombrest please create a new issue, also provide a minimal sample app that reproduces the issue

Done: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8895
