### ISSUE TITLE
Sporadic test failure (1x): GrpcStreamingTest

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#805]
```
java.io.IOException: Failed to bind
	at io.grpc.netty.NettyServer.start(NettyServer.java:182)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:148)
	at GrpcStreamingTest.test conversation #name(GrpcStreamingTest.groovy:74)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/2162/workflows/8fefb78f-18e5-4d71-b34f-70ccb3148c22/jobs/14524

**Comment by trask** [comment]
Closing per #925
