### ISSUE TITLE
Grizzly tests log SEVERE error, even when they pass

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#845]
Grizzly tests log SEVERE error, even when they pass.

May point to a real issue in the instrumentation (as opposed to just issue with the tests).

Marking as `p3` since the Grizzly instrumentation is disabled by default.

```
Jul 30, 2020 7:08:56 PM io.grpc.ThreadLocalContextStorage detach
SEVERE: Context was not attached when detaching
java.lang.Throwable
	at io.grpc.ThreadLocalContextStorage.detach(ThreadLocalContextStorage.java:48)
	at io.grpc.Context.detach(Context.java:463)
	at io.opentelemetry.context.ContextUtils$ContextInScope.close(ContextUtils.java:56)
	at io.opentelemetry.auto.instrumentation.api.SpanWithScope.closeScope(SpanWithScope.java:97)
	at org.glassfish.grizzly.http.HttpCodecFilter.handleRead(HttpCodecFilter.java:585)
```

E.g. https://14989-210933087-gh.circle-artifacts.com/0/reports/instrumentation/grizzly-2.0/tests/integrationTest/classes/GrizzlyTest.html (look at the `Standard error` tab)

**Comment by iNikem** [comment]
It is issue with instrumentation. Seems to be broken by me when translated from decorator to tracer.

**Comment by trask** [comment]
Closing, I don't see this particular error anymore, and there's a new issue tracking Grizzly context propagation with better details now.
