### ISSUE TITLE
gRPC instrumentation - `GrpcNetServerAttributesGetter` throws `AbstractMethodError` on request

### ISSUE THREAD

**Issue by thomm-o** [open-telemetry/opentelemetry-java-instrumentation#9023]
**Describe the bug**
When making a gRPC request after adding telemetry to the netty server, an `IllegalStateException` is thrown resulting from an `AbstractMethodError` - in further investigation the class appears to extend `NetServerAttributesGetter` entirely incorrectly (not sure if this is due to some versioning issues on my end.

Related versions:
```xml
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-netty</artifactId>
    <version>1.56.1</version>
</dependency>
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-protobuf</artifactId>
    <version>1.56.1</version>
</dependency>
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-stub</artifactId>
    <version>1.56.1</version>
</dependency>

<dependency>
    <groupId>io.opentelemetry.instrumentation</groupId>
    <artifactId>opentelemetry-grpc-1.6</artifactId>
    <version>1.28.0-alpha</version>
</dependency>
```

I am using `com.google.protobuf:protoc:3.23.4:exe:${os.detected.classifier}` in my `protobuf-maven-plugin` configuration.

The error:
```
java.lang.IllegalStateException: java.lang.AbstractMethodError: Receiver class io.opentelemetry.instrumentation.grpc.v1_6.internal.GrpcNetServerAttributesGetter does not define or inherit an implementation of the resolved method 'abstract java.lang.String getTransport(java.lang.Object)' of interface io.opentelemetry.instrumentation.api.instrumenter.net.NetServerAttributesGetter.
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:617) ~[grpc-core-1.56.1.jar:1.56.1]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603) ~[grpc-core-1.56.1.jar:1.56.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.56.1.jar:1.56.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.56.1.jar:1.56.1]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]
Caused by: java.lang.AbstractMethodError: Receiver class io.opentelemetry.instrumentation.grpc.v1_6.internal.GrpcNetServerAttributesGetter does not define or inherit an implementation of the resolved method 'abstract java.lang.String getTransport(java.lang.Object)' of interface io.opentelemetry.instrumentation.api.instrumenter.net.NetServerAttributesGetter.
	at io.opentelemetry.instrumentation.api.instrumenter.net.internal.InternalNetServerAttributesExtractor.onStart(InternalNetServerAttributesExtractor.java:36) ~[opentelemetry-instrumentation-api-semconv-1.24.0-alpha.jar:1.24.0-alpha]
	at io.opentelemetry.instrumentation.api.instrumenter.net.NetServerAttributesExtractor.onStart(NetServerAttributesExtractor.java:39) ~[opentelemetry-instrumentation-api-semconv-1.24.0-alpha.jar:1.24.0-alpha]
	at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.doStart(Instrumenter.java:178) ~[opentelemetry-instrumentation-api-1.28.0.jar:1.28.0]
	at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.start(Instrumenter.java:131) ~[opentelemetry-instrumentation-api-1.28.0.jar:1.28.0]
	at io.opentelemetry.instrumentation.api.instrumenter.PropagatingFromUpstreamInstrumenter.start(PropagatingFromUpstreamInstrumenter.java:31) ~[opentelemetry-instrumentation-api-1.28.0.jar:1.28.0]
	at io.opentelemetry.instrumentation.grpc.v1_6.TracingServerInterceptor.interceptCall(TracingServerInterceptor.java:55) ~[opentelemetry-grpc-1.6-1.28.0-alpha.jar:1.28.0-alpha]
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:269) ~[grpc-api-1.56.1.jar:1.56.1]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:701) ~[grpc-core-1.56.1.jar:1.56.1]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:408) ~[grpc-core-1.56.1.jar:1.56.1]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:613) ~[grpc-core-1.56.1.jar:1.56.1]
	... 6 common frames omitted
```

**What did you expect to see?**
Telemetry working as expected and gRPC requests being performed successfully

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version are you using?**
1.28.0-alpha

**Environment**
Compiler: OpenJDK Corretto-20.0.1.9.1 (build 20.0.1+9-FR)
OS: macOS Ventura 13.4.1

**Comment by trask** [comment]
hi @thomm-o! it looks like you are using mismatched artifact versions:

* `opentelemetry-instrumentation-api-semconv-1.24.0-alpha.jar:1.24.0-alpha`
* `opentelemetry-instrumentation-api-1.28.0.jar:1.28.0`
* `opentelemetry-grpc-1.6-1.28.0-alpha.jar:1.28.0-alpha`
