### ISSUE TITLE
Connection has been closed BEFORE send operation (Spring Webflux)

### ISSUE THREAD

**Issue by davidlopezcarrasco** [open-telemetry/opentelemetry-java-instrumentation#9488]
### Describe the bug

The following exception has started to appear randomly to one of our Spring WebFlux services after adding the opentelemetry instrumentation (1.29.0). 

Responses are not getting to clients and traces don't show http.status_code attributes at all.

```
reactor.netty.channel.AbortedException: Connection has been closed BEFORE send operation 
at reactor.netty.channel.AbortedException.beforeSend(AbortedException.java:59) Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: Error has been observed 
at the following site(s): *__checkpoint 
Handler com.flywire.application.http.CompleteAuthentications@606c131a [DispatcherHandler] *__checkpoint 
org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain] *__checkpoint 
org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain] *__checkpoint 
HTTP POST "/b96f7f2a-f802-412b-ac24-757c339dd84b?action=VERIFY" [ExceptionHandlingWebHandler] Original Stack Trace: 
at reactor.netty.channel.AbortedException.beforeSend(AbortedException.java:59) 
at reactor.netty.http.HttpOperations.then(HttpOperations.java:171) 
at reactor.netty.ReactorNetty$OutboundThen.<init>(ReactorNetty.java:735) 
at reactor.netty.ReactorNetty$OutboundThen.<init>(ReactorNetty.java:728) 
at reactor.netty.NettyOutbound.then(NettyOutbound.java:358) 
at reactor.netty.http.HttpOperations.send(HttpOperations.java:115) 
at org.springframework.http.server.reactive.ReactorServerHttpResponse.writeWithInternal(ReactorServerHttpResponse.java:93) 
at org.springframework.http.server.reactive.AbstractServerHttpResponse.lambda$writeWith$2(AbstractServerHttpResponse.java:190) 
at org.springframework.http.server.reactive.AbstractServerHttpResponse.doCommit(AbstractServerHttpResponse.java:266) 
at org.springframework.http.server.reactive.AbstractServerHttpResponse.lambda$writeWith$5(AbstractServerHttpResponse.java:187) 
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64) 
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137) 
at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) 
at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2545) 
at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136) 
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.request(FluxHide.java:152) 
at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194) 
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.request(FluxHide.java:152) 
at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139) 
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.request(FluxHide.java:152) 
at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136) 
at reactor.core.publisher.MonoFlatMap$FlatMapInner.onSubscribe(MonoFlatMap.java:291) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onSubscribe$0(TracingSubscriber.java:59) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onSubscribe(TracingSubscriber.java:59) 
at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onSubscribe(FluxContextWrite.java:101) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onSubscribe$0(TracingSubscriber.java:59) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onSubscribe(TracingSubscriber.java:59) 
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onSubscribe(FluxHide.java:122) 
at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:152) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onSubscribe$0(TracingSubscriber.java:59) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onSubscribe(TracingSubscriber.java:59) 
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onSubscribe(FluxHide.java:122) 
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onSubscribe$0(TracingSubscriber.java:59) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onSubscribe(TracingSubscriber.java:59) 
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onSubscribe(FluxHide.java:122) 
at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onSubscribe(FluxContextWrite.java:101) 
at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) 
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) 
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64) 
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64) 
at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2811) 
at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onComplete(TracingSubscriber.java:82) 
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152) 
at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2547) 
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171) 
at reactor.core.publisher.MonoSingle$SingleSubscriber.doOnRequest(MonoSingle.java:103) 
at reactor.core.publisher.Operators$MonoInnerProducerBase.request(Operators.java:2878) 
at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341) 
at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2215) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onSubscribe$0(TracingSubscriber.java:59) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onSubscribe(TracingSubscriber.java:59) 
at reactor.core.publisher.MonoSingle$SingleSubscriber.onSubscribe(MonoSingle.java:115) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onSubscribe$0(TracingSubscriber.java:59) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onSubscribe(TracingSubscriber.java:59) 
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) 
at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68) 
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) 
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64) 
at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64) 
at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64) 
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64) 
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64) 
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137) 
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64) 
at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onNext(MonoSubscribeOn.java:146) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64) 
at reactor.core.publisher.MonoCallable$MonoCallableSubscription.request(MonoCallable.java:156) 
at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.trySchedule(MonoSubscribeOn.java:189) 
at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onSubscribe(MonoSubscribeOn.java:134) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onSubscribe$0(TracingSubscriber.java:59) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:97) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91) 
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onSubscribe(TracingSubscriber.java:59) 
at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:48) 
at reactor.core.publisher.Mono.subscribe(Mono.java:4495) 
at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) 
at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) 
at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) 
at java.base/java.util.concurrent.FutureTask.run(Unknown Source) 
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) 
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
at java.base/java.lang.Thread.run(Unknown Source)

```

We suspect it may be related to the collector closing unexpectedly connections while the http client in the instrumentation tries to keep alive the connections, which leads to a http connection reset equivalent. 

### Steps to reproduce

Send traces from a webflux application to a opentelemetry collector. Randomly some of the traces will show error=true with the given stacktrace. 

The issues seems to happen more in low traffic environments. In production where we have traffic constantly happens in a very low percentage of the requests, while other development environments with low traffic are getting a higher error rate.

### Expected behavior

- No exception should be raise
- Http response should be returned to clients

### Actual behavior

As describe above, traces are showing the stacktrace in the error event. Also, clients are not getting a response in the cases we have detected the error.

### Javaagent or library instrumentation version

java agent 1.29.0  - io.opentelemetry.spring-webflux-5.0:1.29.0-alpha

### Environment

**JDK**: Eclipse Adoptium OpenJDK 64-Bit Server VM 17.0.8.1+1
**OS**: Linux 5.10.186-179.751.amzn2.x86_64

**Comment by mateuszrzeszutek** [comment]
Hey @davidlopezcarrasco ,

Just to make sure, this concerns the WebFlux _server_ side, right? Not the _client_?

Can you provide some sort of repro scenario? Even if it's not deterministic, anything that'd help us reproduce this would be great.

**Comment by davidlopezcarrasco** [comment]
Hi @mateuszrzeszutek ,
Correct, this affects the server side. 
Right now is a random issue that we can't figure out why it happens, it only happens in a very very small percentage of our calls. 
My dumb theory so far is that we get some sort of connection reset from the otel collector when trying to send the metrics. 
So the collector tells the agent to keep alive connections and then, some firewall does not respect that agreement, closing the connection from the otel collectors side and getting the AbortedException. 
We have added the issue as webflux, as the only application so far that is receiving this sort of exceptions is a Webflux application. We have other spring-web applications which where we haven't seen such behavior.


I have created a small project which mimics our structure/libs in case it helps. Basically:
POST request > stores an HTML generated page to the DB
GET request > fetches the generated HTML
[reactive.zip](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/12673073/reactive.zip)

Our application doesn't connect to any other service via HTTP, so that's why I was suspicious of the connection to the collector, which is the only thing I can think of that may be involved having connections aborted.

**Comment by laurit** [comment]
Do I understand correctly that the problem is that in your observability backend you are seeing errored traces with the aforementioned stack trace and nothing else seems to be wrong? If that is the case then this has nothing to do with the collector. Basically this means that request was made to your application, like `curl --location 'http://localhost:8080/52689811-8a01-4fea-9a30-e59c40a0ed98'` in your demo app, before the application completed responding client closed the connection. You could simulate it by setting a breakpoint in https://github.com/reactor/reactor-netty/blob/cba1e58c666d5abcbfa3749689ccd537b43ec200/reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java#L289 call `channel().close()` and resume the debugger. Our instrumentation captures this and sets the status to error, but this doesn't really mean that something is wrong with the application, client just didn't bother to wait for the response from the server.

**Comment by trask** [comment]
> Our instrumentation captures this and sets the status to error, but this doesn't really mean that something is wrong with the application, client just didn't bother to wait for the response from the server.

I think ideally we wouldn't record these as errors on SERVER spans, similar to how status code 4xx's (client errors) are not recorded as errors on SERVER spans.
